//! Bulk operations for FinancialPeriod entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateFinancialPeriodDto;
use crate::application::service::FinancialPeriodService;
use crate::domain::entity::FinancialPeriod;

/// Bulk operation handler for FinancialPeriod entities.
///
/// Wraps `FinancialPeriodService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type FinancialPeriodBulkService = GenericBulkService<FinancialPeriod, CreateFinancialPeriodDto, FinancialPeriodService>;

// <<< CUSTOM
// END CUSTOM
