//! Bulk operations for Invoice entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateInvoiceDto;
use crate::application::service::InvoiceService;
use crate::domain::entity::Invoice;

/// Bulk operation handler for Invoice entities.
///
/// Wraps `InvoiceService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type InvoiceBulkService = GenericBulkService<Invoice, CreateInvoiceDto, InvoiceService>;

// <<< CUSTOM
// END CUSTOM
