//! Bulk operations
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod agent_earning_bulk;
pub mod financial_period_bulk;
pub mod payment_bulk;
pub mod payment_gateway_detail_bulk;
pub mod payment_fee_bulk;
pub mod invoice_bulk;
pub mod invoice_party_bulk;
pub mod invoice_line_item_bulk;
pub mod provider_bank_account_bulk;
pub mod refund_request_bulk;
pub mod settlement_bulk;

pub use agent_earning_bulk::AgentEarningBulkService;
pub use financial_period_bulk::FinancialPeriodBulkService;
pub use payment_bulk::PaymentBulkService;
pub use payment_gateway_detail_bulk::PaymentGatewayDetailBulkService;
pub use payment_fee_bulk::PaymentFeeBulkService;
pub use invoice_bulk::InvoiceBulkService;
pub use invoice_party_bulk::InvoicePartyBulkService;
pub use invoice_line_item_bulk::InvoiceLineItemBulkService;
pub use provider_bank_account_bulk::ProviderBankAccountBulkService;
pub use refund_request_bulk::RefundRequestBulkService;
pub use settlement_bulk::SettlementBulkService;

// <<< CUSTOM
// END CUSTOM
