//! Bulk operations for Payment entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePaymentDto;
use crate::application::service::PaymentService;
use crate::domain::entity::Payment;

/// Bulk operation handler for Payment entities.
///
/// Wraps `PaymentService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PaymentBulkService = GenericBulkService<Payment, CreatePaymentDto, PaymentService>;

// <<< CUSTOM
// END CUSTOM
