//! Bulk operations for PaymentGatewayDetail entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePaymentGatewayDetailDto;
use crate::application::service::PaymentGatewayDetailService;
use crate::domain::entity::PaymentGatewayDetail;

/// Bulk operation handler for PaymentGatewayDetail entities.
///
/// Wraps `PaymentGatewayDetailService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PaymentGatewayDetailBulkService = GenericBulkService<PaymentGatewayDetail, CreatePaymentGatewayDetailDto, PaymentGatewayDetailService>;

// <<< CUSTOM
// END CUSTOM
