//! Bulk operations for PurchaseInvoiceLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePurchaseInvoiceLineDto;
use crate::application::service::PurchaseInvoiceLineService;
use crate::domain::entity::PurchaseInvoiceLine;

/// Bulk operation handler for PurchaseInvoiceLine entities.
///
/// Wraps `PurchaseInvoiceLineService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PurchaseInvoiceLineBulkService = GenericBulkService<PurchaseInvoiceLine, CreatePurchaseInvoiceLineDto, PurchaseInvoiceLineService>;

// <<< CUSTOM
// END CUSTOM
