//! Bulk operations for RefundRequest entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateRefundRequestDto;
use crate::application::service::RefundRequestService;
use crate::domain::entity::RefundRequest;

/// Bulk operation handler for RefundRequest entities.
///
/// Wraps `RefundRequestService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type RefundRequestBulkService = GenericBulkService<RefundRequest, CreateRefundRequestDto, RefundRequestService>;

// <<< CUSTOM
// END CUSTOM
