//! FinancialPeriod DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::FinancialPeriod;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::FinancialPeriodStatus;
use crate::domain::entity::FinancialPeriodType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new FinancialPeriod
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateFinancialPeriodDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    pub period_type: FinancialPeriodType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub period_start: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub period_end: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub fiscal_year: i32,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 12)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fiscal_month: Option<i32>,
    pub gross_revenue: Decimal,
    pub discounts_given: Decimal,
    pub refunds_issued: Decimal,
    pub net_revenue: Decimal,
    pub cogs: Decimal,
    pub labor_cost: Decimal,
    pub material_cost: Decimal,
    pub utility_expense: Decimal,
    pub maintenance_expense: Decimal,
    pub delivery_expense: Decimal,
    pub other_expense: Decimal,
    pub platform_commission: Decimal,
    pub transaction_fees: Decimal,
    pub subscription_fees: Decimal,
    pub gross_profit: Decimal,
    pub operating_profit: Decimal,
    pub net_profit: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gross_margin_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operating_margin_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub net_margin_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revenue_growth_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profit_growth_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub average_order_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_per_kg: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_per_order: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profit_per_kg: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profit_per_order: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pnl_report_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub report_generated_at: Option<DateTime<Utc>>,
    pub status: FinancialPeriodStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub closed_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a FinancialPeriod
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateFinancialPeriodDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    pub period_type: FinancialPeriodType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub period_start: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub period_end: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub fiscal_year: i32,
    #[cfg_attr(feature = "validation", validate(range(min = 1), range(max = 12)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub fiscal_month: Option<i32>,
    pub gross_revenue: Decimal,
    pub discounts_given: Decimal,
    pub refunds_issued: Decimal,
    pub net_revenue: Decimal,
    pub cogs: Decimal,
    pub labor_cost: Decimal,
    pub material_cost: Decimal,
    pub utility_expense: Decimal,
    pub maintenance_expense: Decimal,
    pub delivery_expense: Decimal,
    pub other_expense: Decimal,
    pub platform_commission: Decimal,
    pub transaction_fees: Decimal,
    pub subscription_fees: Decimal,
    pub gross_profit: Decimal,
    pub operating_profit: Decimal,
    pub net_profit: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gross_margin_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operating_margin_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub net_margin_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revenue_growth_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profit_growth_percent: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub average_order_value: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_per_kg: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_per_order: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profit_per_kg: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profit_per_order: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pnl_report_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub report_generated_at: Option<DateTime<Utc>>,
    pub status: FinancialPeriodStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub closed_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a FinancialPeriod
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchFinancialPeriodDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period_type: Option<FinancialPeriodType>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period_start: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period_end: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fiscal_year: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fiscal_month: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gross_revenue: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discounts_given: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub refunds_issued: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub net_revenue: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cogs: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub labor_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub material_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub utility_expense: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maintenance_expense: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivery_expense: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub other_expense: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub platform_commission: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub transaction_fees: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subscription_fees: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gross_profit: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operating_profit: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub net_profit: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gross_margin_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operating_margin_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub net_margin_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revenue_growth_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profit_growth_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub average_order_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_per_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_per_order: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profit_per_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profit_per_order: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pnl_report_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub report_generated_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<FinancialPeriodStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl PatchFinancialPeriodDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.provider_id.is_some() || self.period_type.is_some() || self.period_start.is_some() || self.period_end.is_some() || self.fiscal_year.is_some() || self.fiscal_month.is_some() || self.gross_revenue.is_some() || self.discounts_given.is_some() || self.refunds_issued.is_some() || self.net_revenue.is_some() || self.cogs.is_some() || self.labor_cost.is_some() || self.material_cost.is_some() || self.utility_expense.is_some() || self.maintenance_expense.is_some() || self.delivery_expense.is_some() || self.other_expense.is_some() || self.platform_commission.is_some() || self.transaction_fees.is_some() || self.subscription_fees.is_some() || self.gross_profit.is_some() || self.operating_profit.is_some() || self.net_profit.is_some() || self.gross_margin_percent.is_some() || self.operating_margin_percent.is_some() || self.net_margin_percent.is_some() || self.revenue_growth_percent.is_some() || self.profit_growth_percent.is_some() || self.average_order_value.is_some() || self.cost_per_kg.is_some() || self.cost_per_order.is_some() || self.profit_per_kg.is_some() || self.profit_per_order.is_some() || self.pnl_report_url.is_some() || self.report_generated_at.is_some() || self.status.is_some() || self.closed_at.is_some() || self.closed_by.is_some() || self.currency.is_some() || self.notes.is_some() || self.data.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for FinancialPeriod entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinancialPeriodResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    pub period_type: FinancialPeriodType,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub period_start: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub period_end: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub fiscal_year: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fiscal_month: Option<i32>,
    pub gross_revenue: Decimal,
    pub discounts_given: Decimal,
    pub refunds_issued: Decimal,
    pub net_revenue: Decimal,
    pub cogs: Decimal,
    pub labor_cost: Decimal,
    pub material_cost: Decimal,
    pub utility_expense: Decimal,
    pub maintenance_expense: Decimal,
    pub delivery_expense: Decimal,
    pub other_expense: Decimal,
    pub platform_commission: Decimal,
    pub transaction_fees: Decimal,
    pub subscription_fees: Decimal,
    pub gross_profit: Decimal,
    pub operating_profit: Decimal,
    pub net_profit: Decimal,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gross_margin_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operating_margin_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub net_margin_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revenue_growth_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profit_growth_percent: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub average_order_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_per_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cost_per_order: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profit_per_kg: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub profit_per_order: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pnl_report_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub report_generated_at: Option<DateTime<Utc>>,
    pub status: FinancialPeriodStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub closed_by: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for FinancialPeriod entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinancialPeriodListResponseDto {
    /// List of items
    pub items: Vec<FinancialPeriodResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl FinancialPeriodListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<FinancialPeriodResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinancialPeriodSummaryDto {
    pub id: Uuid,
    pub provider_id: Uuid,
    pub period_type: FinancialPeriodType,
    pub period_start: DateTime<Utc>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<FinancialPeriod> for FinancialPeriodResponseDto {
    fn from(entity: FinancialPeriod) -> Self {
        Self {
            id: entity.id,
            provider_id: entity.provider_id,
            period_type: entity.period_type,
            period_start: entity.period_start,
            period_end: entity.period_end,
            fiscal_year: entity.fiscal_year,
            fiscal_month: entity.fiscal_month,
            gross_revenue: entity.gross_revenue,
            discounts_given: entity.discounts_given,
            refunds_issued: entity.refunds_issued,
            net_revenue: entity.net_revenue,
            cogs: entity.cogs,
            labor_cost: entity.labor_cost,
            material_cost: entity.material_cost,
            utility_expense: entity.utility_expense,
            maintenance_expense: entity.maintenance_expense,
            delivery_expense: entity.delivery_expense,
            other_expense: entity.other_expense,
            platform_commission: entity.platform_commission,
            transaction_fees: entity.transaction_fees,
            subscription_fees: entity.subscription_fees,
            gross_profit: entity.gross_profit,
            operating_profit: entity.operating_profit,
            net_profit: entity.net_profit,
            gross_margin_percent: entity.gross_margin_percent,
            operating_margin_percent: entity.operating_margin_percent,
            net_margin_percent: entity.net_margin_percent,
            revenue_growth_percent: entity.revenue_growth_percent,
            profit_growth_percent: entity.profit_growth_percent,
            average_order_value: entity.average_order_value,
            cost_per_kg: entity.cost_per_kg,
            cost_per_order: entity.cost_per_order,
            profit_per_kg: entity.profit_per_kg,
            profit_per_order: entity.profit_per_order,
            pnl_report_url: entity.pnl_report_url,
            report_generated_at: entity.report_generated_at,
            status: entity.status,
            closed_at: entity.closed_at,
            closed_by: entity.closed_by,
            currency: entity.currency,
            notes: entity.notes,
            data: entity.data,
            metadata: entity.metadata,
        }
    }
}

impl From<FinancialPeriod> for FinancialPeriodSummaryDto {
    fn from(entity: FinancialPeriod) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            provider_id: entity.provider_id,
            period_type: entity.period_type,
            period_start: entity.period_start,
            created_at,
        }
    }
}

impl From<CreateFinancialPeriodDto> for FinancialPeriod {
    fn from(dto: CreateFinancialPeriodDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            provider_id: dto.provider_id,
            period_type: dto.period_type,
            period_start: dto.period_start,
            period_end: dto.period_end,
            fiscal_year: dto.fiscal_year,
            fiscal_month: dto.fiscal_month,
            gross_revenue: dto.gross_revenue,
            discounts_given: dto.discounts_given,
            refunds_issued: dto.refunds_issued,
            net_revenue: dto.net_revenue,
            cogs: dto.cogs,
            labor_cost: dto.labor_cost,
            material_cost: dto.material_cost,
            utility_expense: dto.utility_expense,
            maintenance_expense: dto.maintenance_expense,
            delivery_expense: dto.delivery_expense,
            other_expense: dto.other_expense,
            platform_commission: dto.platform_commission,
            transaction_fees: dto.transaction_fees,
            subscription_fees: dto.subscription_fees,
            gross_profit: dto.gross_profit,
            operating_profit: dto.operating_profit,
            net_profit: dto.net_profit,
            gross_margin_percent: dto.gross_margin_percent,
            operating_margin_percent: dto.operating_margin_percent,
            net_margin_percent: dto.net_margin_percent,
            revenue_growth_percent: dto.revenue_growth_percent,
            profit_growth_percent: dto.profit_growth_percent,
            average_order_value: dto.average_order_value,
            cost_per_kg: dto.cost_per_kg,
            cost_per_order: dto.cost_per_order,
            profit_per_kg: dto.profit_per_kg,
            profit_per_order: dto.profit_per_order,
            pnl_report_url: dto.pnl_report_url,
            report_generated_at: dto.report_generated_at,
            status: dto.status,
            closed_at: dto.closed_at,
            closed_by: dto.closed_by,
            currency: dto.currency,
            notes: dto.notes,
            data: dto.data,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&FinancialPeriod> for FinancialPeriodResponseDto {
    fn from(entity: &FinancialPeriod) -> Self {
        Self {
            id: entity.id.clone(),
            provider_id: entity.provider_id.clone(),
            period_type: entity.period_type.clone(),
            period_start: entity.period_start.clone(),
            period_end: entity.period_end.clone(),
            fiscal_year: entity.fiscal_year.clone(),
            fiscal_month: entity.fiscal_month.clone(),
            gross_revenue: entity.gross_revenue.clone(),
            discounts_given: entity.discounts_given.clone(),
            refunds_issued: entity.refunds_issued.clone(),
            net_revenue: entity.net_revenue.clone(),
            cogs: entity.cogs.clone(),
            labor_cost: entity.labor_cost.clone(),
            material_cost: entity.material_cost.clone(),
            utility_expense: entity.utility_expense.clone(),
            maintenance_expense: entity.maintenance_expense.clone(),
            delivery_expense: entity.delivery_expense.clone(),
            other_expense: entity.other_expense.clone(),
            platform_commission: entity.platform_commission.clone(),
            transaction_fees: entity.transaction_fees.clone(),
            subscription_fees: entity.subscription_fees.clone(),
            gross_profit: entity.gross_profit.clone(),
            operating_profit: entity.operating_profit.clone(),
            net_profit: entity.net_profit.clone(),
            gross_margin_percent: entity.gross_margin_percent.clone(),
            operating_margin_percent: entity.operating_margin_percent.clone(),
            net_margin_percent: entity.net_margin_percent.clone(),
            revenue_growth_percent: entity.revenue_growth_percent.clone(),
            profit_growth_percent: entity.profit_growth_percent.clone(),
            average_order_value: entity.average_order_value.clone(),
            cost_per_kg: entity.cost_per_kg.clone(),
            cost_per_order: entity.cost_per_order.clone(),
            profit_per_kg: entity.profit_per_kg.clone(),
            profit_per_order: entity.profit_per_order.clone(),
            pnl_report_url: entity.pnl_report_url.clone(),
            report_generated_at: entity.report_generated_at.clone(),
            status: entity.status.clone(),
            closed_at: entity.closed_at.clone(),
            closed_by: entity.closed_by.clone(),
            currency: entity.currency.clone(),
            notes: entity.notes.clone(),
            data: entity.data.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateFinancialPeriodDto> for FinancialPeriod {
    fn from_create_dto(dto: CreateFinancialPeriodDto) -> backbone_core::ServiceResult<Self> {
        Ok(FinancialPeriod::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateFinancialPeriodDto> for FinancialPeriod {
    fn apply_update(mut self, dto: UpdateFinancialPeriodDto) -> backbone_core::ServiceResult<Self> {
        self.provider_id = dto.provider_id;
        self.period_type = dto.period_type;
        self.period_start = dto.period_start;
        self.period_end = dto.period_end;
        self.fiscal_year = dto.fiscal_year;
        self.fiscal_month = dto.fiscal_month;
        self.gross_revenue = dto.gross_revenue;
        self.discounts_given = dto.discounts_given;
        self.refunds_issued = dto.refunds_issued;
        self.net_revenue = dto.net_revenue;
        self.cogs = dto.cogs;
        self.labor_cost = dto.labor_cost;
        self.material_cost = dto.material_cost;
        self.utility_expense = dto.utility_expense;
        self.maintenance_expense = dto.maintenance_expense;
        self.delivery_expense = dto.delivery_expense;
        self.other_expense = dto.other_expense;
        self.platform_commission = dto.platform_commission;
        self.transaction_fees = dto.transaction_fees;
        self.subscription_fees = dto.subscription_fees;
        self.gross_profit = dto.gross_profit;
        self.operating_profit = dto.operating_profit;
        self.net_profit = dto.net_profit;
        self.gross_margin_percent = dto.gross_margin_percent;
        self.operating_margin_percent = dto.operating_margin_percent;
        self.net_margin_percent = dto.net_margin_percent;
        self.revenue_growth_percent = dto.revenue_growth_percent;
        self.profit_growth_percent = dto.profit_growth_percent;
        self.average_order_value = dto.average_order_value;
        self.cost_per_kg = dto.cost_per_kg;
        self.cost_per_order = dto.cost_per_order;
        self.profit_per_kg = dto.profit_per_kg;
        self.profit_per_order = dto.profit_per_order;
        self.pnl_report_url = dto.pnl_report_url;
        self.report_generated_at = dto.report_generated_at;
        self.status = dto.status;
        self.closed_at = dto.closed_at;
        self.closed_by = dto.closed_by;
        self.currency = dto.currency;
        self.notes = dto.notes;
        self.data = dto.data;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to FinancialPeriod here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

