//! InvoiceTaxLine DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::InvoiceKind;
use crate::domain::entity::InvoiceTaxLine;
use crate::domain::entity::TaxBasis;
use crate::domain::entity::TaxExigibility;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new InvoiceTaxLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateInvoiceTaxLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: InvoiceKind,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "account_id")]
    pub account_id: Uuid,
    pub basis: TaxBasis,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(alias = "taxable_base")]
    pub taxable_base: Decimal,
    pub rate: Decimal,
    #[serde(alias = "tax_amount")]
    pub tax_amount: Decimal,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "tax_template_id"
    )]
    pub tax_template_id: Option<Uuid>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "repartition_line_id"
    )]
    pub repartition_line_id: Option<Uuid>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "real_account_id"
    )]
    pub real_account_id: Option<Uuid>,
    pub exigibility: TaxExigibility,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a InvoiceTaxLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateInvoiceTaxLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: InvoiceKind,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "account_id")]
    pub account_id: Uuid,
    pub basis: TaxBasis,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(alias = "taxable_base")]
    pub taxable_base: Decimal,
    pub rate: Decimal,
    #[serde(alias = "tax_amount")]
    pub tax_amount: Decimal,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "tax_template_id"
    )]
    pub tax_template_id: Option<Uuid>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "repartition_line_id"
    )]
    pub repartition_line_id: Option<Uuid>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        alias = "real_account_id"
    )]
    pub real_account_id: Option<Uuid>,
    pub exigibility: TaxExigibility,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a InvoiceTaxLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchInvoiceTaxLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_ref")]
    pub invoice_ref: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_kind")]
    pub invoice_kind: Option<InvoiceKind>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub basis: Option<TaxBasis>,
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "taxable_base")]
    pub taxable_base: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_amount")]
    pub tax_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_template_id")]
    pub tax_template_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "repartition_line_id")]
    pub repartition_line_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "real_account_id")]
    pub real_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exigibility: Option<TaxExigibility>,
}

impl PatchInvoiceTaxLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.invoice_ref.is_some()
            || self.invoice_kind.is_some()
            || self.company_id.is_some()
            || self.account_id.is_some()
            || self.basis.is_some()
            || self.description.is_some()
            || self.taxable_base.is_some()
            || self.rate.is_some()
            || self.tax_amount.is_some()
            || self.tax_template_id.is_some()
            || self.repartition_line_id.is_some()
            || self.real_account_id.is_some()
            || self.exigibility.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for InvoiceTaxLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InvoiceTaxLineResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub invoice_ref: Uuid,
    pub invoice_kind: InvoiceKind,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub account_id: Uuid,
    pub basis: TaxBasis,
    pub description: Option<String>,
    pub taxable_base: Decimal,
    pub rate: Decimal,
    pub tax_amount: Decimal,
    pub tax_template_id: Option<Uuid>,
    pub repartition_line_id: Option<Uuid>,
    pub real_account_id: Option<Uuid>,
    pub exigibility: TaxExigibility,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for InvoiceTaxLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InvoiceTaxLineListResponseDto {
    /// List of items
    pub items: Vec<InvoiceTaxLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl InvoiceTaxLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<InvoiceTaxLineResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InvoiceTaxLineSummaryDto {
    pub id: Uuid,
    pub invoice_ref: Uuid,
    pub invoice_kind: InvoiceKind,
    pub company_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<InvoiceTaxLine> for InvoiceTaxLineResponseDto {
    fn from(entity: InvoiceTaxLine) -> Self {
        Self {
            id: entity.id,
            invoice_ref: entity.invoice_ref,
            invoice_kind: entity.invoice_kind,
            company_id: entity.company_id,
            account_id: entity.account_id,
            basis: entity.basis,
            description: entity.description,
            taxable_base: entity.taxable_base,
            rate: entity.rate,
            tax_amount: entity.tax_amount,
            tax_template_id: entity.tax_template_id,
            repartition_line_id: entity.repartition_line_id,
            real_account_id: entity.real_account_id,
            exigibility: entity.exigibility,
            metadata: entity.metadata,
        }
    }
}

impl From<InvoiceTaxLine> for InvoiceTaxLineSummaryDto {
    fn from(entity: InvoiceTaxLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            invoice_ref: entity.invoice_ref,
            invoice_kind: entity.invoice_kind,
            company_id: entity.company_id,
            created_at,
        }
    }
}

impl From<CreateInvoiceTaxLineDto> for InvoiceTaxLine {
    fn from(dto: CreateInvoiceTaxLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            invoice_ref: dto.invoice_ref,
            invoice_kind: dto.invoice_kind,
            company_id: dto.company_id,
            account_id: dto.account_id,
            basis: dto.basis,
            description: dto.description,
            taxable_base: dto.taxable_base,
            rate: dto.rate,
            tax_amount: dto.tax_amount,
            tax_template_id: dto.tax_template_id,
            repartition_line_id: dto.repartition_line_id,
            real_account_id: dto.real_account_id,
            exigibility: dto.exigibility,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&InvoiceTaxLine> for InvoiceTaxLineResponseDto {
    fn from(entity: &InvoiceTaxLine) -> Self {
        Self {
            id: entity.id.clone(),
            invoice_ref: entity.invoice_ref.clone(),
            invoice_kind: entity.invoice_kind.clone(),
            company_id: entity.company_id.clone(),
            account_id: entity.account_id.clone(),
            basis: entity.basis.clone(),
            description: entity.description.clone(),
            taxable_base: entity.taxable_base.clone(),
            rate: entity.rate.clone(),
            tax_amount: entity.tax_amount.clone(),
            tax_template_id: entity.tax_template_id.clone(),
            repartition_line_id: entity.repartition_line_id.clone(),
            real_account_id: entity.real_account_id.clone(),
            exigibility: entity.exigibility.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateInvoiceTaxLineDto> for InvoiceTaxLine {
    fn from_create_dto(dto: CreateInvoiceTaxLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(InvoiceTaxLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateInvoiceTaxLineDto> for InvoiceTaxLine {
    fn apply_update(mut self, dto: UpdateInvoiceTaxLineDto) -> backbone_core::ServiceResult<Self> {
        self.invoice_ref = dto.invoice_ref;
        self.invoice_kind = dto.invoice_kind;
        self.company_id = dto.company_id;
        self.account_id = dto.account_id;
        self.basis = dto.basis;
        self.description = dto.description;
        self.taxable_base = dto.taxable_base;
        self.rate = dto.rate;
        self.tax_amount = dto.tax_amount;
        self.tax_template_id = dto.tax_template_id;
        self.repartition_line_id = dto.repartition_line_id;
        self.real_account_id = dto.real_account_id;
        self.exigibility = dto.exigibility;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to InvoiceTaxLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
