//! Invoice DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Invoice;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::InvoiceStatus;
use crate::domain::entity::InvoiceType;
use crate::domain::entity::InvoiceableType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Invoice
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateInvoiceDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub invoice_number: String,
    pub invoice_type: InvoiceType,
    pub invoiceable_type: InvoiceableType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub invoiceable_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub issue_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    pub discount_amount: Decimal,
    pub tax_amount: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<Decimal>,
    pub total_amount: Decimal,
    pub status: InvoiceStatus,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sent_via: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pdf_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pdf_generated_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terms: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub footer: Option<String>,
    pub data: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Invoice
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateInvoiceDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub invoice_number: String,
    pub invoice_type: InvoiceType,
    pub invoiceable_type: InvoiceableType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub invoiceable_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub issue_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    pub discount_amount: Decimal,
    pub tax_amount: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<Decimal>,
    pub total_amount: Decimal,
    pub status: InvoiceStatus,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sent_via: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pdf_url: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pdf_generated_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terms: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub footer: Option<String>,
    pub data: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Invoice
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchInvoiceDto {
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_type: Option<InvoiceType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoiceable_type: Option<InvoiceableType>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoiceable_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub issue_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtotal: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<InvoiceStatus>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sent_via: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pdf_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pdf_generated_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub terms: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footer: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl PatchInvoiceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.invoice_number.is_some() || self.invoice_type.is_some() || self.invoiceable_type.is_some() || self.invoiceable_id.is_some() || self.order_id.is_some() || self.settlement_id.is_some() || self.issue_date.is_some() || self.due_date.is_some() || self.currency.is_some() || self.subtotal.is_some() || self.discount_amount.is_some() || self.tax_amount.is_some() || self.tax_rate.is_some() || self.total_amount.is_some() || self.status.is_some() || self.sent_via.is_some() || self.paid_at.is_some() || self.payment_id.is_some() || self.pdf_url.is_some() || self.pdf_generated_at.is_some() || self.notes.is_some() || self.terms.is_some() || self.footer.is_some() || self.data.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Invoice entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InvoiceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub invoice_number: String,
    pub invoice_type: InvoiceType,
    pub invoiceable_type: InvoiceableType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub invoiceable_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub issue_date: NaiveDate,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    pub discount_amount: Decimal,
    pub tax_amount: Decimal,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<Decimal>,
    pub total_amount: Decimal,
    pub status: InvoiceStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sent_via: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pdf_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pdf_generated_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub terms: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub footer: Option<String>,
    pub data: serde_json::Value,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Invoice entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InvoiceListResponseDto {
    /// List of items
    pub items: Vec<InvoiceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl InvoiceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<InvoiceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct InvoiceSummaryDto {
    pub id: Uuid,
    pub invoice_number: String,
    pub invoice_type: InvoiceType,
    pub invoiceable_type: InvoiceableType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Invoice> for InvoiceResponseDto {
    fn from(entity: Invoice) -> Self {
        Self {
            id: entity.id,
            invoice_number: entity.invoice_number,
            invoice_type: entity.invoice_type,
            invoiceable_type: entity.invoiceable_type,
            invoiceable_id: entity.invoiceable_id,
            order_id: entity.order_id,
            settlement_id: entity.settlement_id,
            issue_date: entity.issue_date,
            due_date: entity.due_date,
            currency: entity.currency,
            subtotal: entity.subtotal,
            discount_amount: entity.discount_amount,
            tax_amount: entity.tax_amount,
            tax_rate: entity.tax_rate,
            total_amount: entity.total_amount,
            status: entity.status,
            sent_via: entity.sent_via,
            paid_at: entity.paid_at,
            payment_id: entity.payment_id,
            pdf_url: entity.pdf_url,
            pdf_generated_at: entity.pdf_generated_at,
            notes: entity.notes,
            terms: entity.terms,
            footer: entity.footer,
            data: entity.data,
            metadata: entity.metadata,
        }
    }
}

impl From<Invoice> for InvoiceSummaryDto {
    fn from(entity: Invoice) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            invoice_number: entity.invoice_number,
            invoice_type: entity.invoice_type,
            invoiceable_type: entity.invoiceable_type,
            created_at,
        }
    }
}

impl From<CreateInvoiceDto> for Invoice {
    fn from(dto: CreateInvoiceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            invoice_number: dto.invoice_number,
            invoice_type: dto.invoice_type,
            invoiceable_type: dto.invoiceable_type,
            invoiceable_id: dto.invoiceable_id,
            order_id: dto.order_id,
            settlement_id: dto.settlement_id,
            issue_date: dto.issue_date,
            due_date: dto.due_date,
            currency: dto.currency,
            subtotal: dto.subtotal,
            discount_amount: dto.discount_amount,
            tax_amount: dto.tax_amount,
            tax_rate: dto.tax_rate,
            total_amount: dto.total_amount,
            status: dto.status,
            sent_via: dto.sent_via,
            paid_at: dto.paid_at,
            payment_id: dto.payment_id,
            pdf_url: dto.pdf_url,
            pdf_generated_at: dto.pdf_generated_at,
            notes: dto.notes,
            terms: dto.terms,
            footer: dto.footer,
            data: dto.data,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Invoice> for InvoiceResponseDto {
    fn from(entity: &Invoice) -> Self {
        Self {
            id: entity.id.clone(),
            invoice_number: entity.invoice_number.clone(),
            invoice_type: entity.invoice_type.clone(),
            invoiceable_type: entity.invoiceable_type.clone(),
            invoiceable_id: entity.invoiceable_id.clone(),
            order_id: entity.order_id.clone(),
            settlement_id: entity.settlement_id.clone(),
            issue_date: entity.issue_date.clone(),
            due_date: entity.due_date.clone(),
            currency: entity.currency.clone(),
            subtotal: entity.subtotal.clone(),
            discount_amount: entity.discount_amount.clone(),
            tax_amount: entity.tax_amount.clone(),
            tax_rate: entity.tax_rate.clone(),
            total_amount: entity.total_amount.clone(),
            status: entity.status.clone(),
            sent_via: entity.sent_via.clone(),
            paid_at: entity.paid_at.clone(),
            payment_id: entity.payment_id.clone(),
            pdf_url: entity.pdf_url.clone(),
            pdf_generated_at: entity.pdf_generated_at.clone(),
            notes: entity.notes.clone(),
            terms: entity.terms.clone(),
            footer: entity.footer.clone(),
            data: entity.data.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateInvoiceDto> for Invoice {
    fn from_create_dto(dto: CreateInvoiceDto) -> backbone_core::ServiceResult<Self> {
        Ok(Invoice::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateInvoiceDto> for Invoice {
    fn apply_update(mut self, dto: UpdateInvoiceDto) -> backbone_core::ServiceResult<Self> {
        self.invoice_number = dto.invoice_number;
        self.invoice_type = dto.invoice_type;
        self.invoiceable_type = dto.invoiceable_type;
        self.invoiceable_id = dto.invoiceable_id;
        self.order_id = dto.order_id;
        self.settlement_id = dto.settlement_id;
        self.issue_date = dto.issue_date;
        self.due_date = dto.due_date;
        self.currency = dto.currency;
        self.subtotal = dto.subtotal;
        self.discount_amount = dto.discount_amount;
        self.tax_amount = dto.tax_amount;
        self.tax_rate = dto.tax_rate;
        self.total_amount = dto.total_amount;
        self.status = dto.status;
        self.sent_via = dto.sent_via;
        self.paid_at = dto.paid_at;
        self.payment_id = dto.payment_id;
        self.pdf_url = dto.pdf_url;
        self.pdf_generated_at = dto.pdf_generated_at;
        self.notes = dto.notes;
        self.terms = dto.terms;
        self.footer = dto.footer;
        self.data = dto.data;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Invoice here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

