//! Payment DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Payment;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PayableType;
use crate::domain::entity::PayeeType;
use crate::domain::entity::PayerType;
use crate::domain::entity::PaymentChannel;
use crate::domain::entity::PaymentGateway;
use crate::domain::entity::PaymentTransactionStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Payment
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePaymentDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payment_number: String,
    pub payable_type: PayableType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payable_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    pub payer_type: PayerType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payer_id: Uuid,
    pub payee_type: PayeeType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub amount: Decimal,
    pub net_amount: Decimal,
    pub gateway: PaymentGateway,
    pub channel: PaymentChannel,
    pub status: PaymentTransactionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Payment
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePaymentDto {
    #[cfg_attr(feature = "validation", validate(length(max = 30)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payment_number: String,
    pub payable_type: PayableType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payable_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    pub payer_type: PayerType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payer_id: Uuid,
    pub payee_type: PayeeType,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub amount: Decimal,
    pub net_amount: Decimal,
    pub gateway: PaymentGateway,
    pub channel: PaymentChannel,
    pub status: PaymentTransactionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Payment
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPaymentDto {
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payable_type: Option<PayableType>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payable_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payer_type: Option<PayerType>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payer_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payee_type: Option<PayeeType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub net_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gateway: Option<PaymentGateway>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<PaymentChannel>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PaymentTransactionStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl PatchPaymentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.payment_number.is_some() || self.payable_type.is_some() || self.payable_id.is_some() || self.order_id.is_some() || self.payer_type.is_some() || self.payer_id.is_some() || self.payee_type.is_some() || self.payee_id.is_some() || self.currency.is_some() || self.amount.is_some() || self.net_amount.is_some() || self.gateway.is_some() || self.channel.is_some() || self.status.is_some() || self.expires_at.is_some() || self.paid_at.is_some() || self.failed_at.is_some() || self.cancelled_at.is_some() || self.failure_code.is_some() || self.failure_message.is_some() || self.settlement_id.is_some() || self.description.is_some() || self.notes.is_some() || self.data.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Payment entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payment_number: String,
    pub payable_type: PayableType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payable_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_id: Option<Uuid>,
    pub payer_type: PayerType,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payer_id: Uuid,
    pub payee_type: PayeeType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub amount: Decimal,
    pub net_amount: Decimal,
    pub gateway: PaymentGateway,
    pub channel: PaymentChannel,
    pub status: PaymentTransactionStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub paid_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settlement_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Payment entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentListResponseDto {
    /// List of items
    pub items: Vec<PaymentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PaymentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PaymentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentSummaryDto {
    pub id: Uuid,
    pub payment_number: String,
    pub payable_type: PayableType,
    pub payable_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Payment> for PaymentResponseDto {
    fn from(entity: Payment) -> Self {
        Self {
            id: entity.id,
            payment_number: entity.payment_number,
            payable_type: entity.payable_type,
            payable_id: entity.payable_id,
            order_id: entity.order_id,
            payer_type: entity.payer_type,
            payer_id: entity.payer_id,
            payee_type: entity.payee_type,
            payee_id: entity.payee_id,
            currency: entity.currency,
            amount: entity.amount,
            net_amount: entity.net_amount,
            gateway: entity.gateway,
            channel: entity.channel,
            status: entity.status,
            expires_at: entity.expires_at,
            paid_at: entity.paid_at,
            failed_at: entity.failed_at,
            cancelled_at: entity.cancelled_at,
            failure_code: entity.failure_code,
            failure_message: entity.failure_message,
            settlement_id: entity.settlement_id,
            description: entity.description,
            notes: entity.notes,
            data: entity.data,
            metadata: entity.metadata,
        }
    }
}

impl From<Payment> for PaymentSummaryDto {
    fn from(entity: Payment) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            payment_number: entity.payment_number,
            payable_type: entity.payable_type,
            payable_id: entity.payable_id,
            created_at,
        }
    }
}

impl From<CreatePaymentDto> for Payment {
    fn from(dto: CreatePaymentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            payment_number: dto.payment_number,
            payable_type: dto.payable_type,
            payable_id: dto.payable_id,
            order_id: dto.order_id,
            payer_type: dto.payer_type,
            payer_id: dto.payer_id,
            payee_type: dto.payee_type,
            payee_id: dto.payee_id,
            currency: dto.currency,
            amount: dto.amount,
            net_amount: dto.net_amount,
            gateway: dto.gateway,
            channel: dto.channel,
            status: dto.status,
            expires_at: dto.expires_at,
            paid_at: dto.paid_at,
            failed_at: dto.failed_at,
            cancelled_at: dto.cancelled_at,
            failure_code: dto.failure_code,
            failure_message: dto.failure_message,
            settlement_id: dto.settlement_id,
            description: dto.description,
            notes: dto.notes,
            data: dto.data,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Payment> for PaymentResponseDto {
    fn from(entity: &Payment) -> Self {
        Self {
            id: entity.id.clone(),
            payment_number: entity.payment_number.clone(),
            payable_type: entity.payable_type.clone(),
            payable_id: entity.payable_id.clone(),
            order_id: entity.order_id.clone(),
            payer_type: entity.payer_type.clone(),
            payer_id: entity.payer_id.clone(),
            payee_type: entity.payee_type.clone(),
            payee_id: entity.payee_id.clone(),
            currency: entity.currency.clone(),
            amount: entity.amount.clone(),
            net_amount: entity.net_amount.clone(),
            gateway: entity.gateway.clone(),
            channel: entity.channel.clone(),
            status: entity.status.clone(),
            expires_at: entity.expires_at.clone(),
            paid_at: entity.paid_at.clone(),
            failed_at: entity.failed_at.clone(),
            cancelled_at: entity.cancelled_at.clone(),
            failure_code: entity.failure_code.clone(),
            failure_message: entity.failure_message.clone(),
            settlement_id: entity.settlement_id.clone(),
            description: entity.description.clone(),
            notes: entity.notes.clone(),
            data: entity.data.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePaymentDto> for Payment {
    fn from_create_dto(dto: CreatePaymentDto) -> backbone_core::ServiceResult<Self> {
        Ok(Payment::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePaymentDto> for Payment {
    fn apply_update(mut self, dto: UpdatePaymentDto) -> backbone_core::ServiceResult<Self> {
        self.payment_number = dto.payment_number;
        self.payable_type = dto.payable_type;
        self.payable_id = dto.payable_id;
        self.order_id = dto.order_id;
        self.payer_type = dto.payer_type;
        self.payer_id = dto.payer_id;
        self.payee_type = dto.payee_type;
        self.payee_id = dto.payee_id;
        self.currency = dto.currency;
        self.amount = dto.amount;
        self.net_amount = dto.net_amount;
        self.gateway = dto.gateway;
        self.channel = dto.channel;
        self.status = dto.status;
        self.expires_at = dto.expires_at;
        self.paid_at = dto.paid_at;
        self.failed_at = dto.failed_at;
        self.cancelled_at = dto.cancelled_at;
        self.failure_code = dto.failure_code;
        self.failure_message = dto.failure_message;
        self.settlement_id = dto.settlement_id;
        self.description = dto.description;
        self.notes = dto.notes;
        self.data = dto.data;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Payment here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

