//! PaymentGatewayDetail DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PaymentGatewayDetail;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PaymentGatewayDetail
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePaymentGatewayDetailDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payment_id: Uuid,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invoice_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checkout_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qr_code_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub virtual_account_number: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub virtual_account_bank: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub webhook_payload: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub webhook_received_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PaymentGatewayDetail
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePaymentGatewayDetailDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payment_id: Uuid,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub invoice_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checkout_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qr_code_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub virtual_account_number: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub virtual_account_bank: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub webhook_payload: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub webhook_received_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PaymentGatewayDetail
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPaymentGatewayDetailDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checkout_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qr_code_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub virtual_account_number: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub virtual_account_bank: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_payload: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_received_at: Option<DateTime<Utc>>,
}

impl PatchPaymentGatewayDetailDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.payment_id.is_some() || self.external_id.is_some() || self.invoice_url.is_some() || self.checkout_url.is_some() || self.qr_code_url.is_some() || self.virtual_account_number.is_some() || self.virtual_account_bank.is_some() || self.webhook_payload.is_some() || self.webhook_received_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PaymentGatewayDetail entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentGatewayDetailResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payment_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub invoice_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub checkout_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qr_code_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub virtual_account_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub virtual_account_bank: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_payload: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub webhook_received_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PaymentGatewayDetail entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentGatewayDetailListResponseDto {
    /// List of items
    pub items: Vec<PaymentGatewayDetailResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PaymentGatewayDetailListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PaymentGatewayDetailResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentGatewayDetailSummaryDto {
    pub id: Uuid,
    pub payment_id: Uuid,
    pub external_id: Option<String>,
    pub invoice_url: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PaymentGatewayDetail> for PaymentGatewayDetailResponseDto {
    fn from(entity: PaymentGatewayDetail) -> Self {
        Self {
            id: entity.id,
            payment_id: entity.payment_id,
            external_id: entity.external_id,
            invoice_url: entity.invoice_url,
            checkout_url: entity.checkout_url,
            qr_code_url: entity.qr_code_url,
            virtual_account_number: entity.virtual_account_number,
            virtual_account_bank: entity.virtual_account_bank,
            webhook_payload: entity.webhook_payload,
            webhook_received_at: entity.webhook_received_at,
            metadata: entity.metadata,
        }
    }
}

impl From<PaymentGatewayDetail> for PaymentGatewayDetailSummaryDto {
    fn from(entity: PaymentGatewayDetail) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            payment_id: entity.payment_id,
            external_id: entity.external_id,
            invoice_url: entity.invoice_url,
            created_at,
        }
    }
}

impl From<CreatePaymentGatewayDetailDto> for PaymentGatewayDetail {
    fn from(dto: CreatePaymentGatewayDetailDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            payment_id: dto.payment_id,
            external_id: dto.external_id,
            invoice_url: dto.invoice_url,
            checkout_url: dto.checkout_url,
            qr_code_url: dto.qr_code_url,
            virtual_account_number: dto.virtual_account_number,
            virtual_account_bank: dto.virtual_account_bank,
            webhook_payload: dto.webhook_payload,
            webhook_received_at: dto.webhook_received_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PaymentGatewayDetail> for PaymentGatewayDetailResponseDto {
    fn from(entity: &PaymentGatewayDetail) -> Self {
        Self {
            id: entity.id.clone(),
            payment_id: entity.payment_id.clone(),
            external_id: entity.external_id.clone(),
            invoice_url: entity.invoice_url.clone(),
            checkout_url: entity.checkout_url.clone(),
            qr_code_url: entity.qr_code_url.clone(),
            virtual_account_number: entity.virtual_account_number.clone(),
            virtual_account_bank: entity.virtual_account_bank.clone(),
            webhook_payload: entity.webhook_payload.clone(),
            webhook_received_at: entity.webhook_received_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePaymentGatewayDetailDto> for PaymentGatewayDetail {
    fn from_create_dto(dto: CreatePaymentGatewayDetailDto) -> backbone_core::ServiceResult<Self> {
        Ok(PaymentGatewayDetail::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePaymentGatewayDetailDto> for PaymentGatewayDetail {
    fn apply_update(mut self, dto: UpdatePaymentGatewayDetailDto) -> backbone_core::ServiceResult<Self> {
        self.payment_id = dto.payment_id;
        self.external_id = dto.external_id;
        self.invoice_url = dto.invoice_url;
        self.checkout_url = dto.checkout_url;
        self.qr_code_url = dto.qr_code_url;
        self.virtual_account_number = dto.virtual_account_number;
        self.virtual_account_bank = dto.virtual_account_bank;
        self.webhook_payload = dto.webhook_payload;
        self.webhook_received_at = dto.webhook_received_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PaymentGatewayDetail here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

