//! PaymentSchedule DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PaymentSchedule;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::InvoiceKind;
use crate::domain::entity::PaymentScheduleStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PaymentSchedule
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePaymentScheduleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: InvoiceKind,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "installment_no")]
    pub installment_no: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "due_date")]
    pub due_date: NaiveDate,
    pub amount: Decimal,
    #[serde(alias = "paid_amount")]
    pub paid_amount: Decimal,
    pub status: PaymentScheduleStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PaymentSchedule
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePaymentScheduleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_ref")]
    pub invoice_ref: Uuid,
    #[serde(alias = "invoice_kind")]
    pub invoice_kind: InvoiceKind,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "installment_no")]
    pub installment_no: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "due_date")]
    pub due_date: NaiveDate,
    pub amount: Decimal,
    #[serde(alias = "paid_amount")]
    pub paid_amount: Decimal,
    pub status: PaymentScheduleStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PaymentSchedule
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPaymentScheduleDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_ref")]
    pub invoice_ref: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_kind")]
    pub invoice_kind: Option<InvoiceKind>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "installment_no")]
    pub installment_no: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "paid_amount")]
    pub paid_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PaymentScheduleStatus>,
}

impl PatchPaymentScheduleDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.invoice_ref.is_some() || self.invoice_kind.is_some() || self.company_id.is_some() || self.installment_no.is_some() || self.due_date.is_some() || self.amount.is_some() || self.paid_amount.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PaymentSchedule entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentScheduleResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub invoice_ref: Uuid,
    pub invoice_kind: InvoiceKind,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub installment_no: i32,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub due_date: NaiveDate,
    pub amount: Decimal,
    pub paid_amount: Decimal,
    pub status: PaymentScheduleStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PaymentSchedule entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentScheduleListResponseDto {
    /// List of items
    pub items: Vec<PaymentScheduleResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PaymentScheduleListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PaymentScheduleResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PaymentScheduleSummaryDto {
    pub id: Uuid,
    pub invoice_ref: Uuid,
    pub invoice_kind: InvoiceKind,
    pub company_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PaymentSchedule> for PaymentScheduleResponseDto {
    fn from(entity: PaymentSchedule) -> Self {
        Self {
            id: entity.id,
            invoice_ref: entity.invoice_ref,
            invoice_kind: entity.invoice_kind,
            company_id: entity.company_id,
            installment_no: entity.installment_no,
            due_date: entity.due_date,
            amount: entity.amount,
            paid_amount: entity.paid_amount,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<PaymentSchedule> for PaymentScheduleSummaryDto {
    fn from(entity: PaymentSchedule) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            invoice_ref: entity.invoice_ref,
            invoice_kind: entity.invoice_kind,
            company_id: entity.company_id,
            created_at,
        }
    }
}

impl From<CreatePaymentScheduleDto> for PaymentSchedule {
    fn from(dto: CreatePaymentScheduleDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            invoice_ref: dto.invoice_ref,
            invoice_kind: dto.invoice_kind,
            company_id: dto.company_id,
            installment_no: dto.installment_no,
            due_date: dto.due_date,
            amount: dto.amount,
            paid_amount: dto.paid_amount,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PaymentSchedule> for PaymentScheduleResponseDto {
    fn from(entity: &PaymentSchedule) -> Self {
        Self {
            id: entity.id.clone(),
            invoice_ref: entity.invoice_ref.clone(),
            invoice_kind: entity.invoice_kind.clone(),
            company_id: entity.company_id.clone(),
            installment_no: entity.installment_no.clone(),
            due_date: entity.due_date.clone(),
            amount: entity.amount.clone(),
            paid_amount: entity.paid_amount.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePaymentScheduleDto> for PaymentSchedule {
    fn from_create_dto(dto: CreatePaymentScheduleDto) -> backbone_core::ServiceResult<Self> {
        Ok(PaymentSchedule::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePaymentScheduleDto> for PaymentSchedule {
    fn apply_update(mut self, dto: UpdatePaymentScheduleDto) -> backbone_core::ServiceResult<Self> {
        self.invoice_ref = dto.invoice_ref;
        self.invoice_kind = dto.invoice_kind;
        self.company_id = dto.company_id;
        self.installment_no = dto.installment_no;
        self.due_date = dto.due_date;
        self.amount = dto.amount;
        self.paid_amount = dto.paid_amount;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PaymentSchedule here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
