//! PurchaseInvoice DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PurchaseInvoice;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::GlPostingState;
use crate::domain::entity::InvoiceStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PurchaseInvoice
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePurchaseInvoiceDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "invoice_number")]
    pub invoice_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "supplier_id")]
    pub supplier_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_po_id")]
    pub source_po_id: Option<Uuid>,
    pub status: InvoiceStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "posting_date")]
    pub posting_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "net_total")]
    pub net_total: Decimal,
    #[serde(alias = "tax_total")]
    pub tax_total: Decimal,
    #[serde(alias = "withholding_total")]
    pub withholding_total: Decimal,
    #[serde(alias = "grand_total")]
    pub grand_total: Decimal,
    #[serde(alias = "outstanding_amount")]
    pub outstanding_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "payable_account_id")]
    pub payable_account_id: Uuid,
    #[serde(alias = "posting_state")]
    pub posting_state: GlPostingState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PurchaseInvoice
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePurchaseInvoiceDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "invoice_number")]
    pub invoice_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "supplier_id")]
    pub supplier_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "source_po_id")]
    pub source_po_id: Option<Uuid>,
    pub status: InvoiceStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "posting_date")]
    pub posting_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(alias = "net_total")]
    pub net_total: Decimal,
    #[serde(alias = "tax_total")]
    pub tax_total: Decimal,
    #[serde(alias = "withholding_total")]
    pub withholding_total: Decimal,
    #[serde(alias = "grand_total")]
    pub grand_total: Decimal,
    #[serde(alias = "outstanding_amount")]
    pub outstanding_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "payable_account_id")]
    pub payable_account_id: Uuid,
    #[serde(alias = "posting_state")]
    pub posting_state: GlPostingState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PurchaseInvoice
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPurchaseInvoiceDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_number")]
    pub invoice_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "supplier_id")]
    pub supplier_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "source_po_id")]
    pub source_po_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<InvoiceStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "posting_date")]
    pub posting_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "net_total")]
    pub net_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_total")]
    pub tax_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "withholding_total")]
    pub withholding_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "grand_total")]
    pub grand_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "outstanding_amount")]
    pub outstanding_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "payable_account_id")]
    pub payable_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "posting_state")]
    pub posting_state: Option<GlPostingState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchPurchaseInvoiceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.invoice_number.is_some() || self.company_id.is_some() || self.branch_id.is_some() || self.supplier_id.is_some() || self.source_po_id.is_some() || self.status.is_some() || self.posting_date.is_some() || self.due_date.is_some() || self.currency.is_some() || self.net_total.is_some() || self.tax_total.is_some() || self.withholding_total.is_some() || self.grand_total.is_some() || self.outstanding_amount.is_some() || self.payable_account_id.is_some() || self.posting_state.is_some() || self.journal_id.is_some() || self.accounting_post_id.is_some() || self.posted_at.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PurchaseInvoice entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PurchaseInvoiceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub invoice_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub supplier_id: Uuid,
    pub source_po_id: Option<Uuid>,
    pub status: InvoiceStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub posting_date: NaiveDate,
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub net_total: Decimal,
    pub tax_total: Decimal,
    pub withholding_total: Decimal,
    pub grand_total: Decimal,
    pub outstanding_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub payable_account_id: Uuid,
    pub posting_state: GlPostingState,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub posted_at: Option<DateTime<Utc>>,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PurchaseInvoice entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PurchaseInvoiceListResponseDto {
    /// List of items
    pub items: Vec<PurchaseInvoiceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PurchaseInvoiceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PurchaseInvoiceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PurchaseInvoiceSummaryDto {
    pub id: Uuid,
    pub invoice_number: String,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PurchaseInvoice> for PurchaseInvoiceResponseDto {
    fn from(entity: PurchaseInvoice) -> Self {
        Self {
            id: entity.id,
            invoice_number: entity.invoice_number,
            company_id: entity.company_id,
            branch_id: entity.branch_id,
            supplier_id: entity.supplier_id,
            source_po_id: entity.source_po_id,
            status: entity.status,
            posting_date: entity.posting_date,
            due_date: entity.due_date,
            currency: entity.currency,
            net_total: entity.net_total,
            tax_total: entity.tax_total,
            withholding_total: entity.withholding_total,
            grand_total: entity.grand_total,
            outstanding_amount: entity.outstanding_amount,
            payable_account_id: entity.payable_account_id,
            posting_state: entity.posting_state,
            journal_id: entity.journal_id,
            accounting_post_id: entity.accounting_post_id,
            posted_at: entity.posted_at,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<PurchaseInvoice> for PurchaseInvoiceSummaryDto {
    fn from(entity: PurchaseInvoice) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            invoice_number: entity.invoice_number,
            company_id: entity.company_id,
            branch_id: entity.branch_id,
            created_at,
        }
    }
}

impl From<CreatePurchaseInvoiceDto> for PurchaseInvoice {
    fn from(dto: CreatePurchaseInvoiceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            invoice_number: dto.invoice_number,
            company_id: dto.company_id,
            branch_id: dto.branch_id,
            supplier_id: dto.supplier_id,
            source_po_id: dto.source_po_id,
            status: dto.status,
            posting_date: dto.posting_date,
            due_date: dto.due_date,
            currency: dto.currency,
            net_total: dto.net_total,
            tax_total: dto.tax_total,
            withholding_total: dto.withholding_total,
            grand_total: dto.grand_total,
            outstanding_amount: dto.outstanding_amount,
            payable_account_id: dto.payable_account_id,
            posting_state: dto.posting_state,
            journal_id: dto.journal_id,
            accounting_post_id: dto.accounting_post_id,
            posted_at: dto.posted_at,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PurchaseInvoice> for PurchaseInvoiceResponseDto {
    fn from(entity: &PurchaseInvoice) -> Self {
        Self {
            id: entity.id.clone(),
            invoice_number: entity.invoice_number.clone(),
            company_id: entity.company_id.clone(),
            branch_id: entity.branch_id.clone(),
            supplier_id: entity.supplier_id.clone(),
            source_po_id: entity.source_po_id.clone(),
            status: entity.status.clone(),
            posting_date: entity.posting_date.clone(),
            due_date: entity.due_date.clone(),
            currency: entity.currency.clone(),
            net_total: entity.net_total.clone(),
            tax_total: entity.tax_total.clone(),
            withholding_total: entity.withholding_total.clone(),
            grand_total: entity.grand_total.clone(),
            outstanding_amount: entity.outstanding_amount.clone(),
            payable_account_id: entity.payable_account_id.clone(),
            posting_state: entity.posting_state.clone(),
            journal_id: entity.journal_id.clone(),
            accounting_post_id: entity.accounting_post_id.clone(),
            posted_at: entity.posted_at.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePurchaseInvoiceDto> for PurchaseInvoice {
    fn from_create_dto(dto: CreatePurchaseInvoiceDto) -> backbone_core::ServiceResult<Self> {
        Ok(PurchaseInvoice::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePurchaseInvoiceDto> for PurchaseInvoice {
    fn apply_update(mut self, dto: UpdatePurchaseInvoiceDto) -> backbone_core::ServiceResult<Self> {
        self.invoice_number = dto.invoice_number;
        self.company_id = dto.company_id;
        self.branch_id = dto.branch_id;
        self.supplier_id = dto.supplier_id;
        self.source_po_id = dto.source_po_id;
        self.status = dto.status;
        self.posting_date = dto.posting_date;
        self.due_date = dto.due_date;
        self.currency = dto.currency;
        self.net_total = dto.net_total;
        self.tax_total = dto.tax_total;
        self.withholding_total = dto.withholding_total;
        self.grand_total = dto.grand_total;
        self.outstanding_amount = dto.outstanding_amount;
        self.payable_account_id = dto.payable_account_id;
        self.posting_state = dto.posting_state;
        self.journal_id = dto.journal_id;
        self.accounting_post_id = dto.accounting_post_id;
        self.posted_at = dto.posted_at;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PurchaseInvoice here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
