//! PurchaseInvoiceLine DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PurchaseInvoiceLine;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PurchaseInvoiceLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePurchaseInvoiceLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "invoice_id")]
    pub invoice_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "expense_account_id")]
    pub expense_account_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub quantity: Decimal,
    #[serde(alias = "unit_price")]
    pub unit_price: Decimal,
    #[serde(alias = "net_amount")]
    pub net_amount: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PurchaseInvoiceLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePurchaseInvoiceLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "invoice_id")]
    pub invoice_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(alias = "expense_account_id")]
    pub expense_account_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub quantity: Decimal,
    #[serde(alias = "unit_price")]
    pub unit_price: Decimal,
    #[serde(alias = "net_amount")]
    pub net_amount: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PurchaseInvoiceLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPurchaseInvoiceLineDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_id")]
    pub invoice_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    #[serde(skip_serializing_if = "Option::is_none", alias = "expense_account_id")]
    pub expense_account_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "unit_price")]
    pub unit_price: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "net_amount")]
    pub net_amount: Option<Decimal>,
}

impl PatchPurchaseInvoiceLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.invoice_id.is_some()
            || self.company_id.is_some()
            || self.item_id.is_some()
            || self.expense_account_id.is_some()
            || self.description.is_some()
            || self.quantity.is_some()
            || self.unit_price.is_some()
            || self.net_amount.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PurchaseInvoiceLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PurchaseInvoiceLineResponseDto {
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub invoice_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub company_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub item_id: Uuid,
    #[cfg_attr(
        feature = "openapi",
        schema(example = "550e8400-e29b-41d4-a716-446655440000")
    )]
    pub expense_account_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub net_amount: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PurchaseInvoiceLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PurchaseInvoiceLineListResponseDto {
    /// List of items
    pub items: Vec<PurchaseInvoiceLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PurchaseInvoiceLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(
        items: Vec<PurchaseInvoiceLineResponseDto>,
        total: u64,
        page: u32,
        per_page: u32,
    ) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PurchaseInvoiceLineSummaryDto {
    pub id: Uuid,
    pub invoice_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PurchaseInvoiceLine> for PurchaseInvoiceLineResponseDto {
    fn from(entity: PurchaseInvoiceLine) -> Self {
        Self {
            id: entity.id,
            invoice_id: entity.invoice_id,
            company_id: entity.company_id,
            item_id: entity.item_id,
            expense_account_id: entity.expense_account_id,
            description: entity.description,
            quantity: entity.quantity,
            unit_price: entity.unit_price,
            net_amount: entity.net_amount,
            metadata: entity.metadata,
        }
    }
}

impl From<PurchaseInvoiceLine> for PurchaseInvoiceLineSummaryDto {
    fn from(entity: PurchaseInvoiceLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            invoice_id: entity.invoice_id,
            company_id: entity.company_id,
            item_id: entity.item_id,
            created_at,
        }
    }
}

impl From<CreatePurchaseInvoiceLineDto> for PurchaseInvoiceLine {
    fn from(dto: CreatePurchaseInvoiceLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            invoice_id: dto.invoice_id,
            company_id: dto.company_id,
            item_id: dto.item_id,
            expense_account_id: dto.expense_account_id,
            description: dto.description,
            quantity: dto.quantity,
            unit_price: dto.unit_price,
            net_amount: dto.net_amount,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PurchaseInvoiceLine> for PurchaseInvoiceLineResponseDto {
    fn from(entity: &PurchaseInvoiceLine) -> Self {
        Self {
            id: entity.id.clone(),
            invoice_id: entity.invoice_id.clone(),
            company_id: entity.company_id.clone(),
            item_id: entity.item_id.clone(),
            expense_account_id: entity.expense_account_id.clone(),
            description: entity.description.clone(),
            quantity: entity.quantity.clone(),
            unit_price: entity.unit_price.clone(),
            net_amount: entity.net_amount.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePurchaseInvoiceLineDto> for PurchaseInvoiceLine {
    fn from_create_dto(dto: CreatePurchaseInvoiceLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(PurchaseInvoiceLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePurchaseInvoiceLineDto> for PurchaseInvoiceLine {
    fn apply_update(
        mut self,
        dto: UpdatePurchaseInvoiceLineDto,
    ) -> backbone_core::ServiceResult<Self> {
        self.invoice_id = dto.invoice_id;
        self.company_id = dto.company_id;
        self.item_id = dto.item_id;
        self.expense_account_id = dto.expense_account_id;
        self.description = dto.description;
        self.quantity = dto.quantity;
        self.unit_price = dto.unit_price;
        self.net_amount = dto.net_amount;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PurchaseInvoiceLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
