//! Domain policy for InvoiceTaxLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use crate::domain::entity::InvoiceTaxLine;
use backbone_core::PermitAllPolicy;

/// Domain policy for InvoiceTaxLine — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<InvoiceTaxLine>` in the `// <<< CUSTOM` zone.
pub type InvoiceTaxLineDomainPolicy = PermitAllPolicy<InvoiceTaxLine>;

// <<< CUSTOM
// END CUSTOM
