//! Domain policy for InvoiceLineItem aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::InvoiceLineItem;

/// Domain policy for InvoiceLineItem — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<InvoiceLineItem>` in the `// <<< CUSTOM` zone.
pub type InvoiceLineItemDomainPolicy = PermitAllPolicy<InvoiceLineItem>;

// <<< CUSTOM
// END CUSTOM
