//! Domain policy for RefundRequest aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::RefundRequest;

/// Domain policy for RefundRequest — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<RefundRequest>` in the `// <<< CUSTOM` zone.
pub type RefundRequestDomainPolicy = PermitAllPolicy<RefundRequest>;

// <<< CUSTOM
// END CUSTOM
