//! Domain policy for SalesInvoice aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use crate::domain::entity::SalesInvoice;
use backbone_core::PermitAllPolicy;

/// Domain policy for SalesInvoice — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<SalesInvoice>` in the `// <<< CUSTOM` zone.
pub type SalesInvoiceDomainPolicy = PermitAllPolicy<SalesInvoice>;

// <<< CUSTOM
// END CUSTOM
