//! Domain policy for Settlement aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Settlement;

/// Domain policy for Settlement — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Settlement>` in the `// <<< CUSTOM` zone.
pub type SettlementDomainPolicy = PermitAllPolicy<Settlement>;

// <<< CUSTOM
// END CUSTOM
