//! Application service for AgentEarning entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `agent_earning_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAgentEarningDto, UpdateAgentEarningDto};
use crate::domain::entity::AgentEarning;
use crate::infrastructure::persistence::AgentEarningRepository;

/// Application service for AgentEarning entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `agent_earning_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AgentEarningServiceCustom {
///     inner: Arc<AgentEarningService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AgentEarningService = GenericCrudService<
    AgentEarning,
    CreateAgentEarningDto,
    UpdateAgentEarningDto,
    AgentEarningRepository,
>;

// <<< CUSTOM
// END CUSTOM
