//! Application service for InvoiceParty entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `invoice_party_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateInvoicePartyDto, UpdateInvoicePartyDto};
use crate::domain::entity::InvoiceParty;
use crate::infrastructure::persistence::InvoicePartyRepository;

/// Application service for InvoiceParty entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `invoice_party_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct InvoicePartyServiceCustom {
///     inner: Arc<InvoicePartyService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type InvoicePartyService = GenericCrudService<
    InvoiceParty,
    CreateInvoicePartyDto,
    UpdateInvoicePartyDto,
    InvoicePartyRepository,
>;

// <<< CUSTOM
// END CUSTOM
