//! Application service for Invoice entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `invoice_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateInvoiceDto, UpdateInvoiceDto};
use crate::domain::entity::Invoice;
use crate::infrastructure::persistence::InvoiceRepository;

/// Application service for Invoice entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `invoice_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct InvoiceServiceCustom {
///     inner: Arc<InvoiceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type InvoiceService = GenericCrudService<
    Invoice,
    CreateInvoiceDto,
    UpdateInvoiceDto,
    InvoiceRepository,
>;

// <<< CUSTOM
// END CUSTOM
