//! Application services
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

mod agent_earning_service;
mod financial_period_service;
mod payment_service;
mod payment_gateway_detail_service;
mod payment_fee_service;
mod invoice_service;
mod invoice_party_service;
mod invoice_line_item_service;
mod provider_bank_account_service;
mod refund_request_service;
mod settlement_service;

// <<< CUSTOM
// END CUSTOM

pub use agent_earning_service::AgentEarningService;
pub use financial_period_service::FinancialPeriodService;
pub use payment_service::PaymentService;
pub use payment_gateway_detail_service::PaymentGatewayDetailService;
pub use payment_fee_service::PaymentFeeService;
pub use invoice_service::InvoiceService;
pub use invoice_party_service::InvoicePartyService;
pub use invoice_line_item_service::InvoiceLineItemService;
pub use provider_bank_account_service::ProviderBankAccountService;
pub use refund_request_service::RefundRequestService;
pub use settlement_service::SettlementService;
// <<< CUSTOM
// END CUSTOM
