//! Application service for PaymentTerm entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `payment_term_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::PaymentTerm;
use crate::infrastructure::persistence::PaymentTermRepository;
use crate::presentation::dto::{CreatePaymentTermDto, UpdatePaymentTermDto};

/// Application service for PaymentTerm entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `payment_term_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PaymentTermServiceCustom {
///     inner: Arc<PaymentTermService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PaymentTermService = GenericCrudService<
    PaymentTerm,
    CreatePaymentTermDto,
    UpdatePaymentTermDto,
    PaymentTermRepository,
>;

// <<< CUSTOM
// END CUSTOM
