//! Application service for PaymentTermLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `payment_term_line_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::PaymentTermLine;
use crate::infrastructure::persistence::PaymentTermLineRepository;
use crate::presentation::dto::{CreatePaymentTermLineDto, UpdatePaymentTermLineDto};

/// Application service for PaymentTermLine entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `payment_term_line_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PaymentTermLineServiceCustom {
///     inner: Arc<PaymentTermLineService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PaymentTermLineService = GenericCrudService<
    PaymentTermLine,
    CreatePaymentTermLineDto,
    UpdatePaymentTermLineDto,
    PaymentTermLineRepository,
>;

// <<< CUSTOM
// END CUSTOM
