//! Application service for ProviderBankAccount entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `provider_bank_account_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateProviderBankAccountDto, UpdateProviderBankAccountDto};
use crate::domain::entity::ProviderBankAccount;
use crate::infrastructure::persistence::ProviderBankAccountRepository;

/// Application service for ProviderBankAccount entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `provider_bank_account_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ProviderBankAccountServiceCustom {
///     inner: Arc<ProviderBankAccountService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ProviderBankAccountService = GenericCrudService<
    ProviderBankAccount,
    CreateProviderBankAccountDto,
    UpdateProviderBankAccountDto,
    ProviderBankAccountRepository,
>;

// <<< CUSTOM
// END CUSTOM
