//! Application service for PurchaseInvoiceLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `purchase_invoice_line_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::domain::entity::PurchaseInvoiceLine;
use crate::infrastructure::persistence::PurchaseInvoiceLineRepository;
use crate::presentation::dto::{CreatePurchaseInvoiceLineDto, UpdatePurchaseInvoiceLineDto};

/// Application service for PurchaseInvoiceLine entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `purchase_invoice_line_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PurchaseInvoiceLineServiceCustom {
///     inner: Arc<PurchaseInvoiceLineService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PurchaseInvoiceLineService = GenericCrudService<
    PurchaseInvoiceLine,
    CreatePurchaseInvoiceLineDto,
    UpdatePurchaseInvoiceLineDto,
    PurchaseInvoiceLineRepository,
>;

// <<< CUSTOM
// END CUSTOM
