//! Application service for SalesInvoiceLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `sales_invoice_line_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSalesInvoiceLineDto, UpdateSalesInvoiceLineDto};
use crate::domain::entity::SalesInvoiceLine;
use crate::infrastructure::persistence::SalesInvoiceLineRepository;

/// Application service for SalesInvoiceLine entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `sales_invoice_line_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SalesInvoiceLineServiceCustom {
///     inner: Arc<SalesInvoiceLineService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SalesInvoiceLineService = GenericCrudService<
    SalesInvoiceLine,
    CreateSalesInvoiceLineDto,
    UpdateSalesInvoiceLineDto,
    SalesInvoiceLineRepository,
>;

// <<< CUSTOM
// END CUSTOM
