-- AgentEarning Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the agent_earnings table.
-- Customize this file to add your initial data.

-- INSERT INTO agent_earnings (
--     id,
--     agent_id,
--     task_id,
--     order_id,
--     earning_type,
--     description,
--     currency,
--     base_amount,
--     distance_km,
--     distance_bonus,
--     time_bonus,
--     surge_bonus,
--     incentive_bonus,
--     tip_amount,
--     deduction_amount,
--     deduction_reason,
--     total_earning,
--     status,
--     earned_at,
--     earning_date,
--     is_paid,
--     payout_id,
--     paid_at,
--     cod_collected,
--     cod_deposited,
--     cod_deposited_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO agent_earnings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

