-- PaymentSchedule Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the billing.payment_schedules table.
-- Customize this file to add your initial data.

-- INSERT INTO billing.payment_schedules (
--     id,
--     invoice_ref,
--     invoice_kind,
--     company_id,
--     installment_no,
--     due_date,
--     amount,
--     paid_amount,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO billing.payment_schedules (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

