-- PaymentTermLine Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the billing.payment_term_lines table.
-- Customize this file to add your initial data.

-- INSERT INTO billing.payment_term_lines (
--     id,
--     term_id,
--     company_id,
--     value,
--     value_amount,
--     nb_days,
--     day_of_month,
--     delay_type,
--     anchor,
--     sequence,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO billing.payment_term_lines (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

