-- Migration: Create agent_earnings table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS agent_earnings (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    agent_id UUID NOT NULL,
    task_id UUID,
    order_id UUID,
    earning_type earning_type NOT NULL,
    description TEXT,
    currency TEXT NOT NULL DEFAULT 'IDR',
    base_amount NUMERIC NOT NULL,
    distance_km NUMERIC,
    distance_bonus NUMERIC NOT NULL DEFAULT 0,
    time_bonus NUMERIC NOT NULL DEFAULT 0,
    surge_bonus NUMERIC NOT NULL DEFAULT 0,
    incentive_bonus NUMERIC NOT NULL DEFAULT 0,
    tip_amount NUMERIC NOT NULL DEFAULT 0,
    deduction_amount NUMERIC NOT NULL DEFAULT 0,
    deduction_reason TEXT,
    total_earning NUMERIC NOT NULL,
    status earning_status NOT NULL DEFAULT 'pending',
    earned_at TIMESTAMPTZ NOT NULL,
    earning_date DATE NOT NULL,
    is_paid BOOLEAN NOT NULL DEFAULT FALSE,
    payout_id UUID,
    paid_at TIMESTAMPTZ,
    cod_collected NUMERIC NOT NULL DEFAULT 0,
    cod_deposited BOOLEAN NOT NULL DEFAULT FALSE,
    cod_deposited_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_agent_earnings_agent_id_earning_date ON agent_earnings (agent_id, earning_date);

CREATE INDEX IF NOT EXISTS idx_agent_earnings_agent_id_status_is_paid ON agent_earnings (agent_id, status, is_paid);

CREATE INDEX IF NOT EXISTS idx_agent_earnings_task_id ON agent_earnings (task_id);

CREATE INDEX IF NOT EXISTS idx_agent_earnings_order_id ON agent_earnings (order_id);

CREATE INDEX IF NOT EXISTS idx_agent_earnings_earning_type_earned_at ON agent_earnings (earning_type, earned_at);

CREATE INDEX IF NOT EXISTS idx_agent_earnings_cod_collected_cod_deposited ON agent_earnings (cod_collected, cod_deposited) WHERE cod_collected > 0;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_agent_earnings_metadata_gin ON agent_earnings USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_agent_earnings_metadata_deleted_at ON agent_earnings ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION agent_earnings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS agent_earnings_insert_audit ON agent_earnings;
CREATE TRIGGER agent_earnings_insert_audit BEFORE INSERT ON agent_earnings
    FOR EACH ROW EXECUTE FUNCTION agent_earnings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS agent_earnings_update_audit ON agent_earnings;
CREATE TRIGGER agent_earnings_update_audit BEFORE UPDATE ON agent_earnings
    FOR EACH ROW EXECUTE FUNCTION agent_earnings_audit_timestamp();

