-- Migration: Create invoice_line_items table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS invoice_line_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    invoice_id UUID NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    description TEXT NOT NULL,
    quantity NUMERIC NOT NULL,
    unit_price NUMERIC NOT NULL,
    amount NUMERIC NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_invoice_line_items_invoice_id_sort_order ON invoice_line_items (invoice_id, sort_order);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_invoice_line_items_metadata_gin ON invoice_line_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_invoice_line_items_metadata_deleted_at ON invoice_line_items ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION invoice_line_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS invoice_line_items_insert_audit ON invoice_line_items;
CREATE TRIGGER invoice_line_items_insert_audit BEFORE INSERT ON invoice_line_items
    FOR EACH ROW EXECUTE FUNCTION invoice_line_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS invoice_line_items_update_audit ON invoice_line_items;
CREATE TRIGGER invoice_line_items_update_audit BEFORE UPDATE ON invoice_line_items
    FOR EACH ROW EXECUTE FUNCTION invoice_line_items_audit_timestamp();

