-- Migration: Create refund_requests table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS refund_requests (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    refund_number TEXT NOT NULL,
    payment_id UUID NOT NULL,
    order_id UUID,
    requester_type TEXT NOT NULL,
    requester_id UUID NOT NULL,
    requester_name TEXT,
    currency TEXT NOT NULL DEFAULT 'IDR',
    original_amount NUMERIC NOT NULL,
    requested_amount NUMERIC NOT NULL,
    approved_amount NUMERIC,
    refunded_amount NUMERIC NOT NULL DEFAULT 0,
    reason refund_reason NOT NULL DEFAULT 'customer_request',
    reason_detail TEXT,
    evidence_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
    status refund_status NOT NULL DEFAULT 'pending',
    reviewed_by UUID,
    reviewed_at TIMESTAMPTZ,
    review_notes TEXT,
    approved_by UUID,
    approved_at TIMESTAMPTZ,
    approval_notes TEXT,
    rejected_by UUID,
    rejected_at TIMESTAMPTZ,
    rejection_reason TEXT,
    processing_started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    failure_reason TEXT,
    gateway_refund_id TEXT,
    gateway_status TEXT,
    refund_method refund_method,
    bank_name TEXT,
    account_number TEXT,
    account_name TEXT,
    customer_notified BOOLEAN NOT NULL DEFAULT FALSE,
    customer_notified_at TIMESTAMPTZ,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_refund_requests_refund_number ON refund_requests (refund_number) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_refund_requests_payment_id ON refund_requests (payment_id);

CREATE INDEX IF NOT EXISTS idx_refund_requests_order_id ON refund_requests (order_id);

CREATE INDEX IF NOT EXISTS idx_refund_requests_requester_type_requester_id ON refund_requests (requester_type, requester_id);

CREATE INDEX IF NOT EXISTS idx_refund_requests_status_created_at ON refund_requests (status, ((metadata->>'created_at')));

CREATE INDEX IF NOT EXISTS idx_refund_requests_reason ON refund_requests (reason);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_refund_requests_metadata_gin ON refund_requests USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_refund_requests_metadata_deleted_at ON refund_requests ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION refund_requests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS refund_requests_insert_audit ON refund_requests;
CREATE TRIGGER refund_requests_insert_audit BEFORE INSERT ON refund_requests
    FOR EACH ROW EXECUTE FUNCTION refund_requests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS refund_requests_update_audit ON refund_requests;
CREATE TRIGGER refund_requests_update_audit BEFORE UPDATE ON refund_requests
    FOR EACH ROW EXECUTE FUNCTION refund_requests_audit_timestamp();

