-- Migration: Create purchase_invoices table
-- Generated by metaphor-schema

-- Create invoice_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invoice_status') THEN
        CREATE TYPE invoice_status AS ENUM ('draft', 'submitted', 'partially_paid', 'paid', 'cancelled');
    END IF;
END
$$;

-- Create gl_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gl_posting_state') THEN
        CREATE TYPE gl_posting_state AS ENUM ('pending', 'posted', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE IF NOT EXISTS billing.purchase_invoices (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    invoice_number TEXT NOT NULL,
    company_id UUID NOT NULL,
    branch_id UUID,
    supplier_id UUID NOT NULL,
    source_po_id UUID,
    status invoice_status NOT NULL DEFAULT 'draft',
    posting_date DATE NOT NULL,
    due_date DATE,
    currency TEXT NOT NULL DEFAULT 'IDR',
    net_total NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (net_total >= 0),
    tax_total NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    withholding_total NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (withholding_total >= 0),
    grand_total NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (grand_total >= 0),
    outstanding_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (outstanding_amount >= 0),
    payable_account_id UUID NOT NULL,
    posting_state gl_posting_state NOT NULL DEFAULT 'pending',
    journal_id UUID,
    accounting_post_id UUID,
    posted_at TIMESTAMPTZ,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_invoices_invoice_number ON billing.purchase_invoices (invoice_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_purchase_invoices_company_id_supplier_id_status ON billing.purchase_invoices (company_id, supplier_id, status);

CREATE INDEX IF NOT EXISTS idx_purchase_invoices_posting_state ON billing.purchase_invoices (posting_state);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_metadata_gin ON billing.purchase_invoices USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_metadata_deleted_at ON billing.purchase_invoices ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_metadata_created_at ON billing.purchase_invoices ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_purchase_invoices_metadata_updated_at ON billing.purchase_invoices ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION billing.purchase_invoices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS purchase_invoices_insert_audit ON billing.purchase_invoices;
CREATE TRIGGER purchase_invoices_insert_audit BEFORE INSERT ON billing.purchase_invoices
    FOR EACH ROW EXECUTE FUNCTION billing.purchase_invoices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS purchase_invoices_update_audit ON billing.purchase_invoices;
CREATE TRIGGER purchase_invoices_update_audit BEFORE UPDATE ON billing.purchase_invoices
    FOR EACH ROW EXECUTE FUNCTION billing.purchase_invoices_audit_timestamp();
