-- Migration: Create payment_term_lines table
-- Generated by metaphor-schema

-- Create payment_term_line_value enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_term_line_value') THEN
        CREATE TYPE payment_term_line_value AS ENUM ('balance', 'percent', 'fixed');
    END IF;
END
$$;

-- Create payment_term_delay_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_term_delay_type') THEN
        CREATE TYPE payment_term_delay_type AS ENUM ('days', 'day_following_month', 'day_current_month');
    END IF;
END
$$;

-- Create payment_term_anchor enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_term_anchor') THEN
        CREATE TYPE payment_term_anchor AS ENUM ('invoice_date', 'end_of_invoice_month');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE IF NOT EXISTS billing.payment_term_lines (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    term_id UUID NOT NULL,
    company_id UUID,
    value payment_term_line_value NOT NULL DEFAULT 'balance',
    value_amount NUMERIC(18, 4) NOT NULL DEFAULT 0 CHECK (value_amount >= 0),
    nb_days INTEGER NOT NULL,
    day_of_month INTEGER,
    delay_type payment_term_delay_type NOT NULL DEFAULT 'days',
    anchor payment_term_anchor NOT NULL DEFAULT 'invoice_date',
    sequence INTEGER NOT NULL DEFAULT 10,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_payment_term_lines_term_id_sequence ON billing.payment_term_lines (term_id, sequence);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_payment_term_lines_metadata_gin ON billing.payment_term_lines USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_payment_term_lines_metadata_deleted_at ON billing.payment_term_lines ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_payment_term_lines_metadata_created_at ON billing.payment_term_lines ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_payment_term_lines_metadata_updated_at ON billing.payment_term_lines ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION billing.payment_term_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payment_term_lines_insert_audit ON billing.payment_term_lines;
CREATE TRIGGER payment_term_lines_insert_audit BEFORE INSERT ON billing.payment_term_lines
    FOR EACH ROW EXECUTE FUNCTION billing.payment_term_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payment_term_lines_update_audit ON billing.payment_term_lines;
CREATE TRIGGER payment_term_lines_update_audit BEFORE UPDATE ON billing.payment_term_lines
    FOR EACH ROW EXECUTE FUNCTION billing.payment_term_lines_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE billing.payment_term_lines ADD CONSTRAINT fk_payment_term_lines_term_id FOREIGN KEY (term_id) REFERENCES billing.payment_terms (id);
