-- Migration: Create invoice_tax_lines table
-- Generated by metaphor-schema

-- Create invoice_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invoice_kind') THEN
        CREATE TYPE invoice_kind AS ENUM ('sales', 'purchase');
    END IF;
END
$$;

-- Create tax_basis enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tax_basis') THEN
        CREATE TYPE tax_basis AS ENUM ('output', 'input', 'withholding');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE IF NOT EXISTS billing.invoice_tax_lines (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    invoice_ref UUID NOT NULL,
    invoice_kind invoice_kind NOT NULL,
    account_id UUID NOT NULL,
    basis tax_basis NOT NULL,
    description TEXT,
    taxable_base NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (taxable_base >= 0),
    rate NUMERIC(9, 4) NOT NULL DEFAULT 0 CHECK (rate >= 0),
    tax_amount NUMERIC(18, 2) NOT NULL CHECK (tax_amount >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_invoice_tax_lines_invoice_ref_invoice_kind ON billing.invoice_tax_lines (invoice_ref, invoice_kind);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_invoice_tax_lines_metadata_gin ON billing.invoice_tax_lines USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_invoice_tax_lines_metadata_deleted_at ON billing.invoice_tax_lines ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_invoice_tax_lines_metadata_created_at ON billing.invoice_tax_lines ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_invoice_tax_lines_metadata_updated_at ON billing.invoice_tax_lines ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION billing.invoice_tax_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS invoice_tax_lines_insert_audit ON billing.invoice_tax_lines;
CREATE TRIGGER invoice_tax_lines_insert_audit BEFORE INSERT ON billing.invoice_tax_lines
    FOR EACH ROW EXECUTE FUNCTION billing.invoice_tax_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS invoice_tax_lines_update_audit ON billing.invoice_tax_lines;
CREATE TRIGGER invoice_tax_lines_update_audit BEFORE UPDATE ON billing.invoice_tax_lines
    FOR EACH ROW EXECUTE FUNCTION billing.invoice_tax_lines_audit_timestamp();
