-- Migration: Create payment_schedules table
-- Generated by metaphor-schema

-- Create invoice_kind enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invoice_kind') THEN
        CREATE TYPE invoice_kind AS ENUM ('sales', 'purchase');
    END IF;
END
$$;

-- Create payment_schedule_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_schedule_status') THEN
        CREATE TYPE payment_schedule_status AS ENUM ('unpaid', 'partially_paid', 'paid', 'overdue');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE IF NOT EXISTS billing.payment_schedules (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    invoice_ref UUID NOT NULL,
    invoice_kind invoice_kind NOT NULL,
    company_id UUID NOT NULL,
    installment_no INTEGER NOT NULL,
    due_date DATE NOT NULL,
    amount NUMERIC NOT NULL,
    paid_amount NUMERIC NOT NULL DEFAULT 0,
    status payment_schedule_status NOT NULL DEFAULT 'unpaid',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_payment_schedules_invoice_ref_invoice_kind ON billing.payment_schedules (invoice_ref, invoice_kind);

CREATE INDEX IF NOT EXISTS idx_payment_schedules_company_id_due_date_status ON billing.payment_schedules (company_id, due_date, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_payment_schedules_metadata_gin ON billing.payment_schedules USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_payment_schedules_metadata_deleted_at ON billing.payment_schedules ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_payment_schedules_metadata_created_at ON billing.payment_schedules ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_payment_schedules_metadata_updated_at ON billing.payment_schedules ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION billing.payment_schedules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS payment_schedules_insert_audit ON billing.payment_schedules;
CREATE TRIGGER payment_schedules_insert_audit BEFORE INSERT ON billing.payment_schedules
    FOR EACH ROW EXECUTE FUNCTION billing.payment_schedules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS payment_schedules_update_audit ON billing.payment_schedules;
CREATE TRIGGER payment_schedules_update_audit BEFORE UPDATE ON billing.payment_schedules
    FOR EACH ROW EXECUTE FUNCTION billing.payment_schedules_audit_timestamp();
