//! Event handler trait for AgentEarning events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AgentEarningEvent;

/// Event handler for AgentEarning events.
/// Implement this trait to react to AgentEarning lifecycle events.
pub trait AgentEarningEventHandler: EventHandler<AgentEarningEvent> {}
