//! Domain events for FinancialPeriod entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::FinancialPeriod;

/// Domain events for FinancialPeriod — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<FinancialPeriod>)` variant.
pub type FinancialPeriodEvent = CrudEvent<FinancialPeriod>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for FinancialPeriod events.
pub type FinancialPeriodEventPublisher = Arc<dyn CrudEventPublisher<FinancialPeriod> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopFinancialPeriodEventPublisher = NoOpCrudEventPublisher<FinancialPeriod>;
