//! Domain events for Invoice entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Invoice;

/// Domain events for Invoice — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Invoice>)` variant.
pub type InvoiceEvent = CrudEvent<Invoice>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Invoice events.
pub type InvoiceEventPublisher = Arc<dyn CrudEventPublisher<Invoice> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopInvoiceEventPublisher = NoOpCrudEventPublisher<Invoice>;
