//! Event handler trait for InvoiceParty events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::InvoicePartyEvent;

/// Event handler for InvoiceParty events.
/// Implement this trait to react to InvoiceParty lifecycle events.
pub trait InvoicePartyEventHandler: EventHandler<InvoicePartyEvent> {}
