//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod invoice_tax_line_event_handlers;
pub mod invoice_tax_line_events;
pub mod payment_schedule_event_handlers;
pub mod payment_schedule_events;
pub mod payment_term_event_handlers;
pub mod payment_term_events;
pub mod payment_term_line_event_handlers;
pub mod payment_term_line_events;
pub mod purchase_invoice_event_handlers;
pub mod purchase_invoice_events;
pub mod purchase_invoice_line_event_handlers;
pub mod purchase_invoice_line_events;
pub mod sales_invoice_event_handlers;
pub mod sales_invoice_events;
pub mod sales_invoice_line_event_handlers;
pub mod sales_invoice_line_events;

pub use invoice_tax_line_event_handlers::InvoiceTaxLineEventHandler;
pub use invoice_tax_line_events::{
    InvoiceTaxLineEvent, InvoiceTaxLineEventPublisher, NoopInvoiceTaxLineEventPublisher,
};
pub use payment_schedule_event_handlers::PaymentScheduleEventHandler;
pub use payment_schedule_events::{
    NoopPaymentScheduleEventPublisher, PaymentScheduleEvent, PaymentScheduleEventPublisher,
};
pub use payment_term_event_handlers::PaymentTermEventHandler;
pub use payment_term_events::{
    NoopPaymentTermEventPublisher, PaymentTermEvent, PaymentTermEventPublisher,
};
pub use payment_term_line_event_handlers::PaymentTermLineEventHandler;
pub use payment_term_line_events::{
    NoopPaymentTermLineEventPublisher, PaymentTermLineEvent, PaymentTermLineEventPublisher,
};
pub use purchase_invoice_event_handlers::PurchaseInvoiceEventHandler;
pub use purchase_invoice_events::{
    NoopPurchaseInvoiceEventPublisher, PurchaseInvoiceEvent, PurchaseInvoiceEventPublisher,
};
pub use purchase_invoice_line_event_handlers::PurchaseInvoiceLineEventHandler;
pub use purchase_invoice_line_events::{
    NoopPurchaseInvoiceLineEventPublisher, PurchaseInvoiceLineEvent,
    PurchaseInvoiceLineEventPublisher,
};
pub use sales_invoice_event_handlers::SalesInvoiceEventHandler;
pub use sales_invoice_events::{
    NoopSalesInvoiceEventPublisher, SalesInvoiceEvent, SalesInvoiceEventPublisher,
};
pub use sales_invoice_line_event_handlers::SalesInvoiceLineEventHandler;
pub use sales_invoice_line_events::{
    NoopSalesInvoiceLineEventPublisher, SalesInvoiceLineEvent, SalesInvoiceLineEventPublisher,
};

// <<< CUSTOM
// END CUSTOM
