//! Domain events for PaymentTerm entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::PaymentTerm;
use backbone_messaging::CrudEvent;

/// Domain events for PaymentTerm — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PaymentTerm>)` variant.
pub type PaymentTermEvent = CrudEvent<PaymentTerm>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PaymentTerm events.
pub type PaymentTermEventPublisher = Arc<dyn CrudEventPublisher<PaymentTerm> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPaymentTermEventPublisher = NoOpCrudEventPublisher<PaymentTerm>;
