//! Domain events for PaymentFee entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PaymentFee;

/// Domain events for PaymentFee — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PaymentFee>)` variant.
pub type PaymentFeeEvent = CrudEvent<PaymentFee>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PaymentFee events.
pub type PaymentFeeEventPublisher = Arc<dyn CrudEventPublisher<PaymentFee> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPaymentFeeEventPublisher = NoOpCrudEventPublisher<PaymentFee>;
