//! Event handler trait for PaymentTermLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::PaymentTermLineEvent;
use backbone_messaging::EventHandler;

/// Event handler for PaymentTermLine events.
/// Implement this trait to react to PaymentTermLine lifecycle events.
pub trait PaymentTermLineEventHandler: EventHandler<PaymentTermLineEvent> {}
