//! Event handler trait for PaymentTerm events
//!
//! Generated by metaphor-schema. Do not edit manually.

use super::PaymentTermEvent;
use backbone_messaging::EventHandler;

/// Event handler for PaymentTerm events.
/// Implement this trait to react to PaymentTerm lifecycle events.
pub trait PaymentTermEventHandler: EventHandler<PaymentTermEvent> {}
