//! Domain events for PaymentSchedule entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::PaymentSchedule;
use backbone_messaging::CrudEvent;

/// Domain events for PaymentSchedule — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PaymentSchedule>)` variant.
pub type PaymentScheduleEvent = CrudEvent<PaymentSchedule>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PaymentSchedule events.
pub type PaymentScheduleEventPublisher = Arc<dyn CrudEventPublisher<PaymentSchedule> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPaymentScheduleEventPublisher = NoOpCrudEventPublisher<PaymentSchedule>;
