//! Event handler trait for PaymentTerm events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PaymentTermEvent;

/// Event handler for PaymentTerm events.
/// Implement this trait to react to PaymentTerm lifecycle events.
pub trait PaymentTermEventHandler: EventHandler<PaymentTermEvent> {}
