//! Event handler trait for PaymentTermLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PaymentTermLineEvent;

/// Event handler for PaymentTermLine events.
/// Implement this trait to react to PaymentTermLine lifecycle events.
pub trait PaymentTermLineEventHandler: EventHandler<PaymentTermLineEvent> {}
