//! Domain events for PurchaseInvoiceLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use crate::domain::entity::PurchaseInvoiceLine;
use backbone_messaging::CrudEvent;

/// Domain events for PurchaseInvoiceLine — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PurchaseInvoiceLine>)` variant.
pub type PurchaseInvoiceLineEvent = CrudEvent<PurchaseInvoiceLine>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PurchaseInvoiceLine events.
pub type PurchaseInvoiceLineEventPublisher =
    Arc<dyn CrudEventPublisher<PurchaseInvoiceLine> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPurchaseInvoiceLineEventPublisher = NoOpCrudEventPublisher<PurchaseInvoiceLine>;
