//! Event handler trait for PurchaseInvoiceLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PurchaseInvoiceLineEvent;

/// Event handler for PurchaseInvoiceLine events.
/// Implement this trait to react to PurchaseInvoiceLine lifecycle events.
pub trait PurchaseInvoiceLineEventHandler: EventHandler<PurchaseInvoiceLineEvent> {}
