//! Domain events for PurchaseInvoice entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PurchaseInvoice;

/// Domain events for PurchaseInvoice — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PurchaseInvoice>)` variant.
pub type PurchaseInvoiceEvent = CrudEvent<PurchaseInvoice>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PurchaseInvoice events.
pub type PurchaseInvoiceEventPublisher = Arc<dyn CrudEventPublisher<PurchaseInvoice> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPurchaseInvoiceEventPublisher = NoOpCrudEventPublisher<PurchaseInvoice>;
