//! Event handler trait for PurchaseInvoice events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PurchaseInvoiceEvent;

/// Event handler for PurchaseInvoice events.
/// Implement this trait to react to PurchaseInvoice lifecycle events.
pub trait PurchaseInvoiceEventHandler: EventHandler<PurchaseInvoiceEvent> {}
