//! Domain events for RefundRequest entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RefundRequest;

/// Domain events for RefundRequest — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RefundRequest>)` variant.
pub type RefundRequestEvent = CrudEvent<RefundRequest>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RefundRequest events.
pub type RefundRequestEventPublisher = Arc<dyn CrudEventPublisher<RefundRequest> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRefundRequestEventPublisher = NoOpCrudEventPublisher<RefundRequest>;
