//! Event subscriber type aliases for Billing module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::InvoiceTaxLineEvent;
use crate::domain::event::PaymentScheduleEvent;
use crate::domain::event::PurchaseInvoiceEvent;
use crate::domain::event::PurchaseInvoiceLineEvent;
use crate::domain::event::SalesInvoiceEvent;
use crate::domain::event::SalesInvoiceLineEvent;

/// Subscriber for InvoiceTaxLine events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type InvoiceTaxLineEventSubscriber = GenericEventSubscriber<InvoiceTaxLineEvent>;

/// Subscriber for PaymentSchedule events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PaymentScheduleEventSubscriber = GenericEventSubscriber<PaymentScheduleEvent>;

/// Subscriber for PurchaseInvoice events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PurchaseInvoiceEventSubscriber = GenericEventSubscriber<PurchaseInvoiceEvent>;

/// Subscriber for PurchaseInvoiceLine events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PurchaseInvoiceLineEventSubscriber = GenericEventSubscriber<PurchaseInvoiceLineEvent>;

/// Subscriber for SalesInvoice events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SalesInvoiceEventSubscriber = GenericEventSubscriber<SalesInvoiceEvent>;

/// Subscriber for SalesInvoiceLine events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SalesInvoiceLineEventSubscriber = GenericEventSubscriber<SalesInvoiceLineEvent>;

// <<< CUSTOM
// END CUSTOM
