//! Event subscriber type aliases for Billing module
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::AgentEarningEvent;
use crate::domain::event::FinancialPeriodEvent;
use crate::domain::event::PaymentEvent;
use crate::domain::event::PaymentGatewayDetailEvent;
use crate::domain::event::PaymentFeeEvent;
use crate::domain::event::InvoiceEvent;
use crate::domain::event::InvoicePartyEvent;
use crate::domain::event::InvoiceLineItemEvent;
use crate::domain::event::ProviderBankAccountEvent;
use crate::domain::event::RefundRequestEvent;
use crate::domain::event::SettlementEvent;

/// Subscriber for AgentEarning events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type AgentEarningEventSubscriber = GenericEventSubscriber<AgentEarningEvent>;

/// Subscriber for FinancialPeriod events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type FinancialPeriodEventSubscriber = GenericEventSubscriber<FinancialPeriodEvent>;

/// Subscriber for Payment events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PaymentEventSubscriber = GenericEventSubscriber<PaymentEvent>;

/// Subscriber for PaymentGatewayDetail events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PaymentGatewayDetailEventSubscriber = GenericEventSubscriber<PaymentGatewayDetailEvent>;

/// Subscriber for PaymentFee events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PaymentFeeEventSubscriber = GenericEventSubscriber<PaymentFeeEvent>;

/// Subscriber for Invoice events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type InvoiceEventSubscriber = GenericEventSubscriber<InvoiceEvent>;

/// Subscriber for InvoiceParty events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type InvoicePartyEventSubscriber = GenericEventSubscriber<InvoicePartyEvent>;

/// Subscriber for InvoiceLineItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type InvoiceLineItemEventSubscriber = GenericEventSubscriber<InvoiceLineItemEvent>;

/// Subscriber for ProviderBankAccount events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type ProviderBankAccountEventSubscriber = GenericEventSubscriber<ProviderBankAccountEvent>;

/// Subscriber for RefundRequest events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type RefundRequestEventSubscriber = GenericEventSubscriber<RefundRequestEvent>;

/// Subscriber for Settlement events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SettlementEventSubscriber = GenericEventSubscriber<SettlementEvent>;

// <<< CUSTOM
// END CUSTOM
