//! InvoiceTaxLine seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial InvoiceTaxLine data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// INVOICETAXLINE SEEDER
// ============================================================================

/// Seeder for invoice_tax_line
pub struct SeedInvoiceTaxLineSeeder;

impl SeedInvoiceTaxLineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedInvoiceTaxLineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedInvoiceTaxLineSeeder {
    fn name(&self) -> &'static str {
        "SeedInvoiceTaxLineSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if billing.invoice_tax_lines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM billing.invoice_tax_lines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/invoice_tax_line_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM billing.invoice_tax_lines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

