//! PaymentTerm seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PaymentTerm data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PAYMENTTERM SEEDER
// ============================================================================

/// Seeder for payment_term
pub struct SeedPaymentTermSeeder;

impl SeedPaymentTermSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPaymentTermSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPaymentTermSeeder {
    fn name(&self) -> &'static str {
        "SeedPaymentTermSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if billing.payment_terms table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM billing.payment_terms")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/payment_term_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM billing.payment_terms")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
