//! PurchaseInvoice seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PurchaseInvoice data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// PURCHASEINVOICE SEEDER
// ============================================================================

/// Seeder for purchase_invoice
pub struct SeedPurchaseInvoiceSeeder;

impl SeedPurchaseInvoiceSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPurchaseInvoiceSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPurchaseInvoiceSeeder {
    fn name(&self) -> &'static str {
        "SeedPurchaseInvoiceSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if billing.purchase_invoices table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM billing.purchase_invoices")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/purchase_invoice_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM billing.purchase_invoices")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

