//! SalesInvoiceLine seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SalesInvoiceLine data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SALESINVOICELINE SEEDER
// ============================================================================

/// Seeder for sales_invoice_line
pub struct SeedSalesInvoiceLineSeeder;

impl SeedSalesInvoiceLineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSalesInvoiceLineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSalesInvoiceLineSeeder {
    fn name(&self) -> &'static str {
        "SeedSalesInvoiceLineSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if billing.sales_invoice_lines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM billing.sales_invoice_lines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/sales_invoice_line_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM billing.sales_invoice_lines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
