//! Repository trait for FinancialPeriod aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the FinancialPeriod aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{FinancialPeriod, FinancialPeriodStatus, FinancialPeriodType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct FinancialPeriodPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl FinancialPeriodPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct FinancialPeriodPaginatedResult {
    pub data: Vec<FinancialPeriod>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct FinancialPeriodFilter {
    pub provider_id: Option<Uuid>,
    pub period_type: Option<FinancialPeriodType>,
    pub pnl_report_url: Option<String>,
    pub status: Option<FinancialPeriodStatus>,
    pub closed_by: Option<Uuid>,
    pub currency: Option<String>,
    pub notes: Option<String>,
}

impl FinancialPeriodFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.provider_id.is_some() || self.period_type.is_some() || self.pnl_report_url.is_some() || self.status.is_some() || self.closed_by.is_some() || self.currency.is_some() || self.notes.is_some()
    }
}

/// Repository trait for FinancialPeriod aggregate
///
/// This trait defines the persistence contract for FinancialPeriod entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait FinancialPeriodRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new financial_period entity
    async fn save(&self, entity: &FinancialPeriod) -> Result<FinancialPeriod>;

    /// Find financial_period by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<FinancialPeriod>>;

    /// Find all financial_period entities
    async fn find_all(&self) -> Result<Vec<FinancialPeriod>>;

    /// Update financial_period by ID
    async fn update(&self, id: &str, entity: &FinancialPeriod) -> Result<Option<FinancialPeriod>>;

    /// Delete financial_period by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List financial_period with pagination
    async fn list(&self, params: FinancialPeriodPaginationParams) -> Result<FinancialPeriodPaginatedResult>;

    /// List financial_period with pagination and filters
    async fn list_with_filters(&self, params: FinancialPeriodPaginationParams, filters: FinancialPeriodFilter) -> Result<FinancialPeriodPaginatedResult>;

    /// Count all financial_period entities
    async fn count(&self) -> Result<u64>;

    /// Count financial_period entities matching filters
    async fn count_with_filters(&self, filters: FinancialPeriodFilter) -> Result<u64>;

    /// Check if financial_period exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete financial_period by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted financial_period by ID
    async fn restore(&self, id: &str) -> Result<Option<FinancialPeriod>>;

    /// List soft-deleted financial_period entities
    async fn list_deleted(&self, params: FinancialPeriodPaginationParams) -> Result<FinancialPeriodPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save financial_period entities
    async fn bulk_save(&self, entities: &[FinancialPeriod]) -> Result<Vec<FinancialPeriod>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
