//! Repository trait for Invoice aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Invoice aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Invoice, InvoiceStatus, InvoiceType, InvoiceableType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct InvoicePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl InvoicePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct InvoicePaginatedResult {
    pub data: Vec<Invoice>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct InvoiceFilter {
    pub invoice_number: Option<String>,
    pub invoice_type: Option<InvoiceType>,
    pub invoiceable_type: Option<InvoiceableType>,
    pub invoiceable_id: Option<Uuid>,
    pub order_id: Option<Uuid>,
    pub settlement_id: Option<Uuid>,
    pub currency: Option<String>,
    pub status: Option<InvoiceStatus>,
    pub sent_via: Option<String>,
    pub payment_id: Option<Uuid>,
    pub pdf_url: Option<String>,
    pub notes: Option<String>,
    pub terms: Option<String>,
    pub footer: Option<String>,
}

impl InvoiceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.invoice_number.is_some() || self.invoice_type.is_some() || self.invoiceable_type.is_some() || self.invoiceable_id.is_some() || self.order_id.is_some() || self.settlement_id.is_some() || self.currency.is_some() || self.status.is_some() || self.sent_via.is_some() || self.payment_id.is_some() || self.pdf_url.is_some() || self.notes.is_some() || self.terms.is_some() || self.footer.is_some()
    }
}

/// Repository trait for Invoice aggregate
///
/// This trait defines the persistence contract for Invoice entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait InvoiceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new invoice entity
    async fn save(&self, entity: &Invoice) -> Result<Invoice>;

    /// Find invoice by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Invoice>>;

    /// Find all invoice entities
    async fn find_all(&self) -> Result<Vec<Invoice>>;

    /// Update invoice by ID
    async fn update(&self, id: &str, entity: &Invoice) -> Result<Option<Invoice>>;

    /// Delete invoice by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List invoice with pagination
    async fn list(&self, params: InvoicePaginationParams) -> Result<InvoicePaginatedResult>;

    /// List invoice with pagination and filters
    async fn list_with_filters(&self, params: InvoicePaginationParams, filters: InvoiceFilter) -> Result<InvoicePaginatedResult>;

    /// Count all invoice entities
    async fn count(&self) -> Result<u64>;

    /// Count invoice entities matching filters
    async fn count_with_filters(&self, filters: InvoiceFilter) -> Result<u64>;

    /// Check if invoice exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete invoice by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted invoice by ID
    async fn restore(&self, id: &str) -> Result<Option<Invoice>>;

    /// List soft-deleted invoice entities
    async fn list_deleted(&self, params: InvoicePaginationParams) -> Result<InvoicePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Query by Unique Fields
    // =========================================================================

    /// Find invoice by invoice_number
    async fn find_by_invoice_number(&self, invoice_number: &str) -> Result<Option<Invoice>>;

    // =========================================================================
    // Existence Checks by Unique Fields
    // =========================================================================

    /// Check if invoice exists by invoice_number
    async fn exists_by_invoice_number(&self, invoice_number: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save invoice entities
    async fn bulk_save(&self, entities: &[Invoice]) -> Result<Vec<Invoice>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
