//! Repository trait for InvoiceParty aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the InvoiceParty aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{InvoiceParty, InvoicePartyRole, InvoicePartyType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct InvoicePartyPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl InvoicePartyPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct InvoicePartyPaginatedResult {
    pub data: Vec<InvoiceParty>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct InvoicePartyFilter {
    pub invoice_id: Option<Uuid>,
    pub role: Option<InvoicePartyRole>,
    pub party_type: Option<InvoicePartyType>,
    pub party_id: Option<Uuid>,
    pub name: Option<String>,
    pub email: Option<String>,
    pub address: Option<String>,
    pub tax_id: Option<String>,
}

impl InvoicePartyFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.invoice_id.is_some() || self.role.is_some() || self.party_type.is_some() || self.party_id.is_some() || self.name.is_some() || self.email.is_some() || self.address.is_some() || self.tax_id.is_some()
    }
}

/// Repository trait for InvoiceParty aggregate
///
/// This trait defines the persistence contract for InvoiceParty entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait InvoicePartyRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new invoice_party entity
    async fn save(&self, entity: &InvoiceParty) -> Result<InvoiceParty>;

    /// Find invoice_party by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<InvoiceParty>>;

    /// Find all invoice_party entities
    async fn find_all(&self) -> Result<Vec<InvoiceParty>>;

    /// Update invoice_party by ID
    async fn update(&self, id: &str, entity: &InvoiceParty) -> Result<Option<InvoiceParty>>;

    /// Delete invoice_party by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List invoice_party with pagination
    async fn list(&self, params: InvoicePartyPaginationParams) -> Result<InvoicePartyPaginatedResult>;

    /// List invoice_party with pagination and filters
    async fn list_with_filters(&self, params: InvoicePartyPaginationParams, filters: InvoicePartyFilter) -> Result<InvoicePartyPaginatedResult>;

    /// Count all invoice_party entities
    async fn count(&self) -> Result<u64>;

    /// Count invoice_party entities matching filters
    async fn count_with_filters(&self, filters: InvoicePartyFilter) -> Result<u64>;

    /// Check if invoice_party exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete invoice_party by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted invoice_party by ID
    async fn restore(&self, id: &str) -> Result<Option<InvoiceParty>>;

    /// List soft-deleted invoice_party entities
    async fn list_deleted(&self, params: InvoicePartyPaginationParams) -> Result<InvoicePartyPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save invoice_party entities
    async fn bulk_save(&self, entities: &[InvoiceParty]) -> Result<Vec<InvoiceParty>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
