//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.

pub mod invoice_tax_line_repository;
pub mod payment_schedule_repository;
pub mod purchase_invoice_line_repository;
pub mod purchase_invoice_repository;
pub mod sales_invoice_line_repository;
pub mod sales_invoice_repository;

// Re-exports
pub use invoice_tax_line_repository::{
    InvoiceTaxLineFilter, InvoiceTaxLinePaginatedResult, InvoiceTaxLinePaginationParams,
    InvoiceTaxLineRepository,
};
pub use payment_schedule_repository::{
    PaymentScheduleFilter, PaymentSchedulePaginatedResult, PaymentSchedulePaginationParams,
    PaymentScheduleRepository,
};
pub use purchase_invoice_line_repository::{
    PurchaseInvoiceLineFilter, PurchaseInvoiceLinePaginatedResult,
    PurchaseInvoiceLinePaginationParams, PurchaseInvoiceLineRepository,
};
pub use purchase_invoice_repository::{
    PurchaseInvoiceFilter, PurchaseInvoicePaginatedResult, PurchaseInvoicePaginationParams,
    PurchaseInvoiceRepository,
};
pub use sales_invoice_line_repository::{
    SalesInvoiceLineFilter, SalesInvoiceLinePaginatedResult, SalesInvoiceLinePaginationParams,
    SalesInvoiceLineRepository,
};
pub use sales_invoice_repository::{
    SalesInvoiceFilter, SalesInvoicePaginatedResult, SalesInvoicePaginationParams,
    SalesInvoiceRepository,
};
