//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod invoice_tax_line_repository;
pub mod payment_schedule_repository;
pub mod purchase_invoice_repository;
pub mod purchase_invoice_line_repository;
pub mod sales_invoice_repository;
pub mod sales_invoice_line_repository;

// Re-exports
pub use invoice_tax_line_repository::{
    InvoiceTaxLineRepository,
    InvoiceTaxLinePaginationParams,
    InvoiceTaxLinePaginatedResult,
    InvoiceTaxLineFilter,
};
pub use payment_schedule_repository::{
    PaymentScheduleRepository,
    PaymentSchedulePaginationParams,
    PaymentSchedulePaginatedResult,
    PaymentScheduleFilter,
};
pub use purchase_invoice_repository::{
    PurchaseInvoiceRepository,
    PurchaseInvoicePaginationParams,
    PurchaseInvoicePaginatedResult,
    PurchaseInvoiceFilter,
};
pub use purchase_invoice_line_repository::{
    PurchaseInvoiceLineRepository,
    PurchaseInvoiceLinePaginationParams,
    PurchaseInvoiceLinePaginatedResult,
    PurchaseInvoiceLineFilter,
};
pub use sales_invoice_repository::{
    SalesInvoiceRepository,
    SalesInvoicePaginationParams,
    SalesInvoicePaginatedResult,
    SalesInvoiceFilter,
};
pub use sales_invoice_line_repository::{
    SalesInvoiceLineRepository,
    SalesInvoiceLinePaginationParams,
    SalesInvoiceLinePaginatedResult,
    SalesInvoiceLineFilter,
};
