//! Repository trait for PaymentGatewayDetail aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PaymentGatewayDetail aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PaymentGatewayDetail;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentGatewayDetailPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PaymentGatewayDetailPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PaymentGatewayDetailPaginatedResult {
    pub data: Vec<PaymentGatewayDetail>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentGatewayDetailFilter {
    pub payment_id: Option<Uuid>,
    pub external_id: Option<String>,
    pub invoice_url: Option<String>,
    pub checkout_url: Option<String>,
    pub qr_code_url: Option<String>,
    pub virtual_account_number: Option<String>,
    pub virtual_account_bank: Option<String>,
}

impl PaymentGatewayDetailFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.payment_id.is_some() || self.external_id.is_some() || self.invoice_url.is_some() || self.checkout_url.is_some() || self.qr_code_url.is_some() || self.virtual_account_number.is_some() || self.virtual_account_bank.is_some()
    }
}

/// Repository trait for PaymentGatewayDetail aggregate
///
/// This trait defines the persistence contract for PaymentGatewayDetail entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PaymentGatewayDetailRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new payment_gateway_detail entity
    async fn save(&self, entity: &PaymentGatewayDetail) -> Result<PaymentGatewayDetail>;

    /// Find payment_gateway_detail by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PaymentGatewayDetail>>;

    /// Find all payment_gateway_detail entities
    async fn find_all(&self) -> Result<Vec<PaymentGatewayDetail>>;

    /// Update payment_gateway_detail by ID
    async fn update(&self, id: &str, entity: &PaymentGatewayDetail) -> Result<Option<PaymentGatewayDetail>>;

    /// Delete payment_gateway_detail by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List payment_gateway_detail with pagination
    async fn list(&self, params: PaymentGatewayDetailPaginationParams) -> Result<PaymentGatewayDetailPaginatedResult>;

    /// List payment_gateway_detail with pagination and filters
    async fn list_with_filters(&self, params: PaymentGatewayDetailPaginationParams, filters: PaymentGatewayDetailFilter) -> Result<PaymentGatewayDetailPaginatedResult>;

    /// Count all payment_gateway_detail entities
    async fn count(&self) -> Result<u64>;

    /// Count payment_gateway_detail entities matching filters
    async fn count_with_filters(&self, filters: PaymentGatewayDetailFilter) -> Result<u64>;

    /// Check if payment_gateway_detail exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete payment_gateway_detail by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted payment_gateway_detail by ID
    async fn restore(&self, id: &str) -> Result<Option<PaymentGatewayDetail>>;

    /// List soft-deleted payment_gateway_detail entities
    async fn list_deleted(&self, params: PaymentGatewayDetailPaginationParams) -> Result<PaymentGatewayDetailPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Query by Unique Fields
    // =========================================================================

    /// Find payment_gateway_detail by payment_id
    async fn find_by_payment_id(&self, payment_id: Uuid) -> Result<Option<PaymentGatewayDetail>>;

    // =========================================================================
    // Existence Checks by Unique Fields
    // =========================================================================

    /// Check if payment_gateway_detail exists by payment_id
    async fn exists_by_payment_id(&self, payment_id: Uuid) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save payment_gateway_detail entities
    async fn bulk_save(&self, entities: &[PaymentGatewayDetail]) -> Result<Vec<PaymentGatewayDetail>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
