//! Repository trait for PaymentTerm aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PaymentTerm aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{DiscountTaxBasis, PaymentTerm, PaymentTermStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentTermPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PaymentTermPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PaymentTermPaginatedResult {
    pub data: Vec<PaymentTerm>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentTermFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub note: Option<String>,
    pub status: Option<PaymentTermStatus>,
    pub early_discount: Option<bool>,
    pub discount_account_id: Option<Uuid>,
    pub discount_tax_basis: Option<DiscountTaxBasis>,
}

impl PaymentTermFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some()
            || self.name.is_some()
            || self.note.is_some()
            || self.status.is_some()
            || self.early_discount.is_some()
            || self.discount_account_id.is_some()
            || self.discount_tax_basis.is_some()
    }
}

/// Repository trait for PaymentTerm aggregate
///
/// This trait defines the persistence contract for PaymentTerm entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PaymentTermRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new payment_term entity
    async fn save(&self, entity: &PaymentTerm) -> Result<PaymentTerm>;

    /// Find payment_term by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PaymentTerm>>;

    /// Find all payment_term entities
    async fn find_all(&self) -> Result<Vec<PaymentTerm>>;

    /// Update payment_term by ID
    async fn update(&self, id: &str, entity: &PaymentTerm) -> Result<Option<PaymentTerm>>;

    /// Delete payment_term by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List payment_term with pagination
    async fn list(&self, params: PaymentTermPaginationParams)
        -> Result<PaymentTermPaginatedResult>;

    /// List payment_term with pagination and filters
    async fn list_with_filters(
        &self,
        params: PaymentTermPaginationParams,
        filters: PaymentTermFilter,
    ) -> Result<PaymentTermPaginatedResult>;

    /// Count all payment_term entities
    async fn count(&self) -> Result<u64>;

    /// Count payment_term entities matching filters
    async fn count_with_filters(&self, filters: PaymentTermFilter) -> Result<u64>;

    /// Check if payment_term exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete payment_term by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted payment_term by ID
    async fn restore(&self, id: &str) -> Result<Option<PaymentTerm>>;

    /// List soft-deleted payment_term entities
    async fn list_deleted(
        &self,
        params: PaymentTermPaginationParams,
    ) -> Result<PaymentTermPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save payment_term entities
    async fn bulk_save(&self, entities: &[PaymentTerm]) -> Result<Vec<PaymentTerm>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
