//! Repository trait for PaymentTermLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PaymentTermLine aggregate.
//! Implementation is in the infrastructure layer.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use crate::domain::entity::{
    PaymentTermAnchor, PaymentTermDelayType, PaymentTermLine, PaymentTermLineValue,
};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentTermLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PaymentTermLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PaymentTermLinePaginatedResult {
    pub data: Vec<PaymentTermLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PaymentTermLineFilter {
    pub term_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub value: Option<PaymentTermLineValue>,
    pub delay_type: Option<PaymentTermDelayType>,
    pub anchor: Option<PaymentTermAnchor>,
}

impl PaymentTermLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.term_id.is_some()
            || self.company_id.is_some()
            || self.value.is_some()
            || self.delay_type.is_some()
            || self.anchor.is_some()
    }
}

/// Repository trait for PaymentTermLine aggregate
///
/// This trait defines the persistence contract for PaymentTermLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PaymentTermLineRepository: Send + Sync {
    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new payment_term_line entity
    async fn save(&self, entity: &PaymentTermLine) -> Result<PaymentTermLine>;

    /// Find payment_term_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PaymentTermLine>>;

    /// Find all payment_term_line entities
    async fn find_all(&self) -> Result<Vec<PaymentTermLine>>;

    /// Update payment_term_line by ID
    async fn update(&self, id: &str, entity: &PaymentTermLine) -> Result<Option<PaymentTermLine>>;

    /// Delete payment_term_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List payment_term_line with pagination
    async fn list(
        &self,
        params: PaymentTermLinePaginationParams,
    ) -> Result<PaymentTermLinePaginatedResult>;

    /// List payment_term_line with pagination and filters
    async fn list_with_filters(
        &self,
        params: PaymentTermLinePaginationParams,
        filters: PaymentTermLineFilter,
    ) -> Result<PaymentTermLinePaginatedResult>;

    /// Count all payment_term_line entities
    async fn count(&self) -> Result<u64>;

    /// Count payment_term_line entities matching filters
    async fn count_with_filters(&self, filters: PaymentTermLineFilter) -> Result<u64>;

    /// Check if payment_term_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete payment_term_line by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted payment_term_line by ID
    async fn restore(&self, id: &str) -> Result<Option<PaymentTermLine>>;

    /// List soft-deleted payment_term_line entities
    async fn list_deleted(
        &self,
        params: PaymentTermLinePaginationParams,
    ) -> Result<PaymentTermLinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save payment_term_line entities
    async fn bulk_save(&self, entities: &[PaymentTermLine]) -> Result<Vec<PaymentTermLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
