//! Repository trait for PurchaseInvoiceLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PurchaseInvoiceLine aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PurchaseInvoiceLine;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseInvoiceLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PurchaseInvoiceLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PurchaseInvoiceLinePaginatedResult {
    pub data: Vec<PurchaseInvoiceLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseInvoiceLineFilter {
    pub invoice_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub expense_account_id: Option<Uuid>,
    pub description: Option<String>,
}

impl PurchaseInvoiceLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.invoice_id.is_some() || self.item_id.is_some() || self.expense_account_id.is_some() || self.description.is_some()
    }
}

/// Repository trait for PurchaseInvoiceLine aggregate
///
/// This trait defines the persistence contract for PurchaseInvoiceLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PurchaseInvoiceLineRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new purchase_invoice_line entity
    async fn save(&self, entity: &PurchaseInvoiceLine) -> Result<PurchaseInvoiceLine>;

    /// Find purchase_invoice_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PurchaseInvoiceLine>>;

    /// Find all purchase_invoice_line entities
    async fn find_all(&self) -> Result<Vec<PurchaseInvoiceLine>>;

    /// Update purchase_invoice_line by ID
    async fn update(&self, id: &str, entity: &PurchaseInvoiceLine) -> Result<Option<PurchaseInvoiceLine>>;

    /// Delete purchase_invoice_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List purchase_invoice_line with pagination
    async fn list(&self, params: PurchaseInvoiceLinePaginationParams) -> Result<PurchaseInvoiceLinePaginatedResult>;

    /// List purchase_invoice_line with pagination and filters
    async fn list_with_filters(&self, params: PurchaseInvoiceLinePaginationParams, filters: PurchaseInvoiceLineFilter) -> Result<PurchaseInvoiceLinePaginatedResult>;

    /// Count all purchase_invoice_line entities
    async fn count(&self) -> Result<u64>;

    /// Count purchase_invoice_line entities matching filters
    async fn count_with_filters(&self, filters: PurchaseInvoiceLineFilter) -> Result<u64>;

    /// Check if purchase_invoice_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete purchase_invoice_line by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted purchase_invoice_line by ID
    async fn restore(&self, id: &str) -> Result<Option<PurchaseInvoiceLine>>;

    /// List soft-deleted purchase_invoice_line entities
    async fn list_deleted(&self, params: PurchaseInvoiceLinePaginationParams) -> Result<PurchaseInvoiceLinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save purchase_invoice_line entities
    async fn bulk_save(&self, entities: &[PurchaseInvoiceLine]) -> Result<Vec<PurchaseInvoiceLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
