//! Repository trait for Settlement aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Settlement aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Settlement, SettlementFrequency, SettlementStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SettlementPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SettlementPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SettlementPaginatedResult {
    pub data: Vec<Settlement>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SettlementFilter {
    pub settlement_number: Option<String>,
    pub provider_id: Option<Uuid>,
    pub frequency: Option<SettlementFrequency>,
    pub currency: Option<String>,
    pub adjustment_notes: Option<String>,
    pub bank_account_id: Option<Uuid>,
    pub status: Option<SettlementStatus>,
    pub failure_reason: Option<String>,
    pub transfer_reference: Option<String>,
    pub transfer_receipt_url: Option<String>,
    pub is_on_hold: Option<bool>,
    pub hold_reason: Option<String>,
    pub held_by: Option<Uuid>,
    pub released_by: Option<Uuid>,
    pub invoice_id: Option<Uuid>,
    pub invoice_generated: Option<bool>,
    pub notes: Option<String>,
}

impl SettlementFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.settlement_number.is_some() || self.provider_id.is_some() || self.frequency.is_some() || self.currency.is_some() || self.adjustment_notes.is_some() || self.bank_account_id.is_some() || self.status.is_some() || self.failure_reason.is_some() || self.transfer_reference.is_some() || self.transfer_receipt_url.is_some() || self.is_on_hold.is_some() || self.hold_reason.is_some() || self.held_by.is_some() || self.released_by.is_some() || self.invoice_id.is_some() || self.invoice_generated.is_some() || self.notes.is_some()
    }
}

/// Repository trait for Settlement aggregate
///
/// This trait defines the persistence contract for Settlement entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SettlementRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new settlement entity
    async fn save(&self, entity: &Settlement) -> Result<Settlement>;

    /// Find settlement by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Settlement>>;

    /// Find all settlement entities
    async fn find_all(&self) -> Result<Vec<Settlement>>;

    /// Update settlement by ID
    async fn update(&self, id: &str, entity: &Settlement) -> Result<Option<Settlement>>;

    /// Delete settlement by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List settlement with pagination
    async fn list(&self, params: SettlementPaginationParams) -> Result<SettlementPaginatedResult>;

    /// List settlement with pagination and filters
    async fn list_with_filters(&self, params: SettlementPaginationParams, filters: SettlementFilter) -> Result<SettlementPaginatedResult>;

    /// Count all settlement entities
    async fn count(&self) -> Result<u64>;

    /// Count settlement entities matching filters
    async fn count_with_filters(&self, filters: SettlementFilter) -> Result<u64>;

    /// Check if settlement exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete settlement by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted settlement by ID
    async fn restore(&self, id: &str) -> Result<Option<Settlement>>;

    /// List soft-deleted settlement entities
    async fn list_deleted(&self, params: SettlementPaginationParams) -> Result<SettlementPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Query by Unique Fields
    // =========================================================================

    /// Find settlement by settlement_number
    async fn find_by_settlement_number(&self, settlement_number: &str) -> Result<Option<Settlement>>;

    // =========================================================================
    // Existence Checks by Unique Fields
    // =========================================================================

    /// Check if settlement exists by settlement_number
    async fn exists_by_settlement_number(&self, settlement_number: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save settlement entities
    async fn bulk_save(&self, entities: &[Settlement]) -> Result<Vec<Settlement>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
