//! Repository for FinancialPeriod entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<FinancialPeriod, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::FinancialPeriod;

/// Table name for FinancialPeriod entities
pub const TABLE_NAME: &str = "financial_periods";

/// Repository for FinancialPeriod entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct FinancialPeriodRepository(
    backbone_orm::GenericCrudRepository<FinancialPeriod, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for FinancialPeriodRepository {
    type Target = backbone_orm::GenericCrudRepository<FinancialPeriod, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl FinancialPeriodRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(FinancialPeriodRepository, FinancialPeriod, soft_delete);
