//! Repository for InvoiceTaxLine entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written InvoiceTaxLine SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<InvoiceTaxLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;
// The multi-row read twin lives only in the legacy `company_scope` module. Its connection
// discipline is what this repository needs — request-dedicated connection when the composing
// service bound one, plain pool otherwise. The helper's legacy task-local branch is never
// taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::fetch_all_rows_scoped;

use crate::domain::entity::InvoiceTaxLine;

/// Table name for InvoiceTaxLine entities
pub const TABLE_NAME: &str = "billing.invoice_tax_lines";

/// Repository for InvoiceTaxLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct InvoiceTaxLineRepository(
    backbone_orm::GenericCrudRepository<InvoiceTaxLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for InvoiceTaxLineRepository {
    type Target = backbone_orm::GenericCrudRepository<InvoiceTaxLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl InvoiceTaxLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an overlay tax-line insert writes.
///
/// Mirrors the raw column shape rather than the `InvoiceTaxLine` entity: `invoice_kind` and `basis`
/// are supplied as free strings and cast at the DB (`$3::invoice_kind`, `$5::tax_basis`), which is
/// what lets a bad value fail as a DB error instead of a deserialize panic. Caller-supplied lines
/// carry no base (region-neutral billing does not compute it — the literal-0 legacy shape), while
/// engine-computed lines carry the source line's post-policy net; `tax_amount` arrives already
/// rounded. The template/routing columns are `None` for supplied lines and populated only by the
/// document-engine path; `exigibility` NULL-binds to `'on_invoice'` at the DB (the column default).
pub struct NewInvoiceTaxLineRow<'a> {
    pub id: Uuid,
    /// Bound to the `invoice_ref` column — the sales OR purchase invoice id, disambiguated by `kind`.
    pub invoice_ref: Uuid,
    /// Bound to the `invoice_kind` column — "sales" | "purchase".
    pub kind: &'a str,
    pub account_id: Uuid,
    /// "output" | "input" | "withholding".
    pub basis: &'a str,
    pub description: Option<&'a str>,
    pub rate: Decimal,
    pub tax_amount: Decimal,
    pub taxable_base: Decimal,
    /// The tax template that produced this line (engine-computed rows only).
    pub tax_template_id: Option<Uuid>,
    /// The repartition split whose factor produced this amount (engine rows on templates
    /// with repartition families; `None` for legacy template-row routing).
    pub repartition_line_id: Option<Uuid>,
    /// Cash-basis rows: the real account the amount flips to at payment (the posting
    /// `account_id` is the transition account meanwhile). `None` ⟺ exigibility on_invoice.
    pub real_account_id: Option<Uuid>,
    /// "on_invoice" | "on_payment" — `None` binds to the column default `'on_invoice'`.
    pub exigibility: Option<&'a str>,
}

/// One overlay tax line's account + amount — a `Cr PPN Output` / `Dr PPN Input` / `Cr PPh` GL leg.
pub struct TaxAmountRow {
    pub account_id: Uuid,
    pub tax_amount: Decimal,
}

/// Hand-written InvoiceTaxLine SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl InvoiceTaxLineRepository {
    /// Insert one overlay tax line.
    ///
    /// Takes the CALLER'S connection so the tax overlay commits with its header + lines in one unit.
    /// The caller relays the AMBIENT org scope onto it (`org_scope::bind_org_scope_on`) — don't
    /// re-bind here.
    pub async fn insert_tax_line(
        &self,
        conn: &mut sqlx::PgConnection,
        t: &NewInvoiceTaxLineRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO billing.invoice_tax_lines
                (id, invoice_ref, invoice_kind, account_id, basis, description,
                 taxable_base, rate, tax_amount, tax_template_id, repartition_line_id,
                 real_account_id, exigibility)
               VALUES ($1,$2,$3::invoice_kind,$4,$5::tax_basis,$6,$7,$8,$9,$10,$11,$12,
                 COALESCE($13::billing.tax_exigibility, 'on_invoice'))"#,
        )
        .bind(t.id)
        .bind(t.invoice_ref)
        .bind(t.kind)
        .bind(t.account_id)
        .bind(t.basis)
        .bind(t.description)
        .bind(t.taxable_base)
        .bind(t.rate)
        .bind(t.tax_amount)
        .bind(t.tax_template_id)
        .bind(t.repartition_line_id)
        .bind(t.real_account_id)
        .bind(t.exigibility)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the live overlay lines for one invoice + basis, in the order the GL legs are emitted.
    ///
    /// `kind` ("sales"|"purchase") and `basis` ("output"|"input"|"withholding") are BOUND and cast at
    /// the DB — never interpolated. Rides the request-dedicated connection when the composing service
    /// bound one (carrying the decorator's fence variables), plainly on the pool otherwise (ADR-0029).
    pub async fn fetch_amounts_by_basis(
        &self,
        pool: &PgPool,
        invoice_ref: Uuid,
        kind: &str,
        basis: &str,
    ) -> Result<Vec<TaxAmountRow>, sqlx::Error> {
        let rows = fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT account_id, tax_amount FROM billing.invoice_tax_lines
                   WHERE invoice_ref=$1 AND invoice_kind=$2::invoice_kind AND basis=$3::tax_basis
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(invoice_ref)
            .bind(kind)
            .bind(basis),
        )
        .await?;
        Ok(rows
            .iter()
            .map(|r| TaxAmountRow {
                account_id: r.get("account_id"),
                tax_amount: r.get("tax_amount"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(InvoiceTaxLineRepository, InvoiceTaxLine, soft_delete);
