//! Repository for InvoiceTaxLine entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written InvoiceTaxLine SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<InvoiceTaxLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::InvoiceTaxLine;

/// Table name for InvoiceTaxLine entities
pub const TABLE_NAME: &str = "billing.invoice_tax_lines";

/// Repository for InvoiceTaxLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct InvoiceTaxLineRepository(
    backbone_orm::GenericCrudRepository<InvoiceTaxLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for InvoiceTaxLineRepository {
    type Target = backbone_orm::GenericCrudRepository<InvoiceTaxLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl InvoiceTaxLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an overlay tax-line insert writes.
///
/// Mirrors the raw column shape rather than the `InvoiceTaxLine` entity: `invoice_kind` and `basis`
/// are supplied as free strings and cast at the DB (`$3::invoice_kind`, `$5::tax_basis`), which is
/// what lets a bad value fail as a DB error instead of a deserialize panic. `taxable_base` is a
/// literal 0 in the statement — billing is region-neutral and does not compute the base (that is
/// `backbone-tax`'s job later); `tax_amount` arrives already rounded.
pub struct NewInvoiceTaxLineRow<'a> {
    pub id: Uuid,
    /// Bound to the `invoice_ref` column — the sales OR purchase invoice id, disambiguated by `kind`.
    pub invoice_ref: Uuid,
    /// Bound to the `invoice_kind` column — "sales" | "purchase".
    pub kind: &'a str,
    /// Bound to the `company_id` column (denormalized from the parent invoice — resolved by
    /// kind+invoice_ref — so the overlay row passes the ADR-0008 RLS fence on its own).
    /// Required since migration 20260426220010.
    pub company_id: Uuid,
    pub account_id: Uuid,
    /// "output" | "input" | "withholding".
    pub basis: &'a str,
    pub description: Option<&'a str>,
    pub rate: Decimal,
    pub tax_amount: Decimal,
}

/// One overlay tax line's account + amount — a `Cr PPN Output` / `Dr PPN Input` / `Cr PPh` GL leg.
pub struct TaxAmountRow {
    pub account_id: Uuid,
    pub tax_amount: Decimal,
}

/// Hand-written InvoiceTaxLine SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl InvoiceTaxLineRepository {
    /// Insert one overlay tax line.
    ///
    /// Takes the CALLER'S connection so the tax overlay commits with its header + lines in one unit.
    /// The caller has already bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_tax_line(
        &self,
        conn: &mut sqlx::PgConnection,
        t: &NewInvoiceTaxLineRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO billing.invoice_tax_lines
                (id, invoice_ref, invoice_kind, company_id, account_id, basis, description, taxable_base, rate, tax_amount)
               VALUES ($1,$2,$3::invoice_kind,$4,$5,$6::tax_basis,$7,0,$8,$9)"#,
        )
        .bind(t.id).bind(t.invoice_ref).bind(t.kind).bind(t.company_id).bind(t.account_id).bind(t.basis)
        .bind(t.description).bind(t.rate).bind(t.tax_amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the live overlay lines for one invoice + basis, in the order the GL legs are emitted.
    ///
    /// `kind` ("sales"|"purchase") and `basis` ("output"|"input"|"withholding") are BOUND and cast at
    /// the DB — never interpolated. The caller wraps this in `with_company_scope(Some(company))` (the
    /// company comes off the invoice header) so the read passes the RLS fence (ADR-0008).
    pub async fn fetch_amounts_by_basis(
        &self,
        pool: &PgPool,
        invoice_ref: Uuid,
        kind: &str,
        basis: &str,
    ) -> Result<Vec<TaxAmountRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT account_id, tax_amount FROM billing.invoice_tax_lines
                   WHERE invoice_ref=$1 AND invoice_kind=$2::invoice_kind AND basis=$3::tax_basis
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(invoice_ref).bind(kind).bind(basis),
        )
        .await?;
        Ok(rows.iter().map(|r| TaxAmountRow {
            account_id: r.get("account_id"), tax_amount: r.get("tax_amount"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(InvoiceTaxLineRepository, InvoiceTaxLine, soft_delete);
