//! Repository for PaymentSchedule entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written PaymentSchedule SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PaymentSchedule, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::PaymentSchedule;

/// Table name for PaymentSchedule entities
pub const TABLE_NAME: &str = "billing.payment_schedules";

/// Repository for PaymentSchedule entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PaymentScheduleRepository(
    backbone_orm::GenericCrudRepository<PaymentSchedule, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PaymentScheduleRepository {
    type Target = backbone_orm::GenericCrudRepository<PaymentSchedule, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl PaymentScheduleRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an installment insert writes.
///
/// Mirrors the raw column shape rather than the `PaymentSchedule` entity: `invoice_kind` arrives as
/// a free string and is cast at the DB (`$3::invoice_kind`) so a bad kind fails as a DB error, and
/// `status` is a literal cast (`'unpaid'::payment_schedule_status`). `amount` arrives rounded.
pub struct NewPaymentScheduleRow<'a> {
    pub id: Uuid,
    pub invoice_ref: Uuid,
    /// Bound to the `invoice_kind` column — "sales" | "purchase".
    pub kind: &'a str,
    pub company_id: Uuid,
    pub installment_no: i32,
    pub due_date: chrono::NaiveDate,
    pub amount: Decimal,
}

/// A locked installment's drawdown state: how much it is for and how much is already settled.
pub struct ScheduleDrawdownRow {
    pub id: Uuid,
    pub amount: Decimal,
    pub paid_amount: Decimal,
}

/// Hand-written PaymentSchedule SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PaymentScheduleRepository {
    /// Insert one installment.
    ///
    /// Takes the CALLER'S connection so a whole schedule commits as one unit. The caller has already
    /// bound the company on it (`bind_company_on`) — don't re-bind here.
    pub async fn insert_schedule(
        &self,
        conn: &mut sqlx::PgConnection,
        s: &NewPaymentScheduleRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO billing.payment_schedules
                (id, invoice_ref, invoice_kind, company_id, installment_no, due_date, amount, status)
               VALUES ($1,$2,$3::invoice_kind,$4,$5,$6,$7,'unpaid'::payment_schedule_status)"#,
        )
        .bind(s.id).bind(s.invoice_ref).bind(s.kind).bind(s.company_id).bind(s.installment_no)
        .bind(s.due_date).bind(s.amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Lock the live installments `FOR UPDATE` in **fill-in-order** (earliest installment first) — the
    /// order the settlement drawdown consumes them in.
    ///
    /// Takes the CALLER'S connection: the lock must be held for the whole drawdown, and the invoice
    /// row is already locked `FOR UPDATE` on that same transaction. The caller established the company
    /// scope on it — don't re-bind here.
    pub async fn lock_schedules_fill_order(
        &self,
        conn: &mut sqlx::PgConnection,
        invoice_ref: Uuid,
        kind: &str,
    ) -> Result<Vec<ScheduleDrawdownRow>, sqlx::Error> {
        let rows = sqlx::query(
            "SELECT id, amount, paid_amount FROM billing.payment_schedules WHERE invoice_ref=$1 AND invoice_kind=$2::invoice_kind AND (metadata->>'deleted_at') IS NULL ORDER BY installment_no FOR UPDATE",
        )
        .bind(invoice_ref).bind(kind)
        .fetch_all(conn)
        .await?;
        Ok(rows
            .iter()
            .map(|s| ScheduleDrawdownRow {
                id: s.get("id"),
                amount: s.get("amount"),
                paid_amount: s.get("paid_amount"),
            })
            .collect())
    }

    /// Lock the live installments `FOR UPDATE` in **rewind order** (last installment first) — the
    /// inverse of [`Self::lock_schedules_fill_order`], for a settlement reversal.
    ///
    /// Same caller-owned-transaction contract as [`Self::lock_schedules_fill_order`].
    pub async fn lock_schedules_rewind_order(
        &self,
        conn: &mut sqlx::PgConnection,
        invoice_ref: Uuid,
        kind: &str,
    ) -> Result<Vec<ScheduleDrawdownRow>, sqlx::Error> {
        let rows = sqlx::query(
            "SELECT id, amount, paid_amount FROM billing.payment_schedules WHERE invoice_ref=$1 AND invoice_kind=$2::invoice_kind AND (metadata->>'deleted_at') IS NULL ORDER BY installment_no DESC FOR UPDATE",
        )
        .bind(invoice_ref).bind(kind)
        .fetch_all(conn)
        .await?;
        Ok(rows
            .iter()
            .map(|s| ScheduleDrawdownRow {
                id: s.get("id"),
                amount: s.get("amount"),
                paid_amount: s.get("paid_amount"),
            })
            .collect())
    }

    /// Write back one installment's settled amount + its recomputed status ("unpaid" |
    /// "partially_paid" | "paid", cast at the DB). Same caller-owned-transaction contract as the lock
    /// methods — this must ride the transaction holding the row's `FOR UPDATE`.
    pub async fn update_paid(
        &self,
        conn: &mut sqlx::PgConnection,
        schedule_id: Uuid,
        paid_amount: Decimal,
        status: &str,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE billing.payment_schedules SET paid_amount=$2, status=$3::payment_schedule_status WHERE id=$1")
            .bind(schedule_id).bind(paid_amount).bind(status)
            .execute(conn)
            .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(PaymentScheduleRepository, PaymentSchedule, soft_delete);
