//! Repository for PaymentTermLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PaymentTermLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PaymentTermLine;

/// Table name for PaymentTermLine entities
pub const TABLE_NAME: &str = "billing.payment_term_lines";

/// Repository for PaymentTermLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PaymentTermLineRepository(
    backbone_orm::GenericCrudRepository<PaymentTermLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PaymentTermLineRepository {
    type Target = backbone_orm::GenericCrudRepository<PaymentTermLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl PaymentTermLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PaymentTermLineRepository, PaymentTermLine, soft_delete);
