//! Repository for ProviderBankAccount entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ProviderBankAccount, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ProviderBankAccount;

/// Table name for ProviderBankAccount entities
pub const TABLE_NAME: &str = "provider_bank_accounts";

/// Repository for ProviderBankAccount entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ProviderBankAccountRepository(
    backbone_orm::GenericCrudRepository<ProviderBankAccount, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ProviderBankAccountRepository {
    type Target = backbone_orm::GenericCrudRepository<ProviderBankAccount, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ProviderBankAccountRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ProviderBankAccountRepository, ProviderBankAccount, soft_delete);
