//! Repository for PurchaseInvoice entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PurchaseInvoice, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PurchaseInvoice;

/// Table name for PurchaseInvoice entities
pub const TABLE_NAME: &str = "billing.purchase_invoices";

/// Repository for PurchaseInvoice entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PurchaseInvoiceRepository(
    backbone_orm::GenericCrudRepository<PurchaseInvoice, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PurchaseInvoiceRepository {
    type Target = backbone_orm::GenericCrudRepository<PurchaseInvoice, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PurchaseInvoiceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PurchaseInvoiceRepository, PurchaseInvoice, soft_delete);
