//! Repository for PurchaseInvoice entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written PurchaseInvoice SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PurchaseInvoice, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PurchaseInvoice;

use super::sales_invoice_repository::PostingStateRow;

/// Table name for PurchaseInvoice entities
pub const TABLE_NAME: &str = "billing.purchase_invoices";

/// Repository for PurchaseInvoice entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PurchaseInvoiceRepository(
    backbone_orm::GenericCrudRepository<PurchaseInvoice, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PurchaseInvoiceRepository {
    type Target = backbone_orm::GenericCrudRepository<PurchaseInvoice, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl PurchaseInvoiceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a draft Purchase Invoice header insert writes.
///
/// Mirrors the raw column shape rather than the `PurchaseInvoice` entity: `status`/`posting_state`
/// are literal enum casts in the statement, and the money columns arrive already rounded by the
/// caller (`grand_total = net + input − withholding`, the A/P actually owed).
pub struct NewPurchaseInvoiceRow<'a> {
    pub id: Uuid,
    pub invoice_number: &'a str,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub supplier_id: Uuid,
    pub source_po_id: Option<Uuid>,
    pub posting_date: chrono::NaiveDate,
    pub due_date: Option<chrono::NaiveDate>,
    pub currency: &'a str,
    pub net_total: Decimal,
    /// Bound to the `tax_total` column — the Σ of the overlay's `input` basis lines.
    pub tax_total: Decimal,
    pub withholding_total: Decimal,
    pub grand_total: Decimal,
    pub payable_account_id: Uuid,
}

/// The A/P post builder's header projection.
pub struct ApHeaderRow {
    pub invoice_number: String,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub supplier_id: Uuid,
    pub posting_date: chrono::NaiveDate,
    pub currency: String,
    pub grand_total: Decimal,
    pub payable_account_id: Uuid,
}

/// The seam projection read after a winning pending→posted transition: what the PO seam needs.
pub struct PurchaseSeamHeaderRow {
    pub source_po_id: Option<Uuid>,
    pub grand_total: Decimal,
    /// Tax-overlay projection for the tax consumer (net + PPN input + PPh withheld).
    pub net_total: Decimal,
    pub tax_total: Decimal,
    pub withholding_total: Decimal,
}

/// Hand-written PurchaseInvoice SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PurchaseInvoiceRepository {
    /// Insert the draft A/P header. `outstanding_amount` starts at 0 — the posting transition sets it
    /// to `grand_total`.
    ///
    /// Takes the CALLER'S connection so the header, its lines, and the tax overlay commit as one unit.
    /// The caller has already bound the company on it (`bind_company_on`) — don't re-bind here.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate invoice number into `DuplicateNumber`.
    pub async fn insert_draft(
        &self,
        conn: &mut sqlx::PgConnection,
        inv: &NewPurchaseInvoiceRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO billing.purchase_invoices
                (id, invoice_number, company_id, branch_id, supplier_id, source_po_id, status,
                 posting_date, due_date, currency, net_total, tax_total, withholding_total, grand_total,
                 outstanding_amount, payable_account_id, posting_state)
               VALUES ($1,$2,$3,$4,$5,$6,'draft'::invoice_status,$7,$8,$9,$10,$11,$12,$13,0,$14,'pending'::gl_posting_state)"#,
        )
        .bind(inv.id).bind(inv.invoice_number).bind(inv.company_id).bind(inv.branch_id).bind(inv.supplier_id)
        .bind(inv.source_po_id).bind(inv.posting_date).bind(inv.due_date).bind(inv.currency)
        .bind(inv.net_total).bind(inv.tax_total).bind(inv.withholding_total).bind(inv.grand_total)
        .bind(inv.payable_account_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the header the A/P post is built from. `Ok(None)` = no such live invoice in scope.
    ///
    /// ID-only: no company argument. `fetch_optional_row_scoped` means it rides a connection carrying
    /// the caller's `app.company_id` (ADR-0008), so it is fenced by the request/inherited scope.
    pub async fn fetch_ap_header(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<Option<ApHeaderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT invoice_number, company_id, branch_id, supplier_id, posting_date, currency,
                          grand_total, payable_account_id
                   FROM billing.purchase_invoices WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(invoice_id),
        )
        .await?;
        Ok(row.map(|r| ApHeaderRow {
            invoice_number: r.get("invoice_number"),
            company_id: r.get("company_id"),
            branch_id: r.get("branch_id"),
            supplier_id: r.get("supplier_id"),
            posting_date: r.get("posting_date"),
            currency: r.get("currency"),
            grand_total: r.get("grand_total"),
            payable_account_id: r.get("payable_account_id"),
        }))
    }

    /// Probe the GL posting state for the posted short-circuit. `Ok(None)` = no such live invoice.
    /// Shares [`PostingStateRow`] with the A/R side — same projection, other table.
    ///
    /// ID-only, same request/inherited scope fence as [`Self::fetch_ap_header`].
    pub async fn fetch_posting_state(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<Option<PostingStateRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT posting_state::text AS ps, journal_id, accounting_post_id
                   FROM billing.purchase_invoices WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(invoice_id),
        )
        .await?;
        Ok(row.map(|r| PostingStateRow {
            posting_state: r.get("ps"),
            journal_id: r.get("journal_id"),
            accounting_post_id: r.get("accounting_post_id"),
        }))
    }

    /// Record a GL rejection on the pool. The GL-rejected path runs outside the post transaction, so
    /// this stays pool-based (caller wraps it in `with_company_scope(Some(company))`).
    pub async fn mark_posting_failed(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE billing.purchase_invoices SET posting_state='failed'::gl_posting_state WHERE id=$1")
                .bind(invoice_id),
        )
        .await?;
        Ok(())
    }

    // --- Transaction-accepting twins (outbox fence) -------------------------------------------
    // Caller has already bound the company scope onto `conn`; these run the SAME SQL as their pool
    // counterparts on the shared transition transaction (mirrors backbone-payment).

    /// Transaction-accepting twin of [`Self::mark_posted`] — returns rows affected (1 = winner).
    pub async fn mark_posted_on(
        &self,
        conn: &mut sqlx::PgConnection,
        invoice_id: Uuid,
        journal_id: Uuid,
        post_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let done = sqlx::query(
            r#"UPDATE billing.purchase_invoices SET posting_state='posted'::gl_posting_state,
                status='submitted'::invoice_status, journal_id=$2, accounting_post_id=$3,
                posted_at=now(), outstanding_amount=grand_total
               WHERE id=$1 AND posting_state <> 'posted'::gl_posting_state"#,
        )
        .bind(invoice_id)
        .bind(journal_id)
        .bind(post_id)
        .execute(conn)
        .await?;
        Ok(done.rows_affected())
    }

    /// Transaction-accepting twin of [`Self::fetch_seam_header`].
    pub async fn fetch_seam_header_on(
        &self,
        conn: &mut sqlx::PgConnection,
        invoice_id: Uuid,
    ) -> Result<PurchaseSeamHeaderRow, sqlx::Error> {
        let row = sqlx::query("SELECT source_po_id, grand_total, net_total, tax_total, withholding_total FROM billing.purchase_invoices WHERE id=$1")
            .bind(invoice_id)
            .fetch_one(conn)
            .await?;
        Ok(PurchaseSeamHeaderRow {
            source_po_id: row.get("source_po_id"),
            grand_total: row.get("grand_total"),
            net_total: row.get("net_total"),
            tax_total: row.get("tax_total"),
            withholding_total: row.get("withholding_total"),
        })
    }
}

backbone_core::impl_crud_repository!(PurchaseInvoiceRepository, PurchaseInvoice, soft_delete);
