//! Repository for RefundRequest entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RefundRequest, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::RefundRequest;

/// Table name for RefundRequest entities
pub const TABLE_NAME: &str = "refund_requests";

/// Repository for RefundRequest entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RefundRequestRepository(
    backbone_orm::GenericCrudRepository<RefundRequest, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RefundRequestRepository {
    type Target = backbone_orm::GenericCrudRepository<RefundRequest, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RefundRequestRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

impl RefundRequestRepository {
    /// Find refund_request by refund_number (excludes soft-deleted)
    pub async fn find_by_refund_number(&self, refund_number: &str) -> Result<Option<RefundRequest>> {
        self.find_by_text_field("refund_number", refund_number).await
    }

    /// Check if refund_request exists by refund_number (excludes soft-deleted)
    pub async fn exists_by_refund_number(&self, refund_number: &str) -> Result<bool> {
        self.exists_by_text_field("refund_number", refund_number).await
    }

}

backbone_core::impl_crud_repository!(RefundRequestRepository, RefundRequest, soft_delete);
