//! Repository for SalesInvoiceLine entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written SalesInvoiceLine SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalesInvoiceLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;
// The multi-row read twin lives only in the legacy `company_scope` module. Its connection
// discipline is what this repository needs — request-dedicated connection when the composing
// service bound one, plain pool otherwise. The helper's legacy task-local branch is never
// taken: this module sets no legacy scope of its own (ADR-0029).
use backbone_orm::company_scope::fetch_all_rows_scoped;

use crate::domain::entity::SalesInvoiceLine;

/// Table name for SalesInvoiceLine entities
pub const TABLE_NAME: &str = "billing.sales_invoice_lines";

/// Repository for SalesInvoiceLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalesInvoiceLineRepository(
    backbone_orm::GenericCrudRepository<SalesInvoiceLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalesInvoiceLineRepository {
    type Target = backbone_orm::GenericCrudRepository<SalesInvoiceLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl SalesInvoiceLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a priced Sales Invoice line insert writes.
///
/// Mirrors the raw column shape rather than the `SalesInvoiceLine` entity: `account_id` binds the
/// `revenue_account_id` column (the service's priced line calls it the account, the table calls it
/// the revenue account), and `net_amount` arrives already rounded.
pub struct NewSalesInvoiceLineRow<'a> {
    pub id: Uuid,
    pub invoice_id: Uuid,
    pub item_id: Uuid,
    /// Bound to the `revenue_account_id` column.
    pub account_id: Uuid,
    pub description: Option<&'a str>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub net_amount: Decimal,
}

/// One line's revenue account + net, for the `Cr Revenue` legs of the A/R post.
pub struct RevenueAmountRow {
    pub revenue_account_id: Uuid,
    pub net_amount: Decimal,
}

/// One line's item + quantity — the selling seam's `billed_lines` payload, which advances the source
/// SO's `billed_qty`.
pub struct BilledLineRow {
    pub item_id: Uuid,
    pub quantity: Decimal,
}

/// Hand-written SalesInvoiceLine SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl SalesInvoiceLineRepository {
    /// Insert one priced line.
    ///
    /// Takes the CALLER'S connection so the line commits with its header in one unit. The caller
    /// relays the AMBIENT org scope onto it (`org_scope::bind_org_scope_on`) — don't re-bind here.
    pub async fn insert_line(
        &self,
        conn: &mut sqlx::PgConnection,
        l: &NewSalesInvoiceLineRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO billing.sales_invoice_lines
                (id, invoice_id, item_id, revenue_account_id, description, quantity, unit_price, net_amount)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8)"#,
        )
        .bind(l.id).bind(l.invoice_id).bind(l.item_id).bind(l.account_id).bind(l.description)
        .bind(l.quantity).bind(l.unit_price).bind(l.net_amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the live lines' revenue accounts + nets for the A/R post. Rides the request-dedicated
    /// connection when the composing service bound one (carrying the decorator's fence variables),
    /// plainly on the pool otherwise (ADR-0029).
    pub async fn fetch_revenue_amounts(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<Vec<RevenueAmountRow>, sqlx::Error> {
        let rows = fetch_all_rows_scoped(
            pool,
            sqlx::query("SELECT revenue_account_id, net_amount FROM billing.sales_invoice_lines WHERE invoice_id=$1 AND (metadata->>'deleted_at') IS NULL")
                .bind(invoice_id),
        )
        .await?;
        Ok(rows
            .iter()
            .map(|r| RevenueAmountRow {
                revenue_account_id: r.get("revenue_account_id"),
                net_amount: r.get("net_amount"),
            })
            .collect())
    }

    /// Read the live lines' item + qty for the selling seam on the shared transition transaction
    /// (outbox fence) so the staged event matches the commit.
    pub async fn fetch_billed_lines_on(
        &self,
        conn: &mut sqlx::PgConnection,
        invoice_id: Uuid,
    ) -> Result<Vec<BilledLineRow>, sqlx::Error> {
        let rows: Vec<sqlx::postgres::PgRow> = sqlx::query(
            "SELECT item_id, quantity FROM billing.sales_invoice_lines WHERE invoice_id=$1 AND (metadata->>'deleted_at') IS NULL",
        )
        .bind(invoice_id)
        .fetch_all(conn)
        .await?;
        Ok(rows
            .iter()
            .map(|r| BilledLineRow {
                item_id: r.get("item_id"),
                quantity: r.get("quantity"),
            })
            .collect())
    }
}

backbone_core::impl_crud_repository!(SalesInvoiceLineRepository, SalesInvoiceLine, soft_delete);
