//! Repository for Settlement entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Settlement, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Settlement;

/// Table name for Settlement entities
pub const TABLE_NAME: &str = "settlements";

/// Repository for Settlement entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SettlementRepository(
    backbone_orm::GenericCrudRepository<Settlement, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SettlementRepository {
    type Target = backbone_orm::GenericCrudRepository<Settlement, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SettlementRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

impl SettlementRepository {
    /// Find settlement by settlement_number (excludes soft-deleted)
    pub async fn find_by_settlement_number(&self, settlement_number: &str) -> Result<Option<Settlement>> {
        self.find_by_text_field("settlement_number", settlement_number).await
    }

    /// Check if settlement exists by settlement_number (excludes soft-deleted)
    pub async fn exists_by_settlement_number(&self, settlement_number: &str) -> Result<bool> {
        self.exists_by_text_field("settlement_number", settlement_number).await
    }

}

backbone_core::impl_crud_repository!(SettlementRepository, Settlement, soft_delete);
