//! Validator for InvoiceLineItem entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<InvoiceLineItem>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString, RequiredUuid};
use crate::domain::entity::InvoiceLineItem;

/// Validator type alias for InvoiceLineItem entities.
pub type InvoiceLineItemValidator = EntityValidator<InvoiceLineItem>;

/// Build a validator for InvoiceLineItem with all schema-defined field rules.
pub fn invoice_line_item_validator() -> InvoiceLineItemValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("invoice_id", |e: &InvoiceLineItem| &e.invoice_id))
        .rule(RequiredString::new("description", |e: &InvoiceLineItem| &e.description))
        .rule(NonNegative::new("unit_price", |e: &InvoiceLineItem| e.unit_price))
        .rule(NonNegative::new("amount", |e: &InvoiceLineItem| e.amount))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
