//! Validator for Invoice entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Invoice>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::Invoice;

/// Validator type alias for Invoice entities.
pub type InvoiceValidator = EntityValidator<Invoice>;

/// Build a validator for Invoice with all schema-defined field rules.
pub fn invoice_validator() -> InvoiceValidator {
    EntityValidator::new()
        .rule(RequiredString::new("invoice_number", |e: &Invoice| &e.invoice_number))
        .rule(RequiredUuid::new("invoiceable_id", |e: &Invoice| &e.invoiceable_id))
        .rule(RequiredString::new("currency", |e: &Invoice| &e.currency))
        .rule(NonNegative::new("subtotal", |e: &Invoice| e.subtotal))
        .rule(NonNegative::new("discount_amount", |e: &Invoice| e.discount_amount))
        .rule(NonNegative::new("tax_amount", |e: &Invoice| e.tax_amount))
        .rule(NonNegative::new("total_amount", |e: &Invoice| e.total_amount))
        .rule(OptionalNotBlank::new("sent_via", |e: &Invoice| e.sent_via.as_deref()))
        .rule(OptionalNotBlank::new("pdf_url", |e: &Invoice| e.pdf_url.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &Invoice| e.notes.as_deref()))
        .rule(OptionalNotBlank::new("terms", |e: &Invoice| e.terms.as_deref()))
        .rule(OptionalNotBlank::new("footer", |e: &Invoice| e.footer.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
