//! Validator for PaymentFee entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PaymentFee>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredUuid};
use crate::domain::entity::PaymentFee;

/// Validator type alias for PaymentFee entities.
pub type PaymentFeeValidator = EntityValidator<PaymentFee>;

/// Build a validator for PaymentFee with all schema-defined field rules.
pub fn payment_fee_validator() -> PaymentFeeValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("payment_id", |e: &PaymentFee| &e.payment_id))
        .rule(NonNegative::new("amount", |e: &PaymentFee| e.amount))
        .rule(OptionalNotBlank::new("description", |e: &PaymentFee| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
