//! Validator for PaymentTerm entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PaymentTerm>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::PaymentTerm;

/// Validator type alias for PaymentTerm entities.
pub type PaymentTermValidator = EntityValidator<PaymentTerm>;

/// Build a validator for PaymentTerm with all schema-defined field rules.
pub fn payment_term_validator() -> PaymentTermValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &PaymentTerm| &e.name))
        .rule(OptionalNotBlank::new("note", |e: &PaymentTerm| e.note.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
