//! Validator for PaymentTermLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PaymentTermLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::PaymentTermLine;

/// Validator type alias for PaymentTermLine entities.
pub type PaymentTermLineValidator = EntityValidator<PaymentTermLine>;

/// Build a validator for PaymentTermLine with all schema-defined field rules.
pub fn payment_term_line_validator() -> PaymentTermLineValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
