//! Validator for Settlement entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Settlement>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::Settlement;

/// Validator type alias for Settlement entities.
pub type SettlementValidator = EntityValidator<Settlement>;

/// Build a validator for Settlement with all schema-defined field rules.
pub fn settlement_validator() -> SettlementValidator {
    EntityValidator::new()
        .rule(RequiredString::new("settlement_number", |e: &Settlement| &e.settlement_number))
        .rule(RequiredUuid::new("provider_id", |e: &Settlement| &e.provider_id))
        .rule(RequiredString::new("currency", |e: &Settlement| &e.currency))
        .rule(NonNegative::new("gross_amount", |e: &Settlement| e.gross_amount))
        .rule(NonNegative::new("platform_commission", |e: &Settlement| e.platform_commission))
        .rule(NonNegative::new("transaction_fees", |e: &Settlement| e.transaction_fees))
        .rule(NonNegative::new("payment_gateway_fees", |e: &Settlement| e.payment_gateway_fees))
        .rule(NonNegative::new("refunds_amount", |e: &Settlement| e.refunds_amount))
        .rule(OptionalNotBlank::new("adjustment_notes", |e: &Settlement| e.adjustment_notes.as_deref()))
        .rule(NonNegative::new("withholding_tax", |e: &Settlement| e.withholding_tax))
        .rule(OptionalNotBlank::new("failure_reason", |e: &Settlement| e.failure_reason.as_deref()))
        .rule(OptionalNotBlank::new("transfer_reference", |e: &Settlement| e.transfer_reference.as_deref()))
        .rule(OptionalNotBlank::new("transfer_receipt_url", |e: &Settlement| e.transfer_receipt_url.as_deref()))
        .rule(OptionalNotBlank::new("hold_reason", |e: &Settlement| e.hold_reason.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &Settlement| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
