//! Auth configuration for FinancialPeriod handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<FinancialPeriod>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::FinancialPeriodService;
use crate::domain::entity::FinancialPeriod;

/// Permission string constants for FinancialPeriod operations.
pub mod permissions {
    pub const LIST:        &str = "financial_period:list";
    pub const READ:        &str = "financial_period:read";
    pub const CREATE:      &str = "financial_period:create";
    pub const UPDATE:      &str = "financial_period:update";
    pub const DELETE:      &str = "financial_period:delete";
    pub const RESTORE:     &str = "financial_period:restore";
    pub const TRASH:       &str = "financial_period:trash";
    pub const EMPTY_TRASH: &str = "financial_period:empty_trash";
    pub const BULK_CREATE: &str = "financial_period:bulk_create";
    pub const UPSERT:      &str = "financial_period:upsert";
}

/// Resource policy for FinancialPeriod — maps CRUD actions to permission strings.
pub struct FinancialPeriodPolicy;

#[async_trait]
impl ResourcePolicy<FinancialPeriod> for FinancialPeriodPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &FinancialPeriod,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for FinancialPeriod handlers.
///
/// Wraps `FinancialPeriodService` and checks `FinancialPeriodPolicy` before delegating.
pub type FinancialPeriodGuard = PermissionGuard<FinancialPeriod, FinancialPeriodService, FinancialPeriodPolicy>;

/// Service-integrated permission guard for FinancialPeriod (for use in generated handlers).
pub type FinancialPeriodServiceGuard = ServicePermissionGuard<FinancialPeriod, FinancialPeriodService, FinancialPeriodPolicy>;

// <<< CUSTOM
// END CUSTOM
