//! Auth configuration for InvoiceLineItem handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<InvoiceLineItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::InvoiceLineItemService;
use crate::domain::entity::InvoiceLineItem;

/// Permission string constants for InvoiceLineItem operations.
pub mod permissions {
    pub const LIST:        &str = "invoice_line_item:list";
    pub const READ:        &str = "invoice_line_item:read";
    pub const CREATE:      &str = "invoice_line_item:create";
    pub const UPDATE:      &str = "invoice_line_item:update";
    pub const DELETE:      &str = "invoice_line_item:delete";
    pub const RESTORE:     &str = "invoice_line_item:restore";
    pub const TRASH:       &str = "invoice_line_item:trash";
    pub const EMPTY_TRASH: &str = "invoice_line_item:empty_trash";
    pub const BULK_CREATE: &str = "invoice_line_item:bulk_create";
    pub const UPSERT:      &str = "invoice_line_item:upsert";
}

/// Resource policy for InvoiceLineItem — maps CRUD actions to permission strings.
pub struct InvoiceLineItemPolicy;

#[async_trait]
impl ResourcePolicy<InvoiceLineItem> for InvoiceLineItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &InvoiceLineItem,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for InvoiceLineItem handlers.
///
/// Wraps `InvoiceLineItemService` and checks `InvoiceLineItemPolicy` before delegating.
pub type InvoiceLineItemGuard = PermissionGuard<InvoiceLineItem, InvoiceLineItemService, InvoiceLineItemPolicy>;

/// Service-integrated permission guard for InvoiceLineItem (for use in generated handlers).
pub type InvoiceLineItemServiceGuard = ServicePermissionGuard<InvoiceLineItem, InvoiceLineItemService, InvoiceLineItemPolicy>;

// <<< CUSTOM
// END CUSTOM
