//! Auth configuration for PaymentFee handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PaymentFee>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PaymentFeeService;
use crate::domain::entity::PaymentFee;

/// Permission string constants for PaymentFee operations.
pub mod permissions {
    pub const LIST:        &str = "payment_fee:list";
    pub const READ:        &str = "payment_fee:read";
    pub const CREATE:      &str = "payment_fee:create";
    pub const UPDATE:      &str = "payment_fee:update";
    pub const DELETE:      &str = "payment_fee:delete";
    pub const RESTORE:     &str = "payment_fee:restore";
    pub const TRASH:       &str = "payment_fee:trash";
    pub const EMPTY_TRASH: &str = "payment_fee:empty_trash";
    pub const BULK_CREATE: &str = "payment_fee:bulk_create";
    pub const UPSERT:      &str = "payment_fee:upsert";
}

/// Resource policy for PaymentFee — maps CRUD actions to permission strings.
pub struct PaymentFeePolicy;

#[async_trait]
impl ResourcePolicy<PaymentFee> for PaymentFeePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PaymentFee,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for PaymentFee handlers.
///
/// Wraps `PaymentFeeService` and checks `PaymentFeePolicy` before delegating.
pub type PaymentFeeGuard = PermissionGuard<PaymentFee, PaymentFeeService, PaymentFeePolicy>;

/// Service-integrated permission guard for PaymentFee (for use in generated handlers).
pub type PaymentFeeServiceGuard = ServicePermissionGuard<PaymentFee, PaymentFeeService, PaymentFeePolicy>;

// <<< CUSTOM
// END CUSTOM
