//! Auth configuration for Payment handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Payment>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PaymentService;
use crate::domain::entity::Payment;

/// Permission string constants for Payment operations.
pub mod permissions {
    pub const LIST:        &str = "payment:list";
    pub const READ:        &str = "payment:read";
    pub const CREATE:      &str = "payment:create";
    pub const UPDATE:      &str = "payment:update";
    pub const DELETE:      &str = "payment:delete";
    pub const RESTORE:     &str = "payment:restore";
    pub const TRASH:       &str = "payment:trash";
    pub const EMPTY_TRASH: &str = "payment:empty_trash";
    pub const BULK_CREATE: &str = "payment:bulk_create";
    pub const UPSERT:      &str = "payment:upsert";
}

/// Resource policy for Payment — maps CRUD actions to permission strings.
pub struct PaymentPolicy;

#[async_trait]
impl ResourcePolicy<Payment> for PaymentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Payment,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for Payment handlers.
///
/// Wraps `PaymentService` and checks `PaymentPolicy` before delegating.
pub type PaymentGuard = PermissionGuard<Payment, PaymentService, PaymentPolicy>;

/// Service-integrated permission guard for Payment (for use in generated handlers).
pub type PaymentServiceGuard = ServicePermissionGuard<Payment, PaymentService, PaymentPolicy>;

// <<< CUSTOM
// END CUSTOM
