//! Auth configuration for PurchaseInvoice handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PurchaseInvoice>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PurchaseInvoiceService;
use crate::domain::entity::PurchaseInvoice;

/// Permission string constants for PurchaseInvoice operations.
pub mod permissions {
    pub const LIST:        &str = "purchase_invoice:list";
    pub const READ:        &str = "purchase_invoice:read";
    pub const CREATE:      &str = "purchase_invoice:create";
    pub const UPDATE:      &str = "purchase_invoice:update";
    pub const DELETE:      &str = "purchase_invoice:delete";
    pub const RESTORE:     &str = "purchase_invoice:restore";
    pub const TRASH:       &str = "purchase_invoice:trash";
    pub const EMPTY_TRASH: &str = "purchase_invoice:empty_trash";
    pub const BULK_CREATE: &str = "purchase_invoice:bulk_create";
    pub const UPSERT:      &str = "purchase_invoice:upsert";
}

/// Resource policy for PurchaseInvoice — maps CRUD actions to permission strings.
pub struct PurchaseInvoicePolicy;

#[async_trait]
impl ResourcePolicy<PurchaseInvoice> for PurchaseInvoicePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PurchaseInvoice,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PurchaseInvoice handlers.
///
/// Wraps `PurchaseInvoiceService` and checks `PurchaseInvoicePolicy` before delegating.
pub type PurchaseInvoiceGuard = PermissionGuard<PurchaseInvoice>;

/// Service-integrated permission guard for PurchaseInvoice (for use in generated handlers).
pub type PurchaseInvoiceServiceGuard = ServicePermissionGuard<PurchaseInvoice, PurchaseInvoiceService, PurchaseInvoicePolicy>;

// <<< CUSTOM
// END CUSTOM
