//! InvoiceParty API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the InvoiceParty CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// INVOICEPARTY TEST DATA GENERATOR
// ============================================================================

/// Test data generator for InvoiceParty
pub struct InvoicePartyTestData;

impl TestDataGenerator for InvoicePartyTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "invoice_id": null,
            "role": null,
            "party_type": null,
            "party_id": null,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "email": format!("test{}@example.com", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "address": null,
            "tax_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "invoice_id": null,
            "role": null,
            "party_type": null,
            "party_id": null,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "email": format!("test{}@example.com", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "address": null,
            "tax_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// INVOICEPARTY API TEST
// ============================================================================

/// InvoiceParty API test suite
pub struct InvoicePartyApiTest {
    inner: GenericCrudTest<InvoicePartyTestData>,
}

impl InvoicePartyApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/invoice_parties", "InvoiceParty");
        Self {
            inner: GenericCrudTest::new(config, InvoicePartyTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for InvoicePartyApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_invoice_party_crud() {
        let mut test = InvoicePartyApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add InvoiceParty specific tests here
// <<< CUSTOM TESTS END >>>
