//! InvoiceTaxLine API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the InvoiceTaxLine CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// INVOICETAXLINE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for InvoiceTaxLine
pub struct InvoiceTaxLineTestData;

impl TestDataGenerator for InvoiceTaxLineTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "invoice_ref": Uuid::new_v4().to_string(),
            "invoice_kind": "sales",
            "company_id": Uuid::new_v4().to_string(),
            "account_id": Uuid::new_v4().to_string(),
            "basis": "output",
            "description": null,
            "taxable_base": 0,
            "rate": 0,
            "tax_amount": 0,
            "tax_template_id": null,
            "repartition_line_id": null,
            "real_account_id": null,
            "exigibility": "on_invoice",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "invoice_ref": Uuid::new_v4().to_string(),
            "invoice_kind": "sales",
            "company_id": Uuid::new_v4().to_string(),
            "account_id": Uuid::new_v4().to_string(),
            "basis": "output",
            "description": null,
            "taxable_base": 0,
            "rate": 0,
            "tax_amount": 0,
            "tax_template_id": null,
            "repartition_line_id": null,
            "real_account_id": null,
            "exigibility": "on_invoice",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// INVOICETAXLINE API TEST
// ============================================================================

/// InvoiceTaxLine API test suite
pub struct InvoiceTaxLineApiTest {
    inner: GenericCrudTest<InvoiceTaxLineTestData>,
}

impl InvoiceTaxLineApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/invoice_tax_lines", "InvoiceTaxLine");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, InvoiceTaxLineTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for InvoiceTaxLineApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_invoice_tax_line_crud() {
        let mut test = InvoiceTaxLineApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add InvoiceTaxLine specific tests here
// <<< CUSTOM TESTS END >>>
