//! InvoiceLineItem API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the InvoiceLineItem CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// INVOICELINEITEM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for InvoiceLineItem
pub struct InvoiceLineItemTestData;

impl TestDataGenerator for InvoiceLineItemTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "invoice_id": null,
            "sort_order": 1,
            "description": "Test description",
            "quantity": null,
            "unit_price": null,
            "amount": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "invoice_id": null,
            "sort_order": 1,
            "description": "Test description",
            "quantity": null,
            "unit_price": null,
            "amount": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// INVOICELINEITEM API TEST
// ============================================================================

/// InvoiceLineItem API test suite
pub struct InvoiceLineItemApiTest {
    inner: GenericCrudTest<InvoiceLineItemTestData>,
}

impl InvoiceLineItemApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/invoice_line_items", "InvoiceLineItem");
        Self {
            inner: GenericCrudTest::new(config, InvoiceLineItemTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for InvoiceLineItemApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_invoice_line_item_crud() {
        let mut test = InvoiceLineItemApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add InvoiceLineItem specific tests here
// <<< CUSTOM TESTS END >>>
