//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod invoice_tax_line_api_test;
pub mod payment_schedule_api_test;
pub mod payment_term_api_test;
pub mod payment_term_line_api_test;
pub mod purchase_invoice_api_test;
pub mod purchase_invoice_line_api_test;
pub mod sales_invoice_api_test;
pub mod sales_invoice_line_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use invoice_tax_line_api_test::*;
pub use payment_schedule_api_test::*;
pub use payment_term_api_test::*;
pub use payment_term_line_api_test::*;
pub use purchase_invoice_api_test::*;
pub use purchase_invoice_line_api_test::*;
pub use sales_invoice_api_test::*;
pub use sales_invoice_line_api_test::*;
