//! PaymentSchedule API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PaymentSchedule CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PAYMENTSCHEDULE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PaymentSchedule
pub struct PaymentScheduleTestData;

impl TestDataGenerator for PaymentScheduleTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "invoice_ref": Uuid::new_v4().to_string(),
            "invoice_kind": "sales",
            "company_id": Uuid::new_v4().to_string(),
            "installment_no": 1,
            "due_date": Utc::now().format("%Y-%m-%d").to_string(),
            "amount": 0,
            "paid_amount": 0,
            "status": "unpaid",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "invoice_ref": Uuid::new_v4().to_string(),
            "invoice_kind": "sales",
            "company_id": Uuid::new_v4().to_string(),
            "installment_no": 1,
            "due_date": Utc::now().format("%Y-%m-%d").to_string(),
            "amount": 0,
            "paid_amount": 0,
            "status": "unpaid",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PAYMENTSCHEDULE API TEST
// ============================================================================

/// PaymentSchedule API test suite
pub struct PaymentScheduleApiTest {
    inner: GenericCrudTest<PaymentScheduleTestData>,
}

impl PaymentScheduleApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/payment_schedules", "PaymentSchedule");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PaymentScheduleTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PaymentScheduleApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_payment_schedule_crud() {
        let mut test = PaymentScheduleApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PaymentSchedule specific tests here
// <<< CUSTOM TESTS END >>>
