//! PaymentTerm API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PaymentTerm CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PAYMENTTERM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PaymentTerm
pub struct PaymentTermTestData;

impl TestDataGenerator for PaymentTermTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": null,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "note": null,
            "sequence": 1,
            "status": "active",
            "early_discount": false,
            "discount_percent": 0,
            "discount_days": 1,
            "discount_account_id": null,
            "discount_tax_basis": "included",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": null,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "note": null,
            "sequence": 1,
            "status": "active",
            "early_discount": false,
            "discount_percent": 0,
            "discount_days": 1,
            "discount_account_id": null,
            "discount_tax_basis": "included",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PAYMENTTERM API TEST
// ============================================================================

/// PaymentTerm API test suite
pub struct PaymentTermApiTest {
    inner: GenericCrudTest<PaymentTermTestData>,
}

impl PaymentTermApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/payment_terms", "PaymentTerm");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PaymentTermTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PaymentTermApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_payment_term_crud() {
        let mut test = PaymentTermApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PaymentTerm specific tests here
// <<< CUSTOM TESTS END >>>
