//! SalesInvoiceLine API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SalesInvoiceLine CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SALESINVOICELINE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SalesInvoiceLine
pub struct SalesInvoiceLineTestData;

impl TestDataGenerator for SalesInvoiceLineTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "invoice_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "revenue_account_id": Uuid::new_v4().to_string(),
            "description": null,
            "quantity": 0,
            "unit_price": 0,
            "net_amount": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "invoice_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "revenue_account_id": Uuid::new_v4().to_string(),
            "description": null,
            "quantity": 0,
            "unit_price": 0,
            "net_amount": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/sales_invoices", &super::sales_invoice_api_test::SalesInvoiceTestData).await {
            deps.push(("invoice_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SALESINVOICELINE API TEST
// ============================================================================

/// SalesInvoiceLine API test suite
pub struct SalesInvoiceLineApiTest {
    inner: GenericCrudTest<SalesInvoiceLineTestData>,
}

impl SalesInvoiceLineApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/sales_invoice_lines", "SalesInvoiceLine");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SalesInvoiceLineTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SalesInvoiceLineApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_sales_invoice_line_crud() {
        let mut test = SalesInvoiceLineApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SalesInvoiceLine specific tests here
// <<< CUSTOM TESTS END >>>
