//! Billing Module Handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AgentEarningService;
use crate::application::service::FinancialPeriodService;
use crate::application::service::PaymentService;
use crate::application::service::PaymentGatewayDetailService;
use crate::application::service::PaymentFeeService;
use crate::application::service::InvoiceService;
use crate::application::service::InvoicePartyService;
use crate::application::service::InvoiceLineItemService;
use crate::application::service::ProviderBankAccountService;
use crate::application::service::RefundRequestService;
use crate::application::service::SettlementService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// AgentEarning service
    pub agent_earning_service: Arc<AgentEarningService>,
    /// FinancialPeriod service
    pub financial_period_service: Arc<FinancialPeriodService>,
    /// Payment service
    pub payment_service: Arc<PaymentService>,
    /// PaymentGatewayDetail service
    pub payment_gateway_detail_service: Arc<PaymentGatewayDetailService>,
    /// PaymentFee service
    pub payment_fee_service: Arc<PaymentFeeService>,
    /// Invoice service
    pub invoice_service: Arc<InvoiceService>,
    /// InvoiceParty service
    pub invoice_party_service: Arc<InvoicePartyService>,
    /// InvoiceLineItem service
    pub invoice_line_item_service: Arc<InvoiceLineItemService>,
    /// ProviderBankAccount service
    pub provider_bank_account_service: Arc<ProviderBankAccountService>,
    /// RefundRequest service
    pub refund_request_service: Arc<RefundRequestService>,
    /// Settlement service
    pub settlement_service: Arc<SettlementService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        agent_earning_service: Arc<AgentEarningService>,
        financial_period_service: Arc<FinancialPeriodService>,
        payment_service: Arc<PaymentService>,
        payment_gateway_detail_service: Arc<PaymentGatewayDetailService>,
        payment_fee_service: Arc<PaymentFeeService>,
        invoice_service: Arc<InvoiceService>,
        invoice_party_service: Arc<InvoicePartyService>,
        invoice_line_item_service: Arc<InvoiceLineItemService>,
        provider_bank_account_service: Arc<ProviderBankAccountService>,
        refund_request_service: Arc<RefundRequestService>,
        settlement_service: Arc<SettlementService>
    ) -> Self {
        Self {
            agent_earning_service,
            financial_period_service,
            payment_service,
            payment_gateway_detail_service,
            payment_fee_service,
            invoice_service,
            invoice_party_service,
            invoice_line_item_service,
            provider_bank_account_service,
            refund_request_service,
            settlement_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::BillingModule) -> Self {
        Self {
            agent_earning_service: module.agent_earning_service.clone(),
            financial_period_service: module.financial_period_service.clone(),
            payment_service: module.payment_service.clone(),
            payment_gateway_detail_service: module.payment_gateway_detail_service.clone(),
            payment_fee_service: module.payment_fee_service.clone(),
            invoice_service: module.invoice_service.clone(),
            invoice_party_service: module.invoice_party_service.clone(),
            invoice_line_item_service: module.invoice_line_item_service.clone(),
            provider_bank_account_service: module.provider_bank_account_service.clone(),
            refund_request_service: module.refund_request_service.clone(),
            settlement_service: module.settlement_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    agent_earning_service: Option<Arc<AgentEarningService>>,
    financial_period_service: Option<Arc<FinancialPeriodService>>,
    payment_service: Option<Arc<PaymentService>>,
    payment_gateway_detail_service: Option<Arc<PaymentGatewayDetailService>>,
    payment_fee_service: Option<Arc<PaymentFeeService>>,
    invoice_service: Option<Arc<InvoiceService>>,
    invoice_party_service: Option<Arc<InvoicePartyService>>,
    invoice_line_item_service: Option<Arc<InvoiceLineItemService>>,
    provider_bank_account_service: Option<Arc<ProviderBankAccountService>>,
    refund_request_service: Option<Arc<RefundRequestService>>,
    settlement_service: Option<Arc<SettlementService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the AgentEarning service.
    pub fn with_agent_earning_service(mut self, service: Arc<AgentEarningService>) -> Self {
        self.agent_earning_service = Some(service);
        self
    }

    /// Set the FinancialPeriod service.
    pub fn with_financial_period_service(mut self, service: Arc<FinancialPeriodService>) -> Self {
        self.financial_period_service = Some(service);
        self
    }

    /// Set the Payment service.
    pub fn with_payment_service(mut self, service: Arc<PaymentService>) -> Self {
        self.payment_service = Some(service);
        self
    }

    /// Set the PaymentGatewayDetail service.
    pub fn with_payment_gateway_detail_service(mut self, service: Arc<PaymentGatewayDetailService>) -> Self {
        self.payment_gateway_detail_service = Some(service);
        self
    }

    /// Set the PaymentFee service.
    pub fn with_payment_fee_service(mut self, service: Arc<PaymentFeeService>) -> Self {
        self.payment_fee_service = Some(service);
        self
    }

    /// Set the Invoice service.
    pub fn with_invoice_service(mut self, service: Arc<InvoiceService>) -> Self {
        self.invoice_service = Some(service);
        self
    }

    /// Set the InvoiceParty service.
    pub fn with_invoice_party_service(mut self, service: Arc<InvoicePartyService>) -> Self {
        self.invoice_party_service = Some(service);
        self
    }

    /// Set the InvoiceLineItem service.
    pub fn with_invoice_line_item_service(mut self, service: Arc<InvoiceLineItemService>) -> Self {
        self.invoice_line_item_service = Some(service);
        self
    }

    /// Set the ProviderBankAccount service.
    pub fn with_provider_bank_account_service(mut self, service: Arc<ProviderBankAccountService>) -> Self {
        self.provider_bank_account_service = Some(service);
        self
    }

    /// Set the RefundRequest service.
    pub fn with_refund_request_service(mut self, service: Arc<RefundRequestService>) -> Self {
        self.refund_request_service = Some(service);
        self
    }

    /// Set the Settlement service.
    pub fn with_settlement_service(mut self, service: Arc<SettlementService>) -> Self {
        self.settlement_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            agent_earning_service: self.agent_earning_service.expect("agent_earning_service is required"),
            financial_period_service: self.financial_period_service.expect("financial_period_service is required"),
            payment_service: self.payment_service.expect("payment_service is required"),
            payment_gateway_detail_service: self.payment_gateway_detail_service.expect("payment_gateway_detail_service is required"),
            payment_fee_service: self.payment_fee_service.expect("payment_fee_service is required"),
            invoice_service: self.invoice_service.expect("invoice_service is required"),
            invoice_party_service: self.invoice_party_service.expect("invoice_party_service is required"),
            invoice_line_item_service: self.invoice_line_item_service.expect("invoice_line_item_service is required"),
            provider_bank_account_service: self.provider_bank_account_service.expect("provider_bank_account_service is required"),
            refund_request_service: self.refund_request_service.expect("refund_request_service is required"),
            settlement_service: self.settlement_service.expect("settlement_service is required"),
        }
    }
}
