//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    invoice_tax_line_handler::create_invoice_tax_line_routes,
    payment_schedule_handler::create_payment_schedule_routes,
    payment_term_handler::create_payment_term_routes,
    payment_term_line_handler::create_payment_term_line_routes,
    purchase_invoice_handler::create_purchase_invoice_routes,
    purchase_invoice_line_handler::create_purchase_invoice_line_routes,
    sales_invoice_handler::create_sales_invoice_routes,
    sales_invoice_line_handler::create_sales_invoice_line_routes,
};

use crate::application::service::{
    InvoiceTaxLineService,
    PaymentScheduleService,
    PaymentTermService,
    PaymentTermLineService,
    PurchaseInvoiceService,
    PurchaseInvoiceLineService,
    SalesInvoiceService,
    SalesInvoiceLineService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub invoice_tax_line: Arc<InvoiceTaxLineService>,
    pub payment_schedule: Arc<PaymentScheduleService>,
    pub payment_term: Arc<PaymentTermService>,
    pub payment_term_line: Arc<PaymentTermLineService>,
    pub purchase_invoice: Arc<PurchaseInvoiceService>,
    pub purchase_invoice_line: Arc<PurchaseInvoiceLineService>,
    pub sales_invoice: Arc<SalesInvoiceService>,
    pub sales_invoice_line: Arc<SalesInvoiceLineService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // InvoiceTaxLine routes (12 Backbone endpoints)
        .merge(create_invoice_tax_line_routes(services.invoice_tax_line))
        // PaymentSchedule routes (12 Backbone endpoints)
        .merge(create_payment_schedule_routes(services.payment_schedule))
        // PaymentTerm routes (12 Backbone endpoints)
        .merge(create_payment_term_routes(services.payment_term))
        // PaymentTermLine routes (12 Backbone endpoints)
        .merge(create_payment_term_line_routes(services.payment_term_line))
        // PurchaseInvoice routes (12 Backbone endpoints)
        .merge(create_purchase_invoice_routes(services.purchase_invoice))
        // PurchaseInvoiceLine routes (12 Backbone endpoints)
        .merge(create_purchase_invoice_line_routes(services.purchase_invoice_line))
        // SalesInvoice routes (12 Backbone endpoints)
        .merge(create_sales_invoice_routes(services.sales_invoice))
        // SalesInvoiceLine routes (12 Backbone endpoints)
        .merge(create_sales_invoice_line_routes(services.sales_invoice_line))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn invoice_tax_line_routes(service: Arc<InvoiceTaxLineService>) -> Router {
        create_invoice_tax_line_routes(service)
    }

    pub fn payment_schedule_routes(service: Arc<PaymentScheduleService>) -> Router {
        create_payment_schedule_routes(service)
    }

    pub fn payment_term_routes(service: Arc<PaymentTermService>) -> Router {
        create_payment_term_routes(service)
    }

    pub fn payment_term_line_routes(service: Arc<PaymentTermLineService>) -> Router {
        create_payment_term_line_routes(service)
    }

    pub fn purchase_invoice_routes(service: Arc<PurchaseInvoiceService>) -> Router {
        create_purchase_invoice_routes(service)
    }

    pub fn purchase_invoice_line_routes(service: Arc<PurchaseInvoiceLineService>) -> Router {
        create_purchase_invoice_line_routes(service)
    }

    pub fn sales_invoice_routes(service: Arc<SalesInvoiceService>) -> Router {
        create_sales_invoice_routes(service)
    }

    pub fn sales_invoice_line_routes(service: Arc<SalesInvoiceLineService>) -> Router {
        create_sales_invoice_line_routes(service)
    }

}
