//! Public types for Billing module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// ============================================================================
// AGENTEARNING TYPES
// ============================================================================

/// Type-safe ID for AgentEarning
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AgentEarningId(pub Uuid);

impl AgentEarningId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AgentEarningId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AgentEarningId> for Uuid {
    fn from(id: AgentEarningId) -> Self {
        id.0
    }
}

/// Data transfer object for AgentEarning
///
/// This is the public representation of AgentEarning for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentEarningDto {
    pub id: AgentEarningId,
    pub agent_id: Uuid,
    pub task_id: Option<Uuid>,
    pub order_id: Option<Uuid>,
    pub earning_type: EarningType,
    pub description: Option<String>,
    pub currency: String,
    pub base_amount: Decimal,
    pub distance_km: Option<Decimal>,
    pub distance_bonus: Decimal,
    pub time_bonus: Decimal,
    pub surge_bonus: Decimal,
    pub incentive_bonus: Decimal,
    pub tip_amount: Decimal,
    pub deduction_amount: Decimal,
    pub deduction_reason: Option<String>,
    pub total_earning: Decimal,
    pub status: EarningStatus,
    pub earned_at: DateTime<Utc>,
    pub earning_date: NaiveDate,
    pub is_paid: bool,
    pub payout_id: Option<Uuid>,
    pub paid_at: Option<DateTime<Utc>>,
    pub cod_collected: Decimal,
    pub cod_deposited: bool,
    pub cod_deposited_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of AgentEarning for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentEarningSummary {
    pub id: AgentEarningId,
    pub status: EarningStatus,
}

/// Reference to AgentEarning for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentEarningRef {
    pub id: AgentEarningId,
}

// ============================================================================
// FINANCIALPERIOD TYPES
// ============================================================================

/// Type-safe ID for FinancialPeriod
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct FinancialPeriodId(pub Uuid);

impl FinancialPeriodId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for FinancialPeriodId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<FinancialPeriodId> for Uuid {
    fn from(id: FinancialPeriodId) -> Self {
        id.0
    }
}

/// Data transfer object for FinancialPeriod
///
/// This is the public representation of FinancialPeriod for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinancialPeriodDto {
    pub id: FinancialPeriodId,
    pub provider_id: Uuid,
    pub period_type: FinancialPeriodType,
    pub period_start: DateTime<Utc>,
    pub period_end: DateTime<Utc>,
    pub fiscal_year: i32,
    pub fiscal_month: Option<i32>,
    pub gross_revenue: Decimal,
    pub discounts_given: Decimal,
    pub refunds_issued: Decimal,
    pub net_revenue: Decimal,
    pub cogs: Decimal,
    pub labor_cost: Decimal,
    pub material_cost: Decimal,
    pub utility_expense: Decimal,
    pub maintenance_expense: Decimal,
    pub delivery_expense: Decimal,
    pub other_expense: Decimal,
    pub platform_commission: Decimal,
    pub transaction_fees: Decimal,
    pub subscription_fees: Decimal,
    pub gross_profit: Decimal,
    pub operating_profit: Decimal,
    pub net_profit: Decimal,
    pub gross_margin_percent: Option<Decimal>,
    pub operating_margin_percent: Option<Decimal>,
    pub net_margin_percent: Option<Decimal>,
    pub revenue_growth_percent: Option<Decimal>,
    pub profit_growth_percent: Option<Decimal>,
    pub average_order_value: Option<Decimal>,
    pub cost_per_kg: Option<Decimal>,
    pub cost_per_order: Option<Decimal>,
    pub profit_per_kg: Option<Decimal>,
    pub profit_per_order: Option<Decimal>,
    pub pnl_report_url: Option<String>,
    pub report_generated_at: Option<DateTime<Utc>>,
    pub status: FinancialPeriodStatus,
    pub closed_at: Option<DateTime<Utc>>,
    pub closed_by: Option<Uuid>,
    pub currency: String,
    pub notes: Option<String>,
    pub data: serde_json::Value,
    pub metadata: serde_json::Value,
}

/// Summary view of FinancialPeriod for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinancialPeriodSummary {
    pub id: FinancialPeriodId,
    pub status: FinancialPeriodStatus,
}

/// Reference to FinancialPeriod for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinancialPeriodRef {
    pub id: FinancialPeriodId,
}

// ============================================================================
// PAYMENT TYPES
// ============================================================================

/// Type-safe ID for Payment
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PaymentId(pub Uuid);

impl PaymentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PaymentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PaymentId> for Uuid {
    fn from(id: PaymentId) -> Self {
        id.0
    }
}

/// Data transfer object for Payment
///
/// This is the public representation of Payment for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentDto {
    pub id: PaymentId,
    pub payment_number: String,
    pub payable_type: PayableType,
    pub payable_id: Uuid,
    pub order_id: Option<Uuid>,
    pub payer_type: PayerType,
    pub payer_id: Uuid,
    pub payee_type: PayeeType,
    pub payee_id: Option<Uuid>,
    pub currency: String,
    pub amount: Decimal,
    pub net_amount: Decimal,
    pub gateway: PaymentGateway,
    pub channel: PaymentChannel,
    pub status: PaymentTransactionStatus,
    pub expires_at: Option<DateTime<Utc>>,
    pub paid_at: Option<DateTime<Utc>>,
    pub failed_at: Option<DateTime<Utc>>,
    pub cancelled_at: Option<DateTime<Utc>>,
    pub failure_code: Option<String>,
    pub failure_message: Option<String>,
    pub settlement_id: Option<Uuid>,
    pub description: Option<String>,
    pub notes: Option<String>,
    pub data: serde_json::Value,
    pub metadata: serde_json::Value,
}

/// Summary view of Payment for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentSummary {
    pub id: PaymentId,
    pub status: PaymentTransactionStatus,
}

/// Reference to Payment for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentRef {
    pub id: PaymentId,
}

// ============================================================================
// PAYMENTGATEWAYDETAIL TYPES
// ============================================================================

/// Type-safe ID for PaymentGatewayDetail
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PaymentGatewayDetailId(pub Uuid);

impl PaymentGatewayDetailId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PaymentGatewayDetailId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PaymentGatewayDetailId> for Uuid {
    fn from(id: PaymentGatewayDetailId) -> Self {
        id.0
    }
}

/// Data transfer object for PaymentGatewayDetail
///
/// This is the public representation of PaymentGatewayDetail for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayDetailDto {
    pub id: PaymentGatewayDetailId,
    pub payment_id: Uuid,
    pub external_id: Option<String>,
    pub invoice_url: Option<String>,
    pub checkout_url: Option<String>,
    pub qr_code_url: Option<String>,
    pub virtual_account_number: Option<String>,
    pub virtual_account_bank: Option<String>,
    pub webhook_payload: Option<serde_json::Value>,
    pub webhook_received_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of PaymentGatewayDetail for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayDetailSummary {
    pub id: PaymentGatewayDetailId,
}

/// Reference to PaymentGatewayDetail for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentGatewayDetailRef {
    pub id: PaymentGatewayDetailId,
}

// ============================================================================
// PAYMENTFEE TYPES
// ============================================================================

/// Type-safe ID for PaymentFee
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PaymentFeeId(pub Uuid);

impl PaymentFeeId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PaymentFeeId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PaymentFeeId> for Uuid {
    fn from(id: PaymentFeeId) -> Self {
        id.0
    }
}

/// Data transfer object for PaymentFee
///
/// This is the public representation of PaymentFee for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentFeeDto {
    pub id: PaymentFeeId,
    pub payment_id: Uuid,
    pub fee_type: PaymentFeeType,
    pub amount: Decimal,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of PaymentFee for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentFeeSummary {
    pub id: PaymentFeeId,
}

/// Reference to PaymentFee for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PaymentFeeRef {
    pub id: PaymentFeeId,
}

// ============================================================================
// INVOICE TYPES
// ============================================================================

/// Type-safe ID for Invoice
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct InvoiceId(pub Uuid);

impl InvoiceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for InvoiceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<InvoiceId> for Uuid {
    fn from(id: InvoiceId) -> Self {
        id.0
    }
}

/// Data transfer object for Invoice
///
/// This is the public representation of Invoice for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoiceDto {
    pub id: InvoiceId,
    pub invoice_number: String,
    pub invoice_type: InvoiceType,
    pub invoiceable_type: InvoiceableType,
    pub invoiceable_id: Uuid,
    pub order_id: Option<Uuid>,
    pub settlement_id: Option<Uuid>,
    pub issue_date: NaiveDate,
    pub due_date: Option<NaiveDate>,
    pub currency: String,
    pub subtotal: Decimal,
    pub discount_amount: Decimal,
    pub tax_amount: Decimal,
    pub tax_rate: Option<Decimal>,
    pub total_amount: Decimal,
    pub status: InvoiceStatus,
    pub sent_via: Option<String>,
    pub paid_at: Option<DateTime<Utc>>,
    pub payment_id: Option<Uuid>,
    pub pdf_url: Option<String>,
    pub pdf_generated_at: Option<DateTime<Utc>>,
    pub notes: Option<String>,
    pub terms: Option<String>,
    pub footer: Option<String>,
    pub data: serde_json::Value,
    pub metadata: serde_json::Value,
}

/// Summary view of Invoice for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoiceSummary {
    pub id: InvoiceId,
    pub status: InvoiceStatus,
}

/// Reference to Invoice for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoiceRef {
    pub id: InvoiceId,
}

// ============================================================================
// INVOICEPARTY TYPES
// ============================================================================

/// Type-safe ID for InvoiceParty
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct InvoicePartyId(pub Uuid);

impl InvoicePartyId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for InvoicePartyId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<InvoicePartyId> for Uuid {
    fn from(id: InvoicePartyId) -> Self {
        id.0
    }
}

/// Data transfer object for InvoiceParty
///
/// This is the public representation of InvoiceParty for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoicePartyDto {
    pub id: InvoicePartyId,
    pub invoice_id: Uuid,
    pub role: InvoicePartyRole,
    pub party_type: InvoicePartyType,
    pub party_id: Option<Uuid>,
    pub name: String,
    pub email: Option<String>,
    pub address: Option<String>,
    pub tax_id: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of InvoiceParty for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoicePartySummary {
    pub id: InvoicePartyId,
    pub name: String,
    pub email: Option<String>,
}

/// Reference to InvoiceParty for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoicePartyRef {
    pub id: InvoicePartyId,
}

// ============================================================================
// INVOICELINEITEM TYPES
// ============================================================================

/// Type-safe ID for InvoiceLineItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct InvoiceLineItemId(pub Uuid);

impl InvoiceLineItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for InvoiceLineItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<InvoiceLineItemId> for Uuid {
    fn from(id: InvoiceLineItemId) -> Self {
        id.0
    }
}

/// Data transfer object for InvoiceLineItem
///
/// This is the public representation of InvoiceLineItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoiceLineItemDto {
    pub id: InvoiceLineItemId,
    pub invoice_id: Uuid,
    pub sort_order: i32,
    pub description: String,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub amount: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of InvoiceLineItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoiceLineItemSummary {
    pub id: InvoiceLineItemId,
}

/// Reference to InvoiceLineItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InvoiceLineItemRef {
    pub id: InvoiceLineItemId,
}

// ============================================================================
// PROVIDERBANKACCOUNT TYPES
// ============================================================================

/// Type-safe ID for ProviderBankAccount
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ProviderBankAccountId(pub Uuid);

impl ProviderBankAccountId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ProviderBankAccountId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ProviderBankAccountId> for Uuid {
    fn from(id: ProviderBankAccountId) -> Self {
        id.0
    }
}

/// Data transfer object for ProviderBankAccount
///
/// This is the public representation of ProviderBankAccount for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderBankAccountDto {
    pub id: ProviderBankAccountId,
    pub provider_id: Uuid,
    pub bank_code: String,
    pub bank_name: String,
    pub account_number: String,
    pub account_name: String,
    pub account_type: BankAccountType,
    pub branch_name: Option<String>,
    pub branch_code: Option<String>,
    pub swift_code: Option<String>,
    pub status: BankAccountStatus,
    pub is_verified: bool,
    pub verified_at: Option<DateTime<Utc>>,
    pub verified_by: Option<Uuid>,
    pub verification_method: Option<VerificationMethod>,
    pub verification_notes: Option<String>,
    pub rejection_reason: Option<String>,
    pub rejected_at: Option<DateTime<Utc>>,
    pub rejected_by: Option<Uuid>,
    pub is_primary: bool,
    pub is_active: bool,
    pub gateway_account_id: Option<String>,
    pub gateway_status: Option<String>,
    pub gateway_metadata: serde_json::Value,
    pub document_url: Option<String>,
    pub document_type: Option<String>,
    pub total_settlements: i32,
    pub total_amount_received: Decimal,
    pub last_settlement_at: Option<DateTime<Utc>>,
    pub last_settlement_amount: Option<Decimal>,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of ProviderBankAccount for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderBankAccountSummary {
    pub id: ProviderBankAccountId,
    pub bank_name: String,
    pub account_name: String,
    pub branch_name: Option<String>,
    pub status: BankAccountStatus,
}

/// Reference to ProviderBankAccount for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderBankAccountRef {
    pub id: ProviderBankAccountId,
}

// ============================================================================
// REFUNDREQUEST TYPES
// ============================================================================

/// Type-safe ID for RefundRequest
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RefundRequestId(pub Uuid);

impl RefundRequestId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for RefundRequestId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<RefundRequestId> for Uuid {
    fn from(id: RefundRequestId) -> Self {
        id.0
    }
}

/// Data transfer object for RefundRequest
///
/// This is the public representation of RefundRequest for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RefundRequestDto {
    pub id: RefundRequestId,
    pub refund_number: String,
    pub payment_id: Uuid,
    pub order_id: Option<Uuid>,
    pub requester_type: String,
    pub requester_id: Uuid,
    pub requester_name: Option<String>,
    pub currency: String,
    pub original_amount: Decimal,
    pub requested_amount: Decimal,
    pub approved_amount: Option<Decimal>,
    pub refunded_amount: Decimal,
    pub reason: RefundReason,
    pub reason_detail: Option<String>,
    pub evidence_urls: serde_json::Value,
    pub status: RefundStatus,
    pub reviewed_by: Option<Uuid>,
    pub reviewed_at: Option<DateTime<Utc>>,
    pub review_notes: Option<String>,
    pub approved_by: Option<Uuid>,
    pub approved_at: Option<DateTime<Utc>>,
    pub approval_notes: Option<String>,
    pub rejected_by: Option<Uuid>,
    pub rejected_at: Option<DateTime<Utc>>,
    pub rejection_reason: Option<String>,
    pub processing_started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub failed_at: Option<DateTime<Utc>>,
    pub failure_reason: Option<String>,
    pub gateway_refund_id: Option<String>,
    pub gateway_status: Option<String>,
    pub refund_method: Option<RefundMethod>,
    pub bank_name: Option<String>,
    pub account_number: Option<String>,
    pub account_name: Option<String>,
    pub customer_notified: bool,
    pub customer_notified_at: Option<DateTime<Utc>>,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of RefundRequest for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RefundRequestSummary {
    pub id: RefundRequestId,
    pub requester_name: Option<String>,
    pub status: RefundStatus,
    pub bank_name: Option<String>,
    pub account_name: Option<String>,
}

/// Reference to RefundRequest for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RefundRequestRef {
    pub id: RefundRequestId,
}

// ============================================================================
// SETTLEMENT TYPES
// ============================================================================

/// Type-safe ID for Settlement
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SettlementId(pub Uuid);

impl SettlementId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SettlementId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SettlementId> for Uuid {
    fn from(id: SettlementId) -> Self {
        id.0
    }
}

/// Data transfer object for Settlement
///
/// This is the public representation of Settlement for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SettlementDto {
    pub id: SettlementId,
    pub settlement_number: String,
    pub provider_id: Uuid,
    pub period_start: DateTime<Utc>,
    pub period_end: DateTime<Utc>,
    pub frequency: SettlementFrequency,
    pub currency: String,
    pub gross_amount: Decimal,
    pub platform_commission: Decimal,
    pub platform_commission_rate: Decimal,
    pub transaction_fees: Decimal,
    pub payment_gateway_fees: Decimal,
    pub refunds_amount: Decimal,
    pub adjustments_amount: Decimal,
    pub adjustment_notes: Option<String>,
    pub withholding_tax: Decimal,
    pub withholding_tax_rate: Option<Decimal>,
    pub net_amount: Decimal,
    pub bank_account_id: Option<Uuid>,
    pub status: SettlementStatus,
    pub scheduled_at: Option<DateTime<Utc>>,
    pub processing_started_at: Option<DateTime<Utc>>,
    pub completed_at: Option<DateTime<Utc>>,
    pub failed_at: Option<DateTime<Utc>>,
    pub failure_reason: Option<String>,
    pub transfer_reference: Option<String>,
    pub transfer_receipt_url: Option<String>,
    pub is_on_hold: bool,
    pub hold_reason: Option<String>,
    pub held_by: Option<Uuid>,
    pub held_at: Option<DateTime<Utc>>,
    pub released_by: Option<Uuid>,
    pub released_at: Option<DateTime<Utc>>,
    pub invoice_id: Option<Uuid>,
    pub invoice_generated: bool,
    pub notes: Option<String>,
    pub data: serde_json::Value,
    pub metadata: serde_json::Value,
}

/// Summary view of Settlement for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SettlementSummary {
    pub id: SettlementId,
    pub status: SettlementStatus,
}

/// Reference to Settlement for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SettlementRef {
    pub id: SettlementId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
