//! Use case type aliases for FinancialPeriod aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateFinancialPeriodDto, UpdateFinancialPeriodDto};
use crate::application::service::FinancialPeriodService;
use crate::domain::entity::FinancialPeriod;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateFinancialPeriodUseCase = CreateUseCase<FinancialPeriod, CreateFinancialPeriodDto, FinancialPeriodService>;
pub type UpdateFinancialPeriodUseCase = UpdateUseCase<FinancialPeriod, UpdateFinancialPeriodDto, FinancialPeriodService>;
pub type GetFinancialPeriodUseCase    = GetUseCase<FinancialPeriod, FinancialPeriodService>;
pub type DeleteFinancialPeriodUseCase = DeleteUseCase<FinancialPeriod, FinancialPeriodService>;
pub type ListFinancialPeriodUseCase   = ListUseCase<FinancialPeriod, FinancialPeriodService>;

// <<< CUSTOM
// END CUSTOM
