//! Use case type aliases for InvoiceTaxLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateInvoiceTaxLineDto, UpdateInvoiceTaxLineDto};
use crate::application::service::InvoiceTaxLineService;
use crate::domain::entity::InvoiceTaxLine;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateInvoiceTaxLineUseCase = CreateUseCase<InvoiceTaxLine, CreateInvoiceTaxLineDto, InvoiceTaxLineService>;
pub type UpdateInvoiceTaxLineUseCase = UpdateUseCase<InvoiceTaxLine, UpdateInvoiceTaxLineDto, InvoiceTaxLineService>;
pub type GetInvoiceTaxLineUseCase    = GetUseCase<InvoiceTaxLine, InvoiceTaxLineService>;
pub type DeleteInvoiceTaxLineUseCase = DeleteUseCase<InvoiceTaxLine, InvoiceTaxLineService>;
pub type ListInvoiceTaxLineUseCase   = ListUseCase<InvoiceTaxLine, InvoiceTaxLineService>;

// <<< CUSTOM
// END CUSTOM
