//! Use case type aliases for Invoice aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateInvoiceDto, UpdateInvoiceDto};
use crate::application::service::InvoiceService;
use crate::domain::entity::Invoice;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateInvoiceUseCase = CreateUseCase<Invoice, CreateInvoiceDto, InvoiceService>;
pub type UpdateInvoiceUseCase = UpdateUseCase<Invoice, UpdateInvoiceDto, InvoiceService>;
pub type GetInvoiceUseCase    = GetUseCase<Invoice, InvoiceService>;
pub type DeleteInvoiceUseCase = DeleteUseCase<Invoice, InvoiceService>;
pub type ListInvoiceUseCase   = ListUseCase<Invoice, InvoiceService>;

// <<< CUSTOM
// END CUSTOM
