//! Use case type aliases for InvoiceLineItem aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateInvoiceLineItemDto, UpdateInvoiceLineItemDto};
use crate::application::service::InvoiceLineItemService;
use crate::domain::entity::InvoiceLineItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateInvoiceLineItemUseCase = CreateUseCase<InvoiceLineItem, CreateInvoiceLineItemDto, InvoiceLineItemService>;
pub type UpdateInvoiceLineItemUseCase = UpdateUseCase<InvoiceLineItem, UpdateInvoiceLineItemDto, InvoiceLineItemService>;
pub type GetInvoiceLineItemUseCase    = GetUseCase<InvoiceLineItem, InvoiceLineItemService>;
pub type DeleteInvoiceLineItemUseCase = DeleteUseCase<InvoiceLineItem, InvoiceLineItemService>;
pub type ListInvoiceLineItemUseCase   = ListUseCase<InvoiceLineItem, InvoiceLineItemService>;

// <<< CUSTOM
// END CUSTOM
