//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod invoice_tax_line_usecases;
pub mod payment_schedule_usecases;
pub mod purchase_invoice_usecases;
pub mod purchase_invoice_line_usecases;
pub mod sales_invoice_usecases;
pub mod sales_invoice_line_usecases;

pub use invoice_tax_line_usecases::{
    CreateInvoiceTaxLineUseCase, UpdateInvoiceTaxLineUseCase, GetInvoiceTaxLineUseCase,
    DeleteInvoiceTaxLineUseCase, ListInvoiceTaxLineUseCase,
};
pub use payment_schedule_usecases::{
    CreatePaymentScheduleUseCase, UpdatePaymentScheduleUseCase, GetPaymentScheduleUseCase,
    DeletePaymentScheduleUseCase, ListPaymentScheduleUseCase,
};
pub use purchase_invoice_usecases::{
    CreatePurchaseInvoiceUseCase, UpdatePurchaseInvoiceUseCase, GetPurchaseInvoiceUseCase,
    DeletePurchaseInvoiceUseCase, ListPurchaseInvoiceUseCase,
};
pub use purchase_invoice_line_usecases::{
    CreatePurchaseInvoiceLineUseCase, UpdatePurchaseInvoiceLineUseCase, GetPurchaseInvoiceLineUseCase,
    DeletePurchaseInvoiceLineUseCase, ListPurchaseInvoiceLineUseCase,
};
pub use sales_invoice_usecases::{
    CreateSalesInvoiceUseCase, UpdateSalesInvoiceUseCase, GetSalesInvoiceUseCase,
    DeleteSalesInvoiceUseCase, ListSalesInvoiceUseCase,
};
pub use sales_invoice_line_usecases::{
    CreateSalesInvoiceLineUseCase, UpdateSalesInvoiceLineUseCase, GetSalesInvoiceLineUseCase,
    DeleteSalesInvoiceLineUseCase, ListSalesInvoiceLineUseCase,
};

// <<< CUSTOM
// END CUSTOM
