//! Use case type aliases for PaymentFee aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePaymentFeeDto, UpdatePaymentFeeDto};
use crate::application::service::PaymentFeeService;
use crate::domain::entity::PaymentFee;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePaymentFeeUseCase = CreateUseCase<PaymentFee, CreatePaymentFeeDto, PaymentFeeService>;
pub type UpdatePaymentFeeUseCase = UpdateUseCase<PaymentFee, UpdatePaymentFeeDto, PaymentFeeService>;
pub type GetPaymentFeeUseCase    = GetUseCase<PaymentFee, PaymentFeeService>;
pub type DeletePaymentFeeUseCase = DeleteUseCase<PaymentFee, PaymentFeeService>;
pub type ListPaymentFeeUseCase   = ListUseCase<PaymentFee, PaymentFeeService>;

// <<< CUSTOM
// END CUSTOM
