//! Use case type aliases for PurchaseInvoiceLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePurchaseInvoiceLineDto, UpdatePurchaseInvoiceLineDto};
use crate::application::service::PurchaseInvoiceLineService;
use crate::domain::entity::PurchaseInvoiceLine;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePurchaseInvoiceLineUseCase = CreateUseCase<PurchaseInvoiceLine, CreatePurchaseInvoiceLineDto, PurchaseInvoiceLineService>;
pub type UpdatePurchaseInvoiceLineUseCase = UpdateUseCase<PurchaseInvoiceLine, UpdatePurchaseInvoiceLineDto, PurchaseInvoiceLineService>;
pub type GetPurchaseInvoiceLineUseCase    = GetUseCase<PurchaseInvoiceLine, PurchaseInvoiceLineService>;
pub type DeletePurchaseInvoiceLineUseCase = DeleteUseCase<PurchaseInvoiceLine, PurchaseInvoiceLineService>;
pub type ListPurchaseInvoiceLineUseCase   = ListUseCase<PurchaseInvoiceLine, PurchaseInvoiceLineService>;

// <<< CUSTOM
// END CUSTOM
